#+STARTUP: content

* Security+ SY0-401
** Chapter 1: Measuring and weighing risk
*** Risk assessment
A process conducted in which threats, vulnerabilities, and impacts of a loss
are assessed.  Determines which risks are real/likely.  Coordination with the
Business Impact Analysis (BIA) determines course of action.
**** Computing risk assessment
Prioritize and determine which risks are acceptable.  NIST provides a guide
for conducting assessments.
***** Risk calculations
Risk impact terms:
- ALE: Annual Loss Expectancy.  A monetary measure of loss, every year.
- SLE: Single Loss Expectancy.  A monetary measure of loss for one event.  This
  is divided into AV (asset value) and EF (exposure factor).  SLE = AV * EF.
- ARO: Annualized Rate of Occurance.  Chance of an event occurring within a
  year, based on historical data.

Formula: SLE * ARO = ALE
***** Quantitative vs. qualitative risk assessment
Risk assessments are either qualitative (opinion-based and subjective) or
qualitative (cost-based and objective).  If a dollar cost can be assigned,
it's quantitative.
***** Additional risk terminology
- Likelihood: A score representing the possibility of threat initiation.  Goes
  from 10-0, with 10 being a certainty that the adversary will initiate a
  threat event.
- Threat vector: The way in which an attacker poses a threat.
- Mean Time Between Failures (MTBF): The measure of the anticipated incidence
  of failure for a system or component.  E.g., if a system's MTBF is 1 year,
  expect to replace it once a year.
- Mean Time to Failure (MTTF): The average time to failure for a
  non-repairable system.  Same as MTBF, but for non-repairable systems.
- Mean Time to Restore (MTTR): How long it takes to repair a system once a
  failure occurs.
- Recovery Time Objective (RTO): The maximum amount of downtime considered
  acceptable.  Agreed upon during BIA creation.
- Recovery Point Objective (RPO): The point in time from which the system needs
  to be restored.  The shorter the RPO time, the more expensive.
- Service Level Agreement (SLA): Formally defines service provided.
**** Acting on your risk assessment
- Risk Avoidance: Identifying a risk and deciding not to engage in actions
  associated with it.
- Risk Transference: Sharing some of the burden of the risk with another
  entity (e.g. using insurance).
- Risk Mitigation: Taking steps to reduce a risk.  E.g., Data Loss Prevention
  (DLP) systems monitor the content of systems ensure key content is not
  deleted/removed.
- Risk Deterrence: Warning the adversary about consequences, like posting
  prosecution policies or warning of intrusion detection.
- Risk Acceptance: The choice to make when the cost of implementing the other
  choices outweighs the harm of an identified risk.
**** Risks associated with cloud computing
Cloud computing implementations:
- PaaS: Vendors allow apps to be created and run on their infrastructure.
  E.g., AWS and Google Code.
- SaaS: Applications are remotely run over the Web.
- IaaS: Virtualized resources, billed by resource usage.

Risk-related issues:
- Regulatory compliance
- User privileges: Enforcing least privileges, reduced control.
- Data integration/segregation: Shared resources up data
  encryption/segregation requirements.
**** Risks associated with virtualization
- Breaking out of the VM: Data access issues.
- Network and security controls can intermingle: Granularity differences
  between network and VM admin tools.
- Most attacks occur through the hypervisor, giving attackers root-level
  access to all VMs.
*** Developing policies, standards, and guidelines
Policies provide high-level guidance, standards provide expectations, and
guidelines provide specific advice.
**** Implementing policies
- Scope Statement: Outlines what the policy intends to accomplish and which
  documents, laws, and practices it addresses.  Usually a single sentence.
- Policy Overview Statement: Provides the goal of the policy, its importance,
  and how to comply.  Usually a single paragraph.
- Policy Statement: The substance of the policy.  E.g., how to lock up the
  building at night.
- Accountability Statement: Who is responsible for ensuring the policy is
  enforced.
- Exception Statement: Guidance on how to deviate from the policy and an
  escalation contact.
**** Incorporating standards
Standards are derived from policies.  Provides enough detail that an audit can
be performed.

Key aspects of standards documents:
- Scope and Purpose: Explains/describes the intention.
- Roles and Responsibilities: Who is responsible for implementing, monitoring,
  and maintaining the standard.
- Reference Documents: Explains how the standard relates to the organization's
  policies, thereby connecting them.
- Performance Criteria: Outlines how to accomplish the task, including a
  relevant baseline and tech standards.
- Maintenance and Administrative Requirements: E.g., frequency of lock
  combination changes.
**** Following guidelines
Helps users comply with standards, often step-by-step processes to accomplish
tasks.

Contents of guidelines documents:
- Scope and Purpose: Overview of the guideline's intent.
- Roles and Responsibilities: Who is responsible for accomplishing tasks.
- Guideline Statements: Step-by-step instructions.
- Operational Considerations: Specify what duties are required and at what
  intervals.
**** Business policies to implement
Primary areas of concern:
- Separation of Duties Policies: Designed to reduce risk of fraud and prevent
  other losses.  May require more than one person to accomplish key
  processes.
- Privacy Policies: Define what controls are required to maintain data
  privacy.  A legal document informed by laws.
- Acceptable Use Policies (AUPs): Describe how employees can use company
  systems and resources, including consequences for misuse.  Also known as a
  Use Policy.
- Security Policies: Define what controls are required for security.
- Mandatory Vacations: Addresses dependence upon single persons and an
  opportunity to discover fraud.
- Job Rotation: Same motivation as mandatory vacations, with an emphasis on
  redundancy in skills.
- Least Privilege: Users are given only the permissions needed to perform work.
- Succession Planning: Outlines internal persons that have the ability to step
  into positions when they open up.  Identifies key roles.
**** Understanding control types and false positives/negatives
Once risks are identified, controls are put in place to address them.
Controls fall into three groups:
- Management: Risk assessment; planning; system and services acquisition;
  certification, accreditation, and security assessment.
- Operational: Personnel security, physical and environmental protection,
  contingency planning, configuration management, maintenance, system and
  information integrity, media protection, incident response, awareness and
  training.
- Technical: Identification and authentication, access control, audit and
  accountability, system and communication protection.

Once controls are implemented, audits should be performed.  While doing so,
pay attention to:
- False positives: Events flagged as anomalies that aren't really incidents.
- False negatives: Lack of alert on an real event.
**** Risk management best practices
Implemented with a BIA.  What is shown in industry to produce superior results
regarding business continuity.
***** Undertaking business impact analysis (BIA)
BIA is the process of evaluating critical systems to define impact and
recovery plans.  Focuses on impact a loss would have.

Key components:
- Identifying Critical Functions: Defines essential functions until restoration
  of full service.  Ensures Business Continuity Planning (BCP).
- Prioritizing Critical Business Functions: Categorizes essential/non-essential
  functions.  Useful allocating resources during recovery.
- Calculating a Timeframe for Critical Systems Loss: Evaluates maximum time a
  particular function can be unavailable.  Dictates contingencies to minimize
  loss when time is exceeded.
- Estimating the Tangible and Intangible Impact on the Organization: Details
  tangible (loss production/sales) and intangible (loss customer confidence)
  impact.
***** Identifying critical systems and components
Build systems that don't have a Single Point of Failure (SPOF) by adding
redundancy.  Factor weather, natural disaster, and utilities into contingency
plans.
***** High Availability (HA)
Measures used to keep services operational during an outage.  The goal is to
have 99.999% availability (five nines).
***** Redundancy
Systems either duplicated or fail over to other systems.  Failover is the
process reconstructing a system or switching to another when failure is
detected.  In networks, this involves failover network paths.  Includes
clustering (load balancing).
***** Fault tolerance
The ability of a system to sustain operation in event of component failure.
Stock spare parts and ensure power.  For parts, having N+1 is a common
strategy, where N is the number of parts in use.  For power, use UPSes with
surge protection or a backup generator.
***** RAID
- RAID 0: Disk striping.
- RAID 1: Disk mirroring.  Can alternatively be disk duplexing, which uses one
  more controller card (writing to both disks simultaneously).
- RAID 3: Disk striping with a parity disk.  Uses RAID 0 striping, but adds
  another disk for parity info.  Common in older systems.
- RAID 5: Disk striping with parity, spread across multiple disks.  Supports
  3-32 disks.  Can survive failure of only one drive.
**** Disaster recovery
Recovering system operations after a disaster.  Planning includes designing a
comprehensive backup plan of backup storage, procedures, and maintenance.
Prioritize critical systems.
***** Types of backups
Include both paper and computer records.
***** Disaster recovery planning
Keep backups of key data, databases, applications, and paper records.
**** Tabletop exercise
A method of accessing risk where a facilitator and participants discuss
possible situations and how to respond.
*** Review questions
1 C
2 A
3 D
4 A
5 B
6 D (B)
7 A
8 D
9 B (C)
10 E
11 C
12 D
13 D
14 C
15 B
16 C
17 C
18 A
19 C
20 A
*** Additional notes
- Change management: A structured approach to securing a company's assets.
** Chapter 2: Monitoring and diagnosing networks
*** Monitoring networks
**** Network monitors
- Sniffers: Another name for network monitors.  Enables examining the
  signaling and traffic that occurs on a network.
- Promiscuous mode: A NIC looking at any packet it sees on the network, even
  if the packet is not addressed to that NIC.
***** Monitoring system logs
Event logs: System logs that record various events that occur.  Includes many
types of logs, but security and access logs are most pertinent here.

For Windows, the two most important event logs are:
- Application Log: Contains events logged by programs, including errors.
  E.g., SQL Server uses this and the log can show DB compromise attempts.
- Security Log: Shows successful/unsuccessful login attempts and resource use
  (e.g. creating, opening, deleting files and other objects).  Event types to
  log can be specified.  Should always be changed to log both successful and
  failed login attempts.

In Linux, note:
- /var/log/faillog: Logs failed user logins.
- /var/log/apport.log: Logs application crashes.  Can sometimes reveal system
  compromise attempts or the presence of virii/spyware.
*** Hardening
Hardening means to lock down and secure an OS as much as practical.  Ensure
unneeded services are turned off, unneeded software is uninstalled, patches are
updated, user accounts are checked, etc.
**** Working with services
Part of OS hardening involves disable unnecessary services.

Tips:
- File and Print Servers: Primarily vulnerable to DoS.  Ensure only needed
  protocols are run.
- Networks with PC-Based Systems: Disable NetBIOS on servers or provide an
  effective firewall between them and the Internet.  NetBIOS ports are 135,
  137, 138, and 139.  On Unix systems, close port 111 (RPC).
- Directory Sharing: Limit to what is essential for system functions.  Hide
  root directories from browsing -- instead, designate subfolders.
***** Protecting management interfaces and applications
Admin interfaces should be restricted to only those admins who need it.
Protect server utilities and even workstation utilities like regedit.  Password
protect management functionality and consoles.

On Windows, use the Performance Monitor to look for possible illicit activity,
as it can do things like show excessive processor usage.
***** Software
Remove unneeded software.  On Windows, remove Windows components that commonly
come preinstalled (via Programs and Features).
**** Patches
A patch is an update to a system, adding new functionality or correcting bugs.
In a network environment, patches should be applied to a single machine and
tested first, as it's possible that patches could have problems.  In such
cases, not applying it is an option until a fix can be found.

Types of patches:
- Service pack: A periodic update that corrects problems in one version of a
  product.  Gets users to the current codebase for the product.
- Updates: Code fixes provided to individual customers experiencing critical
  problems that have no feasible workarounds.
- Security updates: Address security vulnerabilities.  Should be considered
  mandatory.  Should be deployed within 30 days of release.
**** User account control
Only active accounts should be operational and properly managed.  Along with
domain accounts, pay attention local accounts.  A common approach is to
configure a single machine, image it, then copy to other workstations.  This
can result in issues propagating throughout a network.

Tips:
- Disable unneeded accounts.  These can provide attack vectors.
- Accounts must have passwords that meet standards.  These should apply to
  domain and local accounts.
- Apply least privileges.

Disable these accounts:
- Employees who have left the company: Should be disabled the minute an
  employee is terminated, regardless of termination type.  Disable instead of
  delete accounts.
- Temporary employees: Also disable immediately.
- Default guest accounts: Commonly known to exist.
**** Filesystems
Windows:
- MS FAT: Designed for small drives.  FAT-16 preceded FAT-32.  Only allows
  share-level and user-level access privileges.  If a user has write or change
  access to a directory, they have access to any file in the directory.
  Highly insecure.
- MS NTFS (New Technology FS): Introduced in Windows NT.  Addresses growing
  disk sizes, security concerns, and file stability.  Unlike FAT, includes
  transaction-tracking, which allows backing out any disk operation in
  progress when the OS crashes or loses power.  Files, directories, and
  volumes each have their own security.  Tracks security in ACLs.

Windows systems have hidden admin shares with names ending in dollar signs
(e.g., admin$) for remote administration.

Not covered: ext3, ext4, XFS on Linux; HFS, HFS+ on OSX.
*** Securing the network
- MAC limiting and filtering: Limit network access to known MAC addresses.
  Most routers have this option.  Find MAC address using ipconfig /all or
  ifconfig/ip command.  Not foolproof as MAC addresses can be changed.
- 802.1X: Add port authentication to MAC filtering secures on a switch port
  level, vastly increasing security.  802.1X defines port-based security for
  wireless network access control.  802.1X offers authentication and defines
  the Extensible Authentication Protocol (EAP) over IEEE 802.  This is EAP
  over LAN (EAPOL).  Authentication relies on authentication servers instead
  of access points and switches doing it themselves.
- Disable unused ports: Disable the service and block the port with a firewall.
- Rogue machine detection: Scan for these.
*** Security posture
Document a baseline configuration, representing a known secure state.
Reporting will be relative to this state.  The baseline also addresses specific
compliance issues and regulatory standards.  Include network utilization stats,
useful in identifying DoS attacks.
**** Continuous security monitoring
Ongoing monitoring involving network traffic levels, routine evaluations for
regulatory compliance, and checks of network security device configurations.
**** Security audits
Scheduled, in-depth checks of security.  Includes:
- Review of security logs.
- Review of policies and compliance with policies.
- A check of security device configuration.
- Review of incident response reports.

Scope and frequency are determined by the organization, subject to
needs/budget.
**** Setting a remediation policy
Monitoring may uncover gaps between the baseline and current network state.  A
remediation plan must be implemented.  A possible classification of gaps:
- Minor: Does not pose an immediate threat.
- Serious: Could pose an  immediate threat, but one unlikely.
- Critical: Poses an immediate threat that must be addressed.
*** Reporting security issues
**** Alarms
Indications of an ongoing current problem requiring immediate response.  Alarm
rates may indicate trends.  After solving the problem, look for indicators that
the condition is not isolated.  A notification system should notify appropriate
staff.  That staff needs a procedure to report incident specifics and how it
was addressed.
**** Alerts
Issues requiring attention but not likely to bring down the system.  Alerts
can refer to Event Viewer events, or AV industry and OS alerts.
**** Trends
Trends in threats, like if a type of attack is currently common.  Also can
refer to organizational security profile trends.  E.g., audits finding
increased policy compliance or increased violation of software installation
policies.  Allow the taking of proactive security measures.
*** Differentiating between detection controls and prevention controls
Some controls exist to detect potential threats, others to prevent/minimize
them.  An intrusion detection system (IDS) detects, an intrusion prevention
system (IPS) prevents.  H-IDS is host based, N-IDS is network based.

Honeypot: A tool that is part detection and prevention.  Honeypots allow
themselves to be attacked to gain information of methods used in the attack.
Draws attackers away from high-value systems and provides attack strategy
intelligence.  If not configured properly, can be used to launch further
attacks.  Concepts to consider for honeypots/honeynets:
- Enticement: Luring someone into a plan/trap via invitation.
- Entrapment: Encouraging/inducing potential criminal activity when a desire
  is expressed not to go ahead.  Not legally acceptable.

Tar pit: Exists only to slow down attackers and does not collect data.
*** Review questions
1 C
2 B
3 C
4 A
5 A
6 A
7 B
8 B
9 A
10 B
11 C
12 D
13 C
14 A
15 B
16 D
17 C
18 A
19 A
20 B
*** Additional notes
Administrator: IDS person responsible for setting security posture.
** Chapter 3: Understanding devices and infrastructure
Intrastructure, network ports, and common protocols. A network is composed of
media and devices.
*** Mastering TCP/IP
Has numerous holes which are easy to plug once aware of their existence.
**** OSI relevance
OSI model is 7-layer.  TCP/IP precedes OSI and uses 4 layers and is used here.
**** Working with the TCP/IP suite
Layers:
- Application layer: E.g., HTTP, SMTP.
- Host-to-Host, or Transport layer: TCP or UDP (user datagram protocol).
- Internet layer: IP.
- Network Access, Network Interface, or Link layer: Network topology
  (essential for conveying information on a network).  Includes "media".

TCP/IP uses existing physical connections between systems, ignoring network
topology (which network controllers handle).

Concepts:
- Host: Any device connected to the network that runs the TCP/IP stack
  (protocol suite).
- Encapsulation: The process used to pass messages between layers.
***** The application layer
Highest layer.  Allows applications to access services or protocols to exchange
data.  Common protocols:
- HTTP
- HTTP Secure (HTTPS): Combines HTTP with SSL/TLS to provide encrypted
  communication.
  - SSL: Establishes a secure connection between two TCP-based machines.  Uses
    the handshake method of session establishment.  Maintains a session using
    symmetric encryption.
  - TLS: A security protocol that expands upon SSL.  May replace SSL and is
    already referred to as SSL 3.1, though doesn't interoperate with SSL.
- FTP: Allows connections to FTP servers for file uploads/downloadds.  Uses
  ports 20 and 21.  Inherently insecure.  FTP over SSL (FTPS) adds support for
  SSL cryptography.  There's also SSH FTP (SFTP), also known as Secure FTP.
  An alternative to FTP is SCP, using port 22.  This combines the remote copy
  program (RCP) with SSH.  Finally, there's Trivial FTP (TFTP), which allows
  file transfer without any user interaction.  TFTP should be avoided anywhere
  other options exist.
- SMTP: Email delivery.  Port 25.
- Telnet
- DNS: Allows resolving of hostnames to IPs.  Port 53.
- RDP: Allows Windows-based terminal servers.  Port 3389.
- SNMP: Simple Network Management Protocol.  Allows communication between
  network devices and a management console.  Used by routers, bridges, and
  intelligent hubs.
- POP3: Post Office Protocol, version 3.  Receiving email.  Port 110.  Often
  now replaced by IMAP on port 143.  POP was created to move email to clients
  and not keep it on the server, whereas IMAP stores email on the server for
  access.  Now, POP can now be configured to store on the server and IMAP to
  store only locally.
***** The host-to-host or transport layer
Session and datagram communications.
- TCP: Provides reliable, one-to-one, connection-oriented sessions.
  Establishes sessions and ensures packet reception.  Ensures packets are
  decoded and sequenced properly.  The connection persists during the only
  session.
- UDP: Provides unreliable, connectionless communication between hosts.  Faster
  than TCP.  No session synchronization.  Doesn't guarantee error-free
  communication.  Mainly used to send small packets of info.  The application
  is responsible for acknowledging correct reception of data.
***** The internet layer
Responsible for routing, IP addressing, and packaging.  Does most of the work
in establishing info exchange between hosts.  Four standard layer protocols:
- IP: Routable protocol responsible for IP addressing.  Fragments and
  reassembles message packets.  Only routes information, doesn't verify for
  accuracy (which is the domain of TCP).  Determines if a destination is known
  and, if so, routes info to it.  If destination is unknown, IP sends the
  packet to the router.
- Address Resolution Protocol (ARP): Resolves IP addresses into Network
  Interface layer addresses, including hardware addresses.  Resolves IPs to MAC
  addresses.
- Internet Control Message Protocol (ICMP): Provides maintenance and reporting
  functions.  Used by ping.  ICMP responds to ping requests or locally reports
  if the destination is unreachable.  Routers and other network devices use
  ICMP to report path info.
***** The network access layer
Responsible for placing and removing packets on the physical network via
communicating with the host's network adapters. When network topology or
technology is changed, TCP/IP only needs to know how to communicate with the
new network controller.  Can also communicate with multiple network topologies.
**** IPv4 and IPv6
IPv4: 32-bit addresses, IPv6: 128-bit addresses.  IPv6 includes mandatory
IPSec security.  Most systems support both.
**** Understanding encapsulation
Encapsulation allows a transport protocol to be sent across the network and
used by the equivalent protocol/service at the destination.  Allows higher
level protocols not to care what happens at lower levels.
**** Working with protocols and services
Ports, handshakes, and application interfaces.

Note: NetBIOS was originally an alternative to TCP/IP, but has since been
adapted to run on top of it.  It's widely used for name resolution and
registration in Windows-based environments.
***** Well-known ports
Ports identify how a communication process occurs.  Ports are special addresses
that allow communication between hosts.  The Internet Assigned Numbers
Authority (IANA) defines a list of well-known ports.

Port numbers are additional info added to TCP or UDP message headers.

TCP ports:
- 20 FTP (data channel)
- 21* FTP (control channel)
- 22* SSH and SCP
- 23 Telnet
- 25* SMTP
- 49 TACACS authentication service
- 80* HTTP
- 110* POP3
- 115 SFTP
- 119 NNTP
- 137 NetBIOS name service
- 138 NetBIOS datagram service
- 139* NetBIOS session
- 143* IMAP
- 389 LDAP
- 443* HTTPS
- 989 FTPS (data channel)
- 990 FTPS (control channel)
- 3389 MS WBT Server (RDP)

UDP ports:
- 22* SSH and SCP
- 49 TACACS authentication service
- 53* DNS
- 69 TFTP
- 80* HTTP
- 137 NetBIOS name service
- 138 NetBIOS datagram service
- 139* NetBIOS session
- 143* IMAP
- 161 SNMP
- 389 LDAP
- 989 FTPS (data channel)
- 990 FTPS (control channel)
- 3389 MS WBT Server (RDP)
***** Viewing the active TCP and UDP ports
- Windows: netstat lists local port -> foreign address.  netstat -a provides
  full listings.
- services file: A reference for common services/ports.
***** TCP three-way handshake
TCP is a connection-oriented protocol which establishes a session using a
three-way handshake:
- SYN: The client originates the connection, sending a TCP segment/message to
  the server.  This segment includes an initial sequence number (ISN) for the
  connection and a window size.
- SYN/ACK: The server responds with a TCP segment that contains its ISN and a
  value for its buffer/window size.
- ACK: The client sends back and acknowledgement of the server's sequence
  number.

A four-step process is used to close the connection.  The sequence numbers are
used so the server can handle simultaneous requests on the same port.  All
communication in a session uses the same sequence number.
***** Application programming interface
Here refers to the APIs used by programmers to create interfaces to TCP/IP.

MS uses the Windows Socket (Winsock) API to interface TCP/IP.
***** Other protocols to know
- iSCSI (Internet Small Computer Systems Interface): Uses port 860 and 3260.
  Allows data storage and transfers across the network.  Enables the creation
  of storage area networks (SANs).
- Fibre Channel: Same as iSCSI, but designed for only fibre-based networks.
  Later changed to use SCSI to create SANs.  A common protocol used is FCoE
  (Fibre Channel over Ethernet), which is not routable at the IP layer, and is
  only useful in small networks.
*** Designing a secure network
Consider these when designing the security topology of a network:
- Demilitarized zones (DMZs).
- Subnetting.
- VLANs.
- Remote access.
- NAT.
- Telephony.
- NACs.
**** Demilitarized zones
An area to place public servers accessible to people otherwise not trusted.
Doesn't allow access to other parts of the network.  Can be built/demarcated
using firewalls that can transmit in three directions:
- To the internal network.
- To the external Internet.
- To the public information (DMZ).

If a web server was on a DMZ, the firewall would direct HTTP traffic there,
whereas email would go to the internal network.

Bastion hosts: Hosts, routers, and firewalls that exist outside the DMZ and
open to the public.
**** Subnetting
Subnetting: Using a subnet mask to divide a network into smaller components.
These can be divided physically, logically, topologically, etc.

Subnetting uses bits from the host address to create the additional networks.
This can:
- Use IP addresses more effectively.
- Make the network more secure and manageable.

Subnets increase security by confining traffic to the network it needs to be
on, reducing network traffic and creating more broadcast domains (reducing
network-wide broadcast traffic).
**** Virtual local area networks (VLANs)
A VLAN allows creation of groups of users and systems, segmenting them on the
network.  Allows hiding of other segments and controlling access.  VLANs can
be set up to control the path data takes.  A good way to contain network
traffic to a certain area.

Can also be thought of as a network of hosts that act as if a physical wire
connects them, even though it doesn't exist.

VLANs reduce the number of broadcast domains by reducing their scope, improving
performance and manageability, and decreasing dependence on topology.  Most
importantly, it allows users with similar data sensitivity to be segmented
together.

Tunneling protocols: Adds the ability to create tunnels between networks that
can be more secure, support additional protocols, and provide virtual paths.
Can use encapsulation in other packets to be sent across a public network.

Types of tunneling:
- Point-to-Point Tunneling Protocol (PPTP): Supports encapsulation of PPP
  (point-to-point protocol) packets in a single point-to-point environment.  A
  low-end protocol.  Negotiation between hosts done is done in the clear, after
  which the channel is encrypted.  This is its major weakness.  A
  packet-capture device, like a sniffer, can capture the negotiation process
  and determine connection type and how the tunnel works.  MS created and uses
  PPTP.  Uses port 1723 on TCP.
- Layer 2 Tunneling Protocol (L2TP): Combined MS (PPTP) and Cisco (L2F)
  tunneling protocols.  Primarily point-to-point.  Supports multiple network
  protocols and can be used outside of TCP/IP.  Works over IPX, SNA, and IP,
  and can therefore act as a bridge between systems.  Its main problem is lack
  of data encryption, but this can be provided by IPSec.  Uses port 1701 on
  UDP.
- Secure Shell (SSH): Uses encryption to establish a connection.  Alternative
  to Telnet, FTP, and other clear-text programs.  Uses port 22 on TCP.
- Internet Protocol Security (IPSec): Not a tunneling protocol, but used in
  conjunction with them.  Mainly for LAN-to-LAN connections, but also used with
  dial-up.  Provides secure authentication and encryption of data and headers,
  making it highly secure.  Can work in:
  - Tunneling mode: Data or payload and headers are encrypted.
  - Transport mode: Only payload is encrypted.
**** Remote access
Tunnels create virtual connections between two systems/networks.  Data is
encapsulated in an mutually agreed protocol.  Data passed through tunnels
appears on the other side as part of the network.

Remote Access Servers (RAS): Any server service that offers the ability to
connect remote systems.  On Windows this is Routing and Remote Access (RRAS).
Connections are accomplished via dial-up/plain-old telephone services (POTS),
VPNs, ISDN, DSL, and cable modems.  RAS connections can be secure or not.
Virtual Network Computing (VNC) provides things like remote control of
computers, but has leaves a discoverable opening.  Should be configured as a
"manual start" service.
**** Network address translation (NAT)
NAT originally extended the number of usable IP addresses, but now allows
organizations to present a single IP address to the Internet for all
connections.  The NAT server provides IPs to the hosts in the network and
tracks inbound/outbound traffic.

NAT presents a limited number of connections to the network through a router
or NAT server.  Intruders will only know a single address.  The rest of the
network is hidden from the outside and acts as a firewall.  Most routers
support NAT.

Non-routable, private address ranges assigned by most NATs for internal use:
- 10.0.0.0 - 10.255.255.255.
- 172.16.0.0 - 172.31.255.255.
- 192.168.0.0 - 192.168.255.255.

Note: Port Address Translation (PAT) is also possible.  NAT can use multiple
public IP addresses, whereas PAT can only use one.  PAT is usually only used on
small, private networks.  MS's ICS is a PAT implementation.  Also, Destination
NAT (DNAT) can be used to redirect traffic for a virtual host to a real one.
**** Telephony
Telephony is the merger of IT and telephone systems.  Breaches here are just
as serious as any other.

Voice over IP (VoIP) can be sniffed and is susceptible to DoS attacks since it
uses UDP.  If a data network goes down, telephony can be lost.
**** Network Access Control (NAC)
Operational security includes NAC, authentication, and security topologies.

NAC is a set of standards defined by the network for clients attempting access.
NAC typically requires clients be virus-free and adhere to certain policies.
*** Understanding the various network infrastructure devices
Components encountered in a network.

Note: For network devices requiring default accounts to change settings, be
sure to change passwords.
**** Firewalls
Firewalls isolate one network from another.

The first line of network defense.  Can be standalone systems/included in
routers or servers or hardware-only/software-only.  Many firewalls are add-in
software for servers/workstations.

Appliances: Some firewalls are appliances.  Intended to be the primary device
separating two networks.  These are freestanding, self-contained devices,
requiring less maintenance.

Firewall functions include one or more of:
- Packet filter.
- Proxy firewall.
- Stateful packet inspection firewall.
***** Packet filter firewalls
Passes or blocks traffic to specific addresses based on the type of
application.  Doesn't analyze the data, only uses addressing info.  E.g., allow
port 80, block port 23.  Included in most routers.  Some allow specifying which
IPs can request which ports.
***** Proxy firewalls
An intermediary between outside/inside the network.  Examines data and makes
rule-based decisions about whether to forward/refuse requests.  Intercepts all
packets and reprocesses them for internal use, including the hiding of IPs.

Provides better security than packet filtering due to increased intelligence.
All internal requests are routed through the proxy, isolating users from the
external network.  Can also provide caching to increase efficiency.

Proxy firewalls typically use two NICs, in which case it's called a dual-homed
firewall.  One NIC is connected internally, the other externally.

Note: IP forwarding bypasses firewalls and uses the firewall as a router.
Probably don't want that on proxies.

Proxies can function at either:
- Application-level: Reads commands of protocols.  E.g., knowing about GET and
  PUT requests and having rules in regards to them.  An application-level proxy
  is needed for each protocol supported.  Many provide full auditing,
  accounting, etc.
- Circuit-level: Doesn't deal with the contents of packets processed.
***** Stateful packet inspection firewalls
Stateless firewalls make decisions based on the data that comes in (the current
packet), and not complex decisions.  Stateful packet inspection (SPI) filtering
keeps records for every communication channel and what the next should be.

Stateful inspection occurs at all levels of the network and provided added
security, especially for UDP and ICMP.  DoS attacks can overload the state
table and cause firewalls to shut down/reboot.
**** Routers
Primary device for connectivity between two or more networks.  Provides a path
between networks and joins networks.  Most routers can act as packet-filtering
firewalls.

Border routers: In conjunction with Channel Service Unit/Data Service Unit
(CSU/DSU), routers can translate from LAN framing to WAN framing (e.g. a router
connecting 100bT and T1 networks).  Needed due to LANs/WANs having different
protocols.

Zones: Router-divided subnetworks.

Routers maintain tables of destinations and local connections.  Contains info
about systems connected and where to forward requests for unknown destinations.
These tables grow as connections are made.

Protocols routers use for communication routing and other info:
- Routing Information Protocol (RIP).
- Border Gateway Protocol (BGP).
- Open Shortest Path First (OSPF).

Best practice is for a router to augment the defense of a firewall.

Routers can be configured statically (manually) or dynamically (where they
learn of other routers and use their info to build routing tables).
**** Switches
Multiport devices that improve network efficiency.  Switches contain small
amounts of info, usually only a table of MAC addresses.  Using virtual
circuits, they improve network efficiency.  Virtual circuits are more difficult
to examine with network monitors.  Combines some of the best features of
routers and hubs.

Only use switches internally because they only use MAC addresses and not IPs.
Routing can only occurs on IPs.
**** Load balancers
Load balancing is shifting a load between devices.  Can apply to servers, HDs,
CPUs, etc.  This provides:
- Reduced response time.
- Maximizes throughput.
- Allows better resource allocation.

Can be software or hardware.
**** Proxies
A device that acts on behalf of another.  All internal user interaction with
the Internet should be controlled through a proxy server.  Proxies should
auto-block known bad sites.  Caching should be enabled.
**** Web security gateway
A proxy server (proxies and caches) with web protection software built-in.
Can include a virus scanner and traffic monitors.  Can detect/prohibit certain
content, P2P connections, IM, tunneling, HTTP/HTML exploits, ActiveX, etc.
**** VPNs and VPN concentrators
VPN: A private network connection that occurs through a public network,
providing security over insecure environments.  Can connect LANs across the
Internet.  Requires special hardware/software.  VPNs usually use L2TP, IPSec,
PPTP.  Great for extra/intranets for remote offices.

Main concern is encryption.  PPTP: weak encryption, IPSec: higher security.

VPN concentrator: A hardware device used to create remote access VPNs.  It
creates encrypted tunnel sessions between hosts, most using two-factor
authentication.  Cisco concentrators include Scalable Encryption Processing
(SEP) for hardware encryption.
**** Intrusion detection systems (IDS)
Software that runs either on workstations or network devices to track network
activity.  Can evaluate system logs, monitor network activity, and disconnect
sessions in violation of security.  Some IDSs come with firewalls.  Recommend
combining with a firewall, as if firewall defenses are bypassed, the IDS
introduces reactive countermeasures.
**** Understanding intrusion detection systems
Intrusion detection (ID) is the process of monitoring events in a system or
network to detect an occurring intrusion.  An intrusion is any activity that
attempts to undermine or compromise the confidentiality, integrity, or
availability of resources.

Terms:
- Activity: An element of a data source of interest to the operator.
- Administrator: Person responsible for setting the security policy, deploys
  and configures the IDS, determines appropriate responses to attacks, and
  determines alarm levels, historical logging, and session-monitoring
  capabilities.
- Alert: A message from the analyzer indicating an event of interest, like
  with exceeded traffic thresholds.
- Analyzer: Component or process that analyzes data collected by the sensor.
- Data source: Raw info that the IDS uses, like audit files, system logs,
  network traffic, etc.
- Event: An occurrence in a data source that indicates suspicious activity.
  Events might trigger alerts.
- Manager: Component or process that operator uses to manage the IDS, like an
  IDS console.  Used for config changes.
- Notification: Process or method by which the manager makes the operator
  aware of the alert.
- Operator: Person responsible for the IDS.
- Sensor: IDS component that collects data from a data source and passes it to
  the analyzer.

IDSs use four main approaches:
- Behavior-Based-Detection IDS: Looks for deviations in behavior such as
  unusually-high traffic, policy violations, etc.
- Signature-Based-Detection IDS: Also called a misuse-detection IDS (MD-IDS).
  Primarily focused on detecting based on attack signatures (established
  methods of attack) and audit trails.  Uses a database of misuse and attack
  signatures.  E.g., if the MD-IDS knows what a TCP flood looks like, it can
  respond or report appropriately.
- Anomaly-Detection IDS (AD-IDS): Looks for anomalies, usually using a training
  program to learn normal operation and then spot deviations from that, or by
  being manually assigned baseline values.
- Heuristic IDS: Uses algorithms to analyze network traffic.  Require more
  fine tuning to prevent false positives.

In order for reporting to be effective, a baseline of typical network traffic
should be developed.

AD-IDSs use AI and expert systems.

IDSs detect and report unusual occurrences, but unlike firewalls, don't block.
**** IDS vs. IPS
An IPS is an IDS that reacts to detected intrusion, usually by blocking
communication from an offending IP.  The main problem here is false positives.
**** Working with a Network-based IDS (NIDS)
NIDS attaches to some point in a network, and reports on/monitors network
traffic.  Can be in front or behind a firewall.  A dual-security approach is
to place NIDSs in both locations.

In front of a firewall, the NIDS can monitor traffic going to the network and
give data on attacks the firewall is blocking.

NIDS can attach to a switch, hub, or tap.  Some switches and hubs have
monitoring ports which are effectively taps.  The advantage of a tap is the
IDS is the only device using it.

Port spanning/port mirroring: Copies all traffic from all ports to a single
port and disallows bidirectional traffic on that port.

Two types of responses: passive and active.
***** Implementing a passive response
Cannot react to an incident.

Passive strategies:
- Logging: Recording events and their circumstances.  Info then used to devise
  a counter to threats.
- Notification: Notify event-related info the appropriate personnel.  For
  manned IDSs, messages can appear on the manager's console.
- Shunning: Ignoring an attack.  Useful for attacks that are inapplicable
  (e.g. IIS attacks on Apache).
***** Implementing a active response
Involve taking action based on an attack/threat.  The goal is taking the
quickest possible reaction to reduce impact.  More costly than passive.

Active reactions:
- Terminating processes or sessions: E.g., in a TCP flood attack, the IDS can
  cause TCP to force resets (RST) to all current sessions.
- Network configuration changes: E.g., if an IP is an attack source, the IDS
  can instruct the border router or firewall to reject traffic from it.  If a
  socket or port is attacked, it can tell the firewall to block it for a
  length of time.
- Deception: Fools an attacker into thinking an attack is succeeding, while
  monitoring and possibly redirecting to a honeypot.
**** Working with a Host-based IDS (HIDS)
Software run on a host, usually a service or background process.  Examines
logs, events, and applications, but usually skips network traffic.  Popular on
servers already using encrypted channels.  Typically are passive.

Problems:
- If a system's compromised, logs are unreliable.
- Must be deployed to each system, adding administrative load.

Benefits:
- Can keep checksums on files to detect alteration.
- Can read memory.
**** Working with NIPSs
Network intrustion prevention systems focus on prevention.  Also detects,
therefor is a subset of NIDS.  Focuses on signature matches and takes action.

Can also be called intrusion detection and prevention systems (IDPS).
**** Logs to check in Linux
- /var/log/faillog: Failed authentication attempts.
- /var/log/lastlog: List of uses and when they logged in.
- /var/log/messages: Use grep to find login-related info.
- /var/log/wtmp: Used by last command.
**** Protocol analyzers
Protocol analyzers = packet sniffers.  Monitor data transmitted across a
network.  Software called an analyzer or sniffer.  Snort is an example of an
analyzer.
**** Spam filters
Catches unwanted email and filters it before delivery.  Uses rules, such as
sender IP lists, subject word scanning, etc.  Can also be used for outgoing
mail to catch infected internal computers.
**** UTM security appliances
Unified Threat Management (UTM), or Next Generation Firewall (NGFW), is an
all-in-one appliance.  Combines firewalls with things like intrusion
prevention, antivirus, filtering, etc.

Advantages include reduced learning curve, single vendor, and reduced
complexity.  Disadvantages include single point of failure and single vendor
dependence.
***** URL filters
Block websites based on URL.  IE8's SmartScreen Filter is a URL filter, which
blocks phishing and malware sites.
***** Content inspection
Looks at data coming in.  IE includes Content Advisor.
***** Malware inspection
Malware detection is useful, but stop it prior to being on systems is better.
***** Web application firewall (WAF) vs. network firewall
A WAF is a real-time appliance that applies a set of customizable rules to
block traffic to and from webservers and to try to block attacks.  Protects
against XSS, injection attacks, and forged HTTP requests.

Reacts to both known and suspected problems, making them superior to IPSs.
***** Application-aware devices
Has the ability to respond to traffic based on what's there.  These devices
combine SNMP and QoS to prioritize traffic.  Can be added to firewalls, IPSs,
IDSs, and proxies.
*** Review questions
1 C
2 A
3 D
4 B
5 B
6 A
7 A
8 D
9 C
10 A
11 B
12 A
13 D
14 C
15 A
16 B,C
17 C
18 A
19 D
20 A
*** Additional notes
Socket: A combination of an IP and port.
** Chapter 4: Access control, authentication, and authorization
Controlling access to a system, what resources are accessible, and ensuring
users are who they claim to be.
*** Understanding access control basics
Access control: Allowing authorized users to the system and keeping others out.
**** Identification vs. authentication
- Identification: Finding out who someone is.  Claiming an identity
- Authentication: A mechanism for verifying that identification.  Proving the
  identity.

Authentication (single or multifactor) systems are based on one or more of:
- Something you know: A password or PIN.
- Something you have: A smart card, token, or ID device.
- Something you are: Fingerprints or retinal scans (biometrics).
- Something you do: An action taken to complete authentication.
- Somewhere you are: Geolocation.  Often not used due to mobile computing.

Systems use similar methods for authentication between each other.

Out-of-band authentication: Getting public record info (such as credit
reports) and querying about info within.
**** Authentication (single factor) and authorization
Single-factor authentication (SFA): The most basic form.  Includes user/pass
combination.

Mutual authentication: When two or more parties authenticate each other.
Servers and clients can use this to establish a secure connection and employ
encryption.  Ensures the client isn't connecting to a rogue server.  Used when
data is critical, like finance.
**** Multifactor authentication
When two or more authentication methods are used, e.g. user/pass + smart card.
The factors can not be from the same category.  Password+PIN is still SFA.
**** Layered security and defense in depth
Synonymous terms, both meaning not relying on a single entity for protection.
**** Network access control
Operational security is part of a triad also including physical and management
security.  Operational security includes network access control (NAC),
authentication, and security topologies -- everything not included in design
or physical security.
**** Tokens
Security tokens are pieces of data that contain the rights and access
privileges of the token bearer as part of the token.  Similar to certs in that
they are used to identify and authenticate a user.  Some OSes create temp
tokens for every action or for user sessions.
**** Federations
A federation is a collection of related (e.g., for an industry association)
computer networks that agree on standards of operation, such as for security.
An example is an IM federation of providers that agree on communication
standards.

Federated identity: Linking a user's identity with their privileges in a manner
usable across business boundaries (e.g. MS Passport, Google Checkout).

Single sign-on: Having one password for all resources on a network.
**** Potential authentication and access problems
Transitive access and client-side attacks.
***** Transitive access
Involves transition.  A trusts B, B trusts C, then A may trust C.  Problems
here were solved with transitive trusts, which type relationships between
domains.

In AD, the default is two-way transitive trust.  Potentially troublesome due
to someone acquiring undesired access by joining a domain.
**** Authentication issues to consider
Consider tech-savviness of people affected by policies, though its better to
educate users than lower security.

Use identity proofing when issues arise between identification and
authentication, e.g. asking for mother's maiden name in event of lost
password.  The problem with these is that they are easily guessed/learned.
Difficult questions or biometrics are better.  Proofing shouldn't grant
immediate access, rather it should send access info to their email account.
**** Authentication protocols
- PAP (Password Authentication Protocol): Older system, not used.  Sends
  user/pass in plain text.
- SPAP (Shiva Password Authentication Protocol): Replaced PAP.  Encrypts
  user/pass.
- CHAP (Challenge Handshake Authentication Protocol): Stops man-in-the-middle
  attacks.  During initial auth, the client is asked to generate a random
  number/hash and send it.  The client is then periodically challenged to
  provide the number again.
- TOTP (Time-Based One-Time Password): An algorithm using a time-based factor
  to create unique passwords.
- HOTP (HMAC-Based One-Time Password): An algorithm using a Hash Message
  Authentication Code (HMAC) algorithm.
**** Account policy enforcement
Account Policy: Determines security parameters regarding who can/cannot access
the system.

The following subsections are account policy enforcement best practices.
***** Password length and complexity
Obtain balance between ease of remembering and cracking difficulty.  Minimums:
8 chars considered length, 1 non-alpha char.

Windows can be set to not require passwords by setting min length 0.  Win
8/7/Vista's Local Security Policy sets password complexity.  Physical access
to Windows machines can allow password retrieval.
***** Password expiration
The longer a password is used, the more likely it is to be broken.  90 days is
the standard, MS recommends 42.

Password history: Prevents users from using previous passwords, with
configurable history lengths.  History of 24 passwords is recommended.

Set minimum number of days that can exist between password changes to 2.
***** Password recovery
Only a hash is stored usually.  Admins should change it to something else then
have users log in and change it.
***** Password disablement and lockout
Accounts should be disabled for employees on temporary leave and permanently
for terminated employees.  For employees coming back as contractors, suspend
accounts so the relative identifiers (RIDs) are reused.

Locking an account usually occurs after repeated failed login attempts,
preventing password guessing:
- Account lockout duration: Accounts can become unlocked after a period of
  time.  Setting to 0 requires an admin to unlock.
- Account lockout threshold: Number of failed login attempts.
- Reset account lockout counter after: Duration between failed login attempts
  that count as a sequence of failures.
**** Users with multiple accounts/roles
Educate users with elevated privilege accounts to only use them when
necessary.  Establish policies to this effect.
**** Generic account prohibition
A generic account is any account shared by multiple users, including guest
accounts.  Problems include shared passwords and auditing issues.  These
should not be used.
**** Group-based and user-assigned privileges
Group privileges include groups and roles.
*** Understanding remote access connectivity
Remote authentication is any authentication done for a remote user.
**** Using the Point-to-Point Protocol
PPP supports multiple protocols and works with POTS, ISDN, T1, etc.  Doesn't
provide data security (no encryption), but does use CHAP auth.

PPP encapsulates traffic in Network Control Protocol (NCP) and authenticates
with Link Control Protocol (LCP).

PPP's insecurity makes it unsuitable for WAN connections.  For direct
connections, risk of phone line taps is small.  PPP connections through a
network should use an encrypted tunnel system.
**** Working with tunneling protocols
Tunneling protocols create tunnels between networks that can be more secure,
support added protocols, and provide virtual paths.  Sensitive data is
encapsulated in other packets and sent across a public network.
- PPTP: Supports encapsulation in a point-to-point environment.  Encapsulates
  and encrypts packets.  The channel is encrypted after negotiation occurs,
  though a sniffer can still capture the negotiation process to determine
  connection type and tunnel info.
- Layer 2 Forwarding (L2F): A Cisco-created method of creating tunnels, mainly
  for dial-up.  Similar to PPP and shouldn't be used on WANs.  Provides
  authentication, but no encryption.
- Layer 2 Tunneling Protocol (L2TP): A hybrid of L2F and PPTP.  Primarily a
  point-to-point protocol.  Doesn't provide data security/encryption, but
  IPSec can be used for this.
- Secure Shell (SSH): Uses encryption to establish a secure connection between
  two systems.
- Internet Protocol Security (IPSec): Used in conjunction with tunneling
  protocols.  Primarily for LAN-to-LAN connections, but also remote
  connections.  Provides secure authentication and encryption of data and
  headers.
**** Working with RADIUS
Remote Authentication Dial-in User Service (RADIUS), an IETF standard protocol,
allows authentication of remote and other network connections.  Implemented by
most major OSes.  Can be managed centrally.  Servers that allow access to a
network verify with a RADIUS server to perform authentication.

Use RADIUS when you want a single service to authenticate remote users.
Auditing and accounting can occur on the RADIUS server.

The main downside to RADIUS is that remote connectivity can go down if the
single servers malfunctions.  Some RADIUS systems allow multiple servers to
counter this.
**** TACACS/TACACS+/XTACACS
Terminal Access Controller Access-Control System (TACACS) is a
client/server-oriented protocol, similar to RADIUS.  Extended TACAS
(XTACACS) added logging/auditing.  TACACS+ is the current version, and allows
multiple credential methods, like Kerberos.

Both TACACS and RADIUS are centralized remote authentication services.
**** VLAN management
VLANs allow groups of users/systems, segmented on a network.  Hides segments
of networks, controls access, and controls data paths.

For security, VLANs allow grouping of users with similar data sensitivity
levels.
**** SAML
Security Assertion Markup Language (SAML) is an XML variant used for
authentication and authorization data.  Service providers uses SAML to prove
remote user identity.
*** Understanding authentication services
Authentication services: The implementation of the authentication
technology. Only need to know about LDAP, Kerberos, and SSO for exam.  LDAP
and Kerberos are protocols, SSO is a property of access control.
**** LDAP
Lightweight Directory Access Protocol (LDAP): A standardized directory access
protocol that allows queries to be made of directories (paired-down X.500-based
directories).  LDAP is used by Active Directory.  Uses port 389.

Secure LDAP (LDAPS): Encrypts all LDAP communication with SSL/TLS over
port 636.
**** Kerberos
An authentication protocol/method, allowing SSO.  Kerberos authentication uses
a key distribution center (KDC), which authenticates the principal (user,
program, or system) and provides it a ticket.  The ticket can then be used to
authenticate against other principals.  The only Kerberos weakness is the KDC
is a single point of failure.

Workflow:
- User authenticates to KDC and is given a ticket granting ticket (TGT), which
  lists privileges of the user.
- User requests a resource on the network from the KDC, presenting the TGT.
  The TGT sends the user a service ticket.
- The user's computer sends the service ticket to the server with the service.
  The server communicates with the TGT to validate the service ticket.
**** Single sign-on initiatives
SSO gives users access to all needed applications/systems needed with one
login.
- Kerberos: A single token allows any Kerberos-enabled application to accept a
  user as valid.  Requires each application to be able to do so.
- AD: The AD server retains all access rights for network users/groups.  Upon
  user login, AD issues a GUID to the user.  AD-supporting applications use
  the GUID to provide access control.

On decentralized networks, SSO passwords are stored on each server,
representing a security risk.  Enforcing password changes helps some.

SSO has some of its own security issues, but is the simplest way to deal with
users with multiple roles/accounts.
*** Understanding access control
Four primary methods of access control:
- Mandatory Access Control (MAC): All access predefined.
- Discretionary Access Control (DAC): Incorporates some flexibility.
- Role-Based Access Control (RBAC): Allows the user's role to dictate access
  capabilities.
- Rule-Based Access Control (RBAC): Limits the user to settings in
  preconfigured policies.

For high security, the standard is MAC or role-based.  For normal business and
educational environments, DAC is standard.
**** Mandatory Access Control (MAC)
Relatively inflexible, but most secure.  Users can't share info unless rights
to do so are established by administrators.  Requires much up-front thinking
about relationships.  Makes security breaches easier to investigate and
correct and information control easier.  Downside: Inflexible and requires
change over time.  If confidentiality is paramount, use MAC.
**** Discretionary Access Control (DAC)
More flexible, allowing the share of information dynamically between users.
Increases risk of unauthorized information disclosure and makes it harder to
ensure only appropriate access is issued.  Unix file permissions are an
example of DAC, with it's "other" group permissions.
**** Role-Based Access Control (RBAC)
Implement access by job function or responsibility.  Between the flexibility
of DAC and MAC.  Windows uses this.
**** Rule-Based Access Control (RBAC)
Uses preconfigured security policies, like deny lists and allow lists.  Can be
used in conjunction with role-based models to add flexibility.  Can implement
this with ACLs.
*** Implementing access controlling best practices
**** Least privilege
Users/systems are given the minimum privileges necessary to accomplish their
job.  Reduces the risk of privilege escalation.
**** Separation of duties
Differentiation between users and groups at varying levels, e.g., root/SA,
administrative accounts, normal users, restricted accounts.

Do the following at minimum:
- Separate the SA from regular accounts and never log in as SA for routine
  functions.
- Limit SA account to minimum group.
- Separate audit/logging from SA.
**** Time of day restrictions
Configuring when an account can have access.  Prevents attacks during the
majority of the time accounts aren't in use.
**** User access review
Access review is a process to determine whether a user's access level is still
appropriate.  Accounts for change in roles over time.

Continuous monitoring: Ongoing auditing of resources accessed by a user.
**** Smart cards
Contain memory storing permissions and access information.  Difficult to
counterfeit but easy to steal.  Passwords/PINs are required to activate most
smart cards.
***** Common Access Card (CAC)
Used for accessing DoD computers, signing email, and implementing PKI.
***** Personal Identification Verification (PIV) card
The same as CAC, but for federal employees and contractors.
**** Access control lists
Grants/denies devices access to network capabilities.
***** Implicit deny
If the proviso in question has not be explicitly granted, then access is
denied.  Can be based upon IP, destination, packet type, etc.
***** Firewall rules
Dictates what traffic can pass between the firewall and internal network.
Criteria:
- Block the connection.
- Allow the connection.
- Allow the connection if it's secured.

Can be applied inbound/outbound and to any network type, and should be audited
regularly.
**** Port security
Allows an administrator to configure switch ports so that only certain MAC
addresses can use the port.  A feature of smart switches, which also include
Dynamic ARP Inspection (DAI) to protect ports from ARP spoofing.

Areas to be familiar with:
- MAC limiting and filtering: Limit access to known MAC addresses.  Some
  routers also have this feature.  Not foolproof.
- 802.1X: Adding port authentication to MAC filtering increases security.
- Unused ports: Disable these.
**** Working with 802.1X
Defines port-based security for wireless network access control.  Adds
authentication via Extensible Authentication Protocol (EAP) over IEEE 802,
called EAP over LAN (EAPOL).  Allow APs and switches to not do authentication,
but rely on an authentication server.
**** Flood guards and loop protection
Flood guard: A protection feature built into some firewalls to vary the
tolerance for unanswered login attacks.  Lessens the likelihood/success of DoS
attacks.

Loop protection: Prevents broadcast loops.  Can disable broadcast forwarding
to protect against duplicate ARP requests (those having the same target
protocol address).  The Spanning Tree Protocol (STP) ensures loop-free bridged
ethernet LANs.  STP ensures only one active path exists between two stations.
**** Preventing network bridging
Network bridging: When a devices has multiple NICs where a user on one network
can jump to the other.  A problem with modern laptops with multiple adapters.
Preventable by shutting off a jack when bridging is detected.  Create profiles
where only one interface is allowed.  Disable unused connections and ICS.
**** Log analylsis
Collect and analyze logs.  Store them for future baseline comparisons.
**** Trusted OS (TOS)
Any OS meeting government requirements for security.  Common Criteria (CC) are
the most common set of standards for security.  CC outlines Evaluation
Assurance Levels (EALs):
- EAL 1: Correct operation, but threats viewed as not serious.
- EAL 2: 1 + requires product developers to use good design practices.
- EAL 3: Moderate levels of security.
- EAL 4: Positive security engineering.  The common benchmark for commercial
  systems.
- EAL 5: Security engineering implemented from an early design phase.
- EAL 6: Specialized security engineering.  Secure from penetration attackers.
- EAL 7: Extremely high levels of security.  Requires extensive independent
  testing and measurement of every component.
**** Secure router configuration
Musts:
- Change the default password.
- Walk through the advanced settings: Block ping requests, perform MAC
  filtering, etc.
- Keep the firmware upgraded: Router manufacturers issues patches for
  discovered problems.

Back up router configuration before changing anything.
*** Review questions
1 B
2 B
3 A
4 A
5 A
6 A
7 A
8 C
9 B
10 A
11 A
12 A
13 A
14 C
15 B
16 D
17 A
18 B
19 C
20 D
*** Additional notes
Tokens can be used to validate users per-session.
** Chapter 5: Protecting wireless networks
*** Working with wireless systems
802.11 standards.
**** IEEE 802.11x wireless protocols
The 802.11x family of protocols provide wireless communication using radio
frequency transmissions in the 2.4GHz and 5GHz spectrum.  Except for 802.11a,
these are compatible with each other.
- 802.11: 1 or 2Mbps, 2.4GHz.
- 802.11a: Up to 54Mbps, 5GHz.
- 802.11b: Up to 11Mbps (fallback to 5.5 and 1Mbps), 2.4 GHz.  Also called
  Wi-Fi or 802.11 high rate.
- 802.11g: Up to 54Mbps, 2.4 GHz.  Higher speeds but shares space other 2.4GHz
  devices, as is the case with 802.11b.
- 802.11i: Provides security enhancements with focus on authentication.  Often
  referenced as WPA2.
- 802.11n: Up to 600Mbps (though usually much slower).  Either 2.4GHz or
  5GHz.  Most popular now due to high speeds and less interference.  Multiple
  antennas can increase speed.
**** WEP/WAP/WPA/WPA2
Wired Equivalent Privacy (WEP) was a basic wireless security with Wireless
Application Protocol (WAP) providing network communications.  Has since been
replaced with WPA/WPA2.
***** Wired Equivalent Privacy (WEP)
A wireless protocol designed to provide privacy equivalent to a wired network
(though it doesn't, WPA2 does).  Vulnerable due to weakness in encryption
algorithm used (RC4).

IV attack: The initialization vector (IV) is 24-bit, meaning IVs are reused
with the same key. Examining the repeated result allows cracking the WEP secret
key.

Temporal Key Integrity Protocol (TKIP): Strengthens WEP encryption.  Places a
128-bit wrapper around the WEP encryption with a key based upon things like
the destination MAC address and packet serial number.  However, even TKIP has
been broken.
***** Wireless Application Protocol (WAP)
A data transmission standard widely adopted by manufacturers.  WAP functions
are equivalent to TCP/IP functions as the intent is the same, but for wireless.
WAP uses a subset of HTML called Wireless Markup Language (WML) for displays.
Scripting capabilities are provided by WMLScript.  WML and WMLScript allow
malicious code/viruses to be transmitted.

WAP systems communicate via a WAP gateway.  The gateway interfaces between WAP
and HTTP and TCP/IP.  If the WAP->Internet communication isn't encrypted,
packets can be sniffed.  The security concern converting between WAP and
SSL/TLS, exposing plain text, is called "gap in the WAP".  Fixed in WAP 2.0.

WAP can use WEP, WPA with TKIP, and WPA2.  WTLS is the security layer of WAP.
***** Wi-Fi Protected Access (WPA) and WPA2
Introduced in 802.11i, addressing security issues in WEP.  WPA implements some
of 802.11i to communicate with older wireless devices.  WPA uses RC4+TKIP.
WPA2 implements the full 802.11i and isn't compatible with older devices.

CCMP: WPA2 requires Counter Mode with Cipher Block Chaining Message
Authentication Code Protocol (CCMP).  CCMP users 128-bit AES encryption with a
48-bit IV.  The larger IV makes cracking difficult and minimizes replay
attacks.

Replay attack: Capturing portions of a session to play back later to convince
the host that it's still talking to the original connection.
**** Wireless Transport Layer Security (WTLS)
The security layer for WAP.  Provides authentication, encryption, and data
integrity on wireless.  Uses lower bandwidth/processing than TLS.  Moderately
secure.  WTLS is used to support devices that don't have much processing power.
*** Understanding wireless devices
Use RF signalling or cellular.

Levels of security existing in WAP:
- Anonymous authentication: Allows anyone to connect to the wireless portal.
- Server authentication: Requires authentication against the server.
- Two-way (client and server) authentication: Requires both ends to
  authenticate.

Some wireless devices can use certificates to verify authentication.

Technologies providing services between devices:
- Wireless Session Protocol (WSP): Manages the session information and
  connection between devices.
- Wireless Transaction Protocol (WTP): Provides TCP/UDP analogs to WAP.
- Wireless Transport Layer Security (WTLS): Security layer for WAP.
- Wireless Datagram Protocol (WDP): Provides common interface between devices.
**** Wireless access points
A low-power transmitter/receiver (transceiver), placed strategically for
wireless access, using 802.11x protocols.  Uses a portion of the RF (radio
frequency) spectrum called microwave.
***** Antenna placement
Generally, the greater the distance, the more the signal will attenuate.
Materials can reflect or absorb the signal.  Some include power level controls
to reduce amount of output.  A site survey with a strength meter can be done
while laying out a network.
***** Antenna types
- Omnidirectional antenna: Provide 360 patterns evenly.
- Directional antenna: Can cover a greater distance, but in a particular
  direction.
- Gain value: Rating metric for antenna.  Expressed in dBi.  Every 3 dB doubles
  the power output.
***** MAC filtering
Most APs include MAC filtering, but default it to off.  Synonymous with
"network lock".  Vulnerable to MAC spoofing.
***** Captive portals
Common on public hotspots.  Requires users to agree to conditions before using
the network/Internet.
***** Working with VPNs
VPNs can enhance security over wireless.
**** Extensible Authentication Protocol (EAP)
Provides a framework for authentication often used in wireless networks.
Among the types used with WPA/WPA2 are LEAP and PEAP.

Wi-Fi Protected Setup (WPS): A series of EAP messages allowing new hosts to
join the network and use WPA/WPA2.  Common in homes and small offices.
Requires users to do something to complete the enrollment process, like enter a
PIN, push a router button, or close distance for NFC.  WPS attacks are common
though, e.g., using brute force PIN attacks.  Recommend disable WPS.

Near-field communication (NFC): Requires the user to bring the client close to
the AP for verification (through RFID or Wi-Fi), validating it is present.
***** Lightweight Extensible Authentication Protocol (LEAP)
An extension to EAP by Cisco, being phased out.  Lacks Windows support.
Requires mutual authentication.  Susceptible to dictionary attacks.  Not
recommended.
***** Protected Extensible Authentication Protocol (PEAP)
The current standard EAP.  Secure through establishing an encrypted channel
between server/client.
*** Wireless vulnerabilities to know
Vulnerable to all the wired attacks, plus additional wireless ones.  Easy to
intercept.  Network names are regularly broadcast via SSID broadcast.

Cloaking: SSID broadcasts can be disabled.  Requires prior knowledge of the
APs existence.  A very weak form of security.

Site surveys: While used for antenna placement, can also be done by attackers
to find systems, protocols, etc.

Jamming: Intentional interference of the signal.

War driving: Driving around with a laptop looking for APs with a NIC set to
promiscuous mode.

War chalking: Once a network weakness is discovered, writing information about
that in chalk outside the premises.

Rogue access points: Any unauthorized AP added to the network.  May not
implement proper security.

Evil twin attack: A rogue wireless AP poses as a legitimate wireless service
provider to intercept information users transmit.

Never assume wireless communication is secure.  Always use data security.  Set
APs to not broadcast. Use WPA2 and higher encryption levels.

Bluetooth is often used to create personal area networks (PANs or WPANs).
Change the default PIN on Bluetooth devices.  Set Bluetooth devices
non-discoverable.  Vulnerablities:
- Bluejacking: Sending unsolicited messages (like spam) over Bluetooth
  connections.
- Bluesnarfing: Gaining unauthorized access through a Bluetooth connection.
*** Review questions
1 C
2 A
3 C
4 D
5 B
6 C
7 A
8 A
9 C
10 A
11 B
12 B
13 C
14 A
15 A
16 C
17 D
18 B
19 A
20 D
** Chapter 6: Securing the cloud
*** Working with cloud computing
Service models: SaaS, PaaS, IaaS.  Delivery models: private, public, community,
hybrid.

Cloud bursting: When your servers become too busy, you offload traffic to a
cloud provider.  A form of load balancing/prioritizing, employing Quality of
Service (QoS) protocols.
**** Software as a Service (SaaS)
Provides applications running on clouds.  Used via thin client interfaces, like
the web or a program.  The consumer doesn't control the underlying
infrastructure.

Consumer: User.
Provider: Application, middleware, OS, hardware, network, facility.

Keywords: Consumer "uses", but doesn't "manage or control".
**** Platform as a Service (PaaS)
Consumer can deploy consumer-created/acquired applications on the cloud, using
languages, libs, services, and tools provided by provider.

Consumer: User, application.
Provider: Middleware, OS, hardware, network, facility.

Keywords: Consumer "deploys", but doesn't "manage or control".
**** Infrastructure as a Service (IaaS)
Consumer able to deploy and run arbitrary software, OSes, and applications.

Consumer: User, application, middleware, OS.
Provider: Hardware, network, facility.

Keywords: Consumer "provisions" and "deploys and runs", but doesn't "manage or
control".
**** Private cloud
Cloud is for exclusive use by an organization.  Organization acts as both
provider and consumer.  Doesn't need to be online.
**** Public cloud
Cloud open for use by general public.  Cloud providers own public clouds.
**** Community cloud
Cloud for use by specific community or organizations with shared concerns.  May
be owned/operated by some of the organizations or external.
**** Hybrid cloud
Composition of two or more of public, private, community.  Most commonly a
combination of private and public.
*** Working with virtualization
Hypervisor: The software/hardware combination making virtualization possible.
Two methods of implementation exist:
- Type I hypervisor (bare metal): Independent of the OS and boots before the
  OS.
- Type II hypervisor (hosted): Dependent upon the OS and cannot boot until the
  OS is running.
**** Snapshots
Allow taking of an image of the system at a point in time.  The VM can then be
reverted to a saved state.  Snapshots contain copies of the VM settings
(hardware configuration), information on all virtual disks, and memory state of
the VM.  Can be used for cloning.
**** Patch compatibility
Verify patch compatibility with VMs before updating them.  Verify sources of
patches.
**** Host availability/elasticity
Availability: The goal is five 9s, the industry standard.

Elasticity: Scaling up/down capabilities, sometimes automatically.
**** Security Control Testing (SCT)
Includes interviews, examinations, and testing of systems to look for
weaknesses.  Also includes contract reviews of SLAs and history of prior
breaches.  A subset of penetration testing.
**** Sandboxing
Running apps in restricted memory areas.  Limits the possibility of an app
crash.  Removes the possibility of another customer's implementation exposes a
"server hop" path.
*** Security and the cloud
Security issues regarding clouds:
- Multitenancy: Workloads from different clients can be on the same system and
  a flaw in implementation could compromise security.  Other customer security
  issues could affect your data.  Protect data from other cloud customers.
  Data segregation can help reduce some risks.
- Laws and regulations: Responsibility of security remains with consumer.

Software/services not necessary for the implementation should be
removed/disabled, patches/firmware kept current, and logs monitored.  Cloud
data storage should involve encryption.  VPN routing/forwarding can help.
Backups should be done regularly.  Prioritize access control.
**** Cloud storage
SLA needs to spell out how provider will handle data protection (sandboxing,
etc.), redundancy, disaster recovery, etc.
*** Review questions
1 C
2 A
3 B
4 B
5 A
6 C
7 D
8 A
9 D
10 B
11 D
12 A
13 C
14 C
15 B
16 A
17 B
18 B
19 B
20 C
*** Additional notes
XaaS: Anything as a Service.  Combination of multiple service models.
** Chapter 7: Host, data, and application security
*** Application hardening
**** Databases and technologies
RDBMSes, SQL.  To improve performance and improve security, companies have
implemented a tiered systems (ones that include DBs) model:
- One-tier model (single-tier environment): DB and application exist on a
  single system.  Common on desktops running a standalone DB.  Early Unix
  systems worked this way.
- Two-tier model: Client workstation/system runs the application,
  communicating with a DB running elsewhere.
- Three-tier model: Isolates the end user by introducing a middle-tier server.
  The middle tier controls access to the DB and provides additional security.
***** NoSQL
Used where scaling is important.  Uses "horizontal" scaling model (adding more
servers), vs. RDBMs' "vertical" scaling (beefing up server).
***** Big data
Defined here as that which cannot normally fit on a single server, but is
instead stored on a SAN.  Size causes it to become difficult to use/manage.
***** Storage Area Network (SAN)
A separate network setup to appear as a server storing data to the
organization.  Abstracts storage/device complexity.  SANs usually have
redundant servers, connected via fibre or iSCSI.

SAN security: Similar to any server, except includes network isolation.  Needs
a firewall, maybe an IDS, user access control, etc.
**** Fuzzing
Providing unexpected values as application input, in order to make it crash.
A common method is to flood the input with a stream of random bits.

Prevent this by validating all input and ensuring it is of an expected type.
**** Secure coding
The only prevention for attacks like XSS, SQL injection, and buffer overflows.
***** OWASP
The Open Web Application Security Project (OWASP) is a group that forms secure
coding practices for web, mobile, and client applications, along with back-end
design.

Recommends all data input be validated before processing via:
- Client-side validation: Accomplished within the client-side web page.
- Server-side validation: Validates the data after the server's received it.
  Normally done in conjunction with client-side validation.
***** CERT secure coding standards
Covers some of the same stuff as OWASP guidelines, but also includes
language-specific guidelines.  Addresses exception handling.

Exception handling: How errors are handled are critical to security.  Don't
present detailed error information to end users.  Log it instead.
**** Application configuration baselining
Baselining compares performance to a metric.  Baseline key applications prior
to a major configuration change.
**** Operating system patch management
The three patch levels for OSes, applied to urgency:
- Hotfix: An immediate and urgent patch.  Represent serious security issues
  and not optional.
- Patch: Non-urgent fix, providing functionality.
- Service pack: Should always be applied, but tested first to ensure no
  problems are caused by it.
***** Application patch management
Same rules above apply to applications.  Routinely scan for available patches.
Many attacks target client systems do to poorer patch management.
*** Host security
A network is only as strong as its weakest host.
**** Permissions
Apply least privileges.

Microsoft's 5 file permissions:
- Full control: +rwx, and assign permissions to other users.
- Modify: +rw, with delete.
- Read and execute: +rx.
- Read: +r.
- Write: +w.

Folders have the same, plus one:
- List folder contents: Allows user to see contents but not read files.
**** Access Control Lists (ACLs)
A list of who can access what resource and at what level.  Can be part of an OS
or application.  Can also be a physical list for access to a room or building.

Related to ACLs:
- White list: A list of items allowed.
- Black list: A list of things prohibited.  Includes black lists of websites.
**** Antimalware
Minimum actions to take:
- Install antivirus software: Install and keep definitions current on all
  servers/workstations.  Monitor incoming files and scan regularly.
- Install antispam filters: Keeps spam away from users.
- Install antispyware software: Standalone or combined with AV.  Scan
  regularly.  Watch for tracking cookies.
- Use pop-up blockers: Annoying and a security threat.
- Use host-based firewalls: A line of defense against attackers/malware.
  Good, but still need a Web Application Firewall (WAF) to check every request
  between client and a web server.
- Use host-based IDSs: SNORT is an example.
**** Host software baselining
A security baseline (or performance baseline) defines the level of security
implemented and maintained.  Low is no security, high doesn't allow users to
make any changes.  Most are somewhere between.
**** Hardening web servers
Web servers represent the greatest reach for attackers when compromised.
Every service a web server provides could be an attack vector.  Ensure users
have minimal permissions.  If anonymous accounts are used, ensure they can
only view pages.

Filters allow limiting traffic allowed through.

Control access to executable scripts, like CGI, PHP, etc.  It's possible a user
can break out of a script while at elevated level (while the script is
running).  Thoroughly test, debug, and approve these scripts.

All web servers create an OS account when services are installed.
**** Hardening email servers
Put an active virus scanner on email servers.  Also scan Exchange mail stores
with specific AV scanners (normal ones can't open MS's open files).
**** Hardening FTP servers
FTP isn't intended for high-security applications due to inherent weaknesses.
Create FTP file areas on separate drives.  Use VPNs or SSH for FTP-like
activities instead.  FTP sends user/pass encrypted over the network.

Give users a separate user/pass for FTP access, preventing normal accounts
from getting compromised.  Scan all files stored on an FTP server.  Always
disable the anonymous account.

Like with web servers, an FTP server creates an account on service install.

Even better, use a secure alternative, like SFTP.
**** Hardening DNS servers
Types of DNS attacks:
- Domain Name Service Denial-of-Service attacks (DNS DoS): Disrupts operations
  of the DNS server, making it unusable.  Minimize impact by ensuring server
  software is up to date and use two-factor authentication with the registrar.
- Network footprinting: The act of gathering data about a network to find ways
  someone might intrude.  DNS servers store lots of network information.
  Using nslookup, an attacker can learn about your network configuration.  DNS
  entries include names and information on some of the key servers in the
  network (email, web, etc.).  Keep information stored on external DNS
  servers to a minimum, or use 2 DNS servers (one external, one internal).
- Compromising record integrity: In DNS lookup systems involving a
  primary/secondary, changes in one will propagate to the other.  An attacker
  could redirect traffic to unintended destinations.  Ensure DNS servers
  require authentication before updates are made.

Domain Name System Security Extensions (DNSSE): Created to add security to and
maintain backward compatibility with DNS, once exploits in DNS were discovered.
DNSSE checks digital signatures and protects information with digitally signed
records.  Protects against forged DNS data.
**** Hardening DHCP servers
DHCP can be provided by routers, switches, or servers, and leases an IP address
to a workstation for a specified time along with other network configuration
options.  Only one DHCP server can be active on a given network/segment (lest
multiple DHCP servers clash), though redundant, non-overlapping servers are
possible.  NAT servers can provide DHCP service.  DHCP usage should be limited
to workstations.  Watch for rogue APs that act as DHCP servers.
*** Protecting data through fault tolerance
**** Backups
The most basic level of fault tolerance.

Backup types:
- Full: All changes to data are archived.
- Differential: All changes since last full backup are archived.  Balances
  efficiency and ease of backup use.
- Incremental: All changes since last backup of any type are archived.  Most
  efficient, but more work to use backup.

Hierarchical storage management (HSM): Provides continuous online backup on
optical/tape.  Appears as an infinite disk to the system.  Closest to a
real-time backup.
**** RAID
Same as RAID information from Chapter 1, with some additions:
- RAID 0: Disk striping.
- RAID 1: Disk mirroring/duplexing.
- RAID 3/4: Striping with one dedicated parity disk.  Can lose 1 disk.
- RAID 5: Striping with distributed parity.  Can lose 1 disk.
- RAID 6: Striping with 2 parity disks.  4 or more disks.  Can lose 2 disks.
- RAID 1+0 (or 10): A mirrored set (1), striped (0).  A stripe mirrors.
- RAID 0+1: The reverse of 10.  A mirror of stripes.

Data at rest: Data not currently being transmitted.  Includes backups and RAID.

Data in transit: Active data.  Data being sent over some network connection.
**** Clustering and load balancing
Clustering: Anytime multiple computers work/act together as a single server.
Use parallel processing (improving performance and availability) and add
redundancy (but adding cost).

Load balancing: Splitting the workload across multiple servers.  A mirror site
is when server farm geo-locations are split.  This can add geographic
redundancy.
*** Application security
- Key management: PKI services are popular and expanding to mobile.
- Credential management: Credentials allow user/pass to be stored in one
  location, then used to access websites/computers.
- Authentication: More pressing with mobile.  Don't configure applications to
  auto-login.
- Geo-tagging: Allow GPS coordinates to embed in files like images.  Can
  reveal the location of facilities/resources unintentionally.
- Encryption: Company policies should address this.
- Application white-listing: Identify applications approved/accepted on the
  network.
- Transitive trust/authentication: Problems possible anytime one entity accepts
  a user without requiring additional authentication on behalf of another
  entity.  More authentication checks generally equals more security.
*** Best practices for security
**** Data Loss Prevention (DLP)
DLP systems monitor the contents of systems and ensure key content is not
deleted/removed.  Also monitor who is using the data, look for unauthorized
access, and who is transmitting data.  Examples include MyDLP, RSA, and
Tripwire.
**** Hardware-based encryption devices
Some BIOS configurations allow enabling Trusted Platform Modules (TPMs), which
can assist with hash key generation.  The TPM is a chip that can store some
cryptographic keys, passwords, or certificates.  Used to protect smart phones
and some PCs.  Whole disk encryption via BitLocker can use a TPM.
*** Review questions
1 A
2 B
3 B
4 A
5 B
6 A
7 C
8 A
9 C
10 D
11 B
12 C
13 D
14 B
15 A
16 C
17 D
18 C
19 D
20 B
*** Additional notes
- Don't share root directories of disks.
- Hotfixing also implies doing so on a running system.
- Patching also implies manual updating.
** Chapter 8: Cryptography
Cryptography: The study of cryptographic algorithms.  The science of altering
information so it cannot be decoded without a key, transforming it with
encryption and transformation.

Cryptanalysis: The study of how to break cryptographic algorithms.
*** An overview of cryptography
**** Historical cryptography
Caesar cipher, ROT13, and the Vigenre cipher.

Cipher: A method used to encode characters to hide their value.

Ciphering: The process of using a cipher to encode a message.  The two
ciphering methods are substitution and transposition.
***** Substitution ciphers
Changing one character into another.

Caesar cipher: Shifting all letters a certain number of spaces in an alphabet.

ROT13: Letters shifted 13 to the right.  To decrypt quickly, write two columns
of letters, the first is the first 13, the second the second 13.  Thus, A
lines up with N, and so on.
***** Multi-alphabet substitution
Having a pattern of character shifts, e.g. 1 char shifts 3 to the right, the
2nd 2 chars, the 3rd 1 char, then repeating.

Vigenre cipher: Used a keyword to look up the cipher text in a table.  Replace
the original text with the keyword (repeated), then use the keyword letter at
each index to encode the plaintext letter.  The keyword letter acts as the row
designator and designates the shift.  Do the reverse to decrypt.
***** Transposition ciphers
Transposing or scrambling the letters in a certain manner.  Typically, a
message is broken into equal size blocks, then each block is scrambled.
***** The Enigma Machine
A typewriter that implemented a multi-alphabet substitution cipher.  Each key
used a different substitution alphabet.
***** Steganography
Hiding a message in a medium such as an image, audio, or other file.  Often
done by storing information in the least significant bit (LSB).  Sometimes
used for electronic watermarking to prove copyright infringement.
***** Transport encryption
Encryption modes:
- Tunneling: The payload and message headers are encrypted.
- Transport: Encrypts only the payload.
*** Modern cryptography
Three areas: Symmetric cryptography, asymmetric cryptography, hashing
algorithms.
**** Working with symmetric algorithms
Symmetric algorithms require both ends to have the same secret key and
processing algorithms.  The symmetric key is also called a secret key or
private key.

Always faster than asymmetric cryptography and can use smaller key sizes for
the same level of security.

Symmetric methods use a block or stream cipher.  Block cipher algorithms work
on chunks of data.  Stream ciphers encrypt one bit or byte at a time.

Common symmetric standards:
- Data Encryption Standard (DES): Used since the mid-1970s as the primary
  standard in government and industry until replaced by AES.  Based on a 56-bit
  key.
- Triple-DES (3DES): A still-used upgrade to DES, though AES is the preferred
  choice in government.  Increases the key length to 168 bits (3x 56-bit keys).
- Advanced Encryption Standard (AES): The current standard using the Rijndael
  algorithm.  Used extensively by government.  Supports key sizes of 128, 192,
  and 256 bits, with 128-bit the default.
- AES256: Uses 256 bits instead of 128.  Qualified for use with US Top Secret.
- CAST: Used in some MS and IBM products.  Uses a 40 to 128-bit key.  Very
  fast and efficient.  CAST-128 and CAST-256 also exist.
- Ron's Cipher (RC): An encryption standard by RCA laboratories.  Levels are
  RC4, RC5, and RC6.  RC5 uses a key size up to 2048 bits and is considered a
  strong system.  RC4 is used in wireless, WEP/WPA encryption, and SSL/TLS.
  It's a streaming cipher using 40 to 2048 bit keys.  Used for obfuscating
  BitTorrent from service providers.
- Blowfish and Twofish: Blowfish is a 64-bit block cipher and super fast.  It's
  a symmetric block cipher that can use 32 to 448-bit keys.  Twofish is similar
  and works with with 128-bit blocks and has a complex key schedule.
- Indernational Data Encryption Algorithm (IDEA): Uses a 128-bit key.  Similar
  is capability and speed to DES, but more secure.  Used in PGP.
- One-time pads: The only truly completely secure cryptographic
  implementations.  The key is long and has no pattern in the key application
  an attacker could use.  Used once and discarded.
***** Key exchange
Critical in symmetric cryptography.  Two approaches:
- In-band key exchange: Key is exchanged in the same communications channel
  that is going to be encrypted.  Used by IPSec.
- Out-of-band key exchange: A different channel is used for keys.

Forward secrecy: A property of key exchange systems, meaning that when one key
is compromised, subsequent keys won't be.

Perfect forward security: When forward secrecy is unbreakable.  Ephemeral keys
is a common example.
**** Working with asymmetric algorithms
Asymmetric algorithms use two keys (public and private) to encrypt and protect
data.  Based on number theory.  One key encrypts, the other decrypts.  If a
public key encrypts a message, then only the private key can decrypt it.

Public-key cryptography (PKC): Two-key systems.  PKI is an infrastructure that
uses PKC.

Four popular asymmetric systems:
- RSA: An early public-key cryptosystem that uses large integers as the
  basis for the process.  Works with both encryption and digital signatures.
  Used in SSL.
- Diffie-Hellman key exchange: Algorithm used to send keys across public
  networks.  Not used to encrypt/decrypt, only for creation of a symmetric key
  between two parties.  An ephemeral key can also be used, called Ephemeral
  Diffie-Hellman (DHE).
- Elliptic Curve Cryptography (ECC): Similar functionality to RSA, but uses
  smaller key sizes and gets the same security.  Based on the discrete
  logarithmic problem of points on a curve, combined with a point at
  infinity.  Should be common in cellular devices in the future.  Includes:
  - Elliptic Curve Diffie-Hellman (ECC-DH)
  - Elliptic Curve Digital Signature Algorithm (ECC-DSA)
- ElGamal: An asymmetric algorithm using an ephemeral key (one that exists only
  for that session).  Several variations exist, including Elliptic Curve
  ElGamal.

An abbreviated version of the above list:
- Diffie-Hellman: Key agreement.
- ElGamal: Transmitting digital signatures and key exchanges.
- Elliptic Curve (ECC): Alternative to RSA using less computing power.
- RSA: Most common.  Used for encryption and digital signatures.
**** What cryptography should you use?
Kerckhoff's principle: Security of an algorithm should depend on the secrecy
of the key and not the secrecy of the algorithm.

Only use public, proved cryptography technology.
**** Hashing algorithms
Cryptographic hash functions must have 3 characteristics:
- Must be one-way: Not reversible.  Cannot unhash that which has been hashed.
- Variable-length input produces fixed-length output: Hash size is always the
  same, regardless of input length.
- Algorithm must have few or no collisions: Hashing two different inputs does
  not the give the same output.

These are used to allow one to easily verify that some input data matches a
stored hash value, but makes it impossible to reconstruct the data from the
hash alone.

Hashing algorithms to be familiar with:
- Secure Hash Algorithm (SHA): Designed to ensure the integrity of messages.  A
  one-way hash that can be used with an encryption protocol. Produces a 160-bit
  hash value.  SHA-2 has several sizes: 224, 256, 334, and 512-bit.  SHA-2 is
  most widely used.  SHA-3 is now standard, though SHA-2 has no known issues
  and SHA-3 still ins't recommended.
- Message Digest Algorithm (MD): Also creates a hash value and is a one-way
  hash.  Also validates message integrity.  Most common are MD5, MD4, and
  MD2.  MD4 used to be used by NTLM.  MD5 creates a 128-bit hash, but the
  algorithm is more complex and offers better security.  Weakness: no strong
  collision resistance.  SHA is preferred.
- RIPEMD: The RACE Integrity Primitives Evaluation Message Digest algorithm.
  Originally based on MD4, but replaced by RIPEMD-160, which uses 160 bits.
  RIPEMD-256 and RIPEMD-320 also exist.
- GOST: A Soviet symmetric cipher modified to now be a hash function.  256-bit
  output.
- LANMAN: An authentication protocol for pre-NT MS OSes.  Used LM Hash and 2
  DES keys.  Replaced by NTLM with Windows NT.  Used for authentication, not a
  hashing algorithm.
- NT LAN Manager (NTLM): Uses MD4/5.  v1 and v2 exist.  Still in use despite
  MS preferring Kerberos for authentication.  Used for authentication, not a
  hashing algorithm.
**** Rainbow tables and salt
Rainbow table: All possible hashes computed in advance, using a hashing
algorithm.  If you know the hash, you can look up the text producing it.  A
significant issue for passwords.  OphCrack uses these.

Salt: The addition of bits at key locations, either before or after the hash.
E.g., before a password is hashed, bits are added to it, then the hash is
performed.  Lookups here won't return the correct original text.
**** Key stretching
Taking a possibly weak key and making it stronger, usually be making it longer
and less susceptible to brute force attacks.  Two methods:
- PBKDF2: Password-Based Key Derivation Function 2.  Applies some function
  (like a hash or HMAC) to the password/passphrase along with salt to produce
  a derived key.
- bcrypt: Used with passwords.  Uses a derivation of Blowfish, converted to
  be a hashing algorithm, to hash and add salt to it.
**** Understanding quantum cryptography
Quantum Key Exchange (QKE): Mentioned, but not covered here.
**** Cryptanalysis methods
Common code-breaking techniques:
- Frequency analysis: Looking at blocks of an encrypted message to determine if
  any common patterns exist.  With enough patterns, an cryptanalyst may be able
  to deduce the method used to encrypt.  Does not work on modern algorithms.
- Chosen plaintext: Obtain ciphertexts of plaintexts of the cryptanalyst's
  choosing.  May allow attacker to derive the key used and then decrypt other
  messages encrypted with the same key.  Difficult, but not impossible.
- Related key attack: Similar to chosen plaintext, but the attacker can obtain
  the ciphertexts encrypted under two different keys.  Useful if you can
  obtain the plaintext and matching ciphertext.
- Brute-force attacks: Applies every possible combination of characters that
  could be the key.  Longer keys take longer to find.
- Exploiting human error: A human might send a plaintext or part of it in the
  clear.  Or, a key may be exposed, showing what they consist of.
**** Wi-Fi encryption
All clients and the AP use a shared key, using symmetric encryption.  WPA uses
RC4+TKIP.  WPA2 uses CCMP, which uses 128-bit AES.  CCMP XORs block n with
block n-1, ensuring block ciphertexts don't match even if the plaintext does.
*** Using cryptographic services
Cryptographic system: a system, method, or process that provides
encryption/decryption.  Includes hardware, software, and manual processes.
**** Confidentiality and strength
Confidentiality: preventing unauthorized disclosure of information.

Strength: The effectiveness of a cryptographic system in preventing
unauthorized decryption.  Refers to the algorithm's work factor.

Work factor: A estimate of the amount of time/effort needed to break the
system.

E.g. Sybase FIPS compliance requires encryption, hash, and key exchange
algorithms of AES, 3DES, DES, and SHA1.
**** Integrity
Integrity: Providing assurance the message wasn't modified during transmission.
Accomplished by adding redundant data used during the decryption process.

Message Authentication Code (MAC): A common method of integrity verification.
The MAC is derived from a message and shared (symmetric) secret key.  The MAC
is then encrypted with the message, adding another layer of integrity checking.

Hash-Based Message Authentication Code (HMAC): Uses a hashing algorithm along
with a symmetric key.
**** Digital signatures
Validates the integrity of a message and sender.  The message is encryption
and the digital signature is added to the message.

Workflow:
- Message created and sender users his private key to create a digital
  signature.
- Message sent.
- Receiver uses the public key attached to the message to validate the digital
  signature.  If it matches, then the message is authentic.
- Receiver uses the public key to decrypt the message.  Most digital signature
  implementations also use a hash to verify integrity.
- The receiver compares the signature area (called the message digest) in the
  message with the calculated value.  If the values match, integrity is
  confirmed.

This process provides message integrity, nonrepudiation, and authentication.
**** Authentication
The process of verifying the sender is who they say they are.  Often done with
digital signatures or secret words.
**** Nonrepudiation
Prevents one party from denying actions they carried out.  Public keys can get
a message received but no way exists the sender is who they say they are.  This
is provided by third-party organizations called Certificate Authorities (CAs).
These manage public keys and issue certificates verifying the validity of a
sender's message.
**** Key features
Key escrow: Addresses the possibility that a third party may need access to
keys.  The keys needed to encrypt/decrypt data are held in an escrow account,
and made available upon request.  The third party is usually the government,
like for law enforcement investigations.

Key recovery agent: An entity able to recover a key, key components, or
plaintext messsages.  Typically used to access information encrypted with older
keys.

Key registration: The process of providing certificates to users. A
registration authority (RA) usually does this to lift load from a CA.

Certificate Revocation List (CRL): When a key is expired, canceled, or
replaced, a CRL can be checked to see if a key is still valid.  A list of
certificates that a specific CA states should no longer be used.  Now being
replaced by a real-time protocol called Online Certificate Status Protocol
(OCSP).

Trust models: Exist in PKI implementations.  Four main types: bridge,
hierarchical, hybrid, and mesh.
*** Understanding cryptography standards and protocols
**** The origins of encryption standards
**** The role of government agencies
- National Security Agency
- National Security Agency/Central Security Service (NSA/CSS): DoD support.
- National Institute of Standards and Technology (NIST): General purpose
  government encryption standards.  Also used by private sector.
**** Industry associations and the development process
RFC: Categorized as a standard, best practice, informational, experimental, or
historic.
- American Bankers Association (ABA): Finance
- Internet Engineering Task Force (IETF): Internet, but also security.
- Internet Society (ISOC): Internet experts, oversees IETF.
- World Wide Web Consortium (W3C): Encryption in XML.
- International Telecommunications Union (ITU): Telecommunications and radio.
- Institute of Electrical and Electronics Engineers (IEEE): PKC, wireless, and
  networking protocol standards.
**** Public-Key Infrastructure X.509/Public-Key Cryptography Standards
Public-Key Infrastructure X.509 (PKIX): A working group formed by the IETF.
Develops standards/models for the PKI environment.  Responsible for the X.509
standard.

Public-Key Cryptography Standards (PKCS): A set of voluntary standards by RSA
and industry corporations.
**** X.509
The standard defining the certificate formats and fields for public keys.
Also defines procedures to distribute public keys.  v2 used as primary method
for issuing CRL certificates.

v3 (current version) comes in two types:
- End-entity certificate: Issues by a CA to an end entity (system that just
  uses certificates).
- CA certificate: Issued by one CA to another CA, who can then issue to an end
  entity.

X.509 certificates have the following:
- Signature (the primary purpose for the certificate)
- Version
- Serial number
- Signature algorithm ID
- Issuer ID
- Validity period
- Subject name
- Subject public-key information
- Issuer unique identifier (v2 and v3 only)
- Subject unique identifier (v2 and v3 only)
- Extensions (v3 only)
**** SSL and TLS
Establishes a secure communication connection between two TCP machines.  Uses
the handshake method of establishing a session, where the number of steps (4
to 9) depend on whether combined and/or mutual authentication is included.

Cipher suites: An early step is to select a cipher suite to use.  A cipher
suite is a combination of methods, such as authentication, encryption, and
message authentication code (MAC) algorithms used together.  TLS uses cipher
suites.

Clients need to support the level of encryption applied.  Modern browsers
support 128-bit encrypted sessions/certificates.
**** Certificate Management Protocols (CMP)
CMP: A messaging protocol used between PKI entities.

XML Key Management Specification (XKMS): Allows XML-based programs access to
PKI services.  Built on top of CMP.
**** Secure Multipurpose Internet Mail Extensions (S/MIME)
A standard used for encrypting email, containing signature data.  MIME is the
standard for email messages, and S/MIME is the secure version of it.  Provides
encryption, integrity, and authentication when used with PKI.  Uses asymmetric
encryption algorithms and digital certificates.
**** Secure Eletronic Transaction (SET)
Provides encryption for credit card numbers transmitted over the Internet.
Developed by Visa and Mastercard.  Suitable for transmitting small amounts of
data.  Works with an electronic wallet set up in advance of the transaction.
**** Secure Shell (SSH)
Tunneling protocol originally used on Unix and interactive terminal sessions.
Similar handshake process to SSL.  Operates in two phases:
- A secure channel to negotiate the channel connection.
- A secure channel used to establish communications.
**** Pretty Good Privacy (PGP)
A freeware email encryption system.  Uses both symmetric and asymmetric
systems.  Messages are encrypted with the public key and a session key (a
one-use random number).  When received, the private key is used to ascertain
the session key.  The session key and private key are then used to decrypt the
message.

GPG is an alternative to PGP and is interoperable with it.
**** HTTP Secure (HTTPS)
Uses SSL to secure the channel between client and server.
**** Secure HTTP (S-HTTP)
HTTP with message security.  HTTPS creates a secure channel, S-HTTP creates a
secure message.  Provides data integrity and authentication.  Seldom used.
Uses port 80.
**** IP Security (IPSec)
Provides authentication and encryption.  The two protocols used by IPSec are
Authentication Header (AH) and Encapsulation Security Payload (ESP).  Both can
operate in transport or tunnel mode.
**** Tunneling protocols
Can create tunnels between networks more secure, support additional protocols,
and provide virtual paths.
- Point-to-Point Tunneling Protocol (PPTP): PPTP encapsulates and encryptes PPP
  packets.  A major weakness is negotiation done in the clear.
- Layer 2 Forwarding (L2F): Cisco protocol for creating tunnels, mainly for
  dial-up.  Similar to PPP, and shouldn't be used over WANs.  Provides
  authentication but no encryption.
- Layer 2 Tunneling Protocol (L2TP): Combination of PPTP and L2F.  Supports
  multiple network protocols, can bridge systems, but doesn't provide data
  security.  IPSec can be used to do so.
**** Federal Information Processing Standards (FIPS)
A set of guidelines for US government systems.  NIST issues FIPS.
*** Using Public-Key Infrastructure (PKI)
PKI: A two-key, asymmetric system with four components: certificate authority
(CA), registration authority (RA), RSA (the encryption algorithm), and digital
certificates.  Messages are encrypted with public keys and decrypted with
private keys.

PKI is a framework, and not a specific technology, with vendor-specific
implementations (some are incompatible).
**** Using a Certificate Authority (CA)
CAs are organizations responsible for issuing, revoking, and distributing
certificates.  A certificate is a mechanism for associating a public key with
an individual, containing information about the user.  Each PKI system user
has a certificate used to verify their authenticity.

To get a certificate, submit a certificate-signing request (CSR) to the CA.
The CSR contains the public key you wish to use and your fully distinguished
name (often a domain name).

CAs can be private or public.  Verisign is the best known public CA.

If a CA server gets overloaded, some work can be offloaded to an RA server.
**** Working with registration authorities (RAs) and local registration authorities
RAs offload some CA work.  It can distribute keys, accept registrations, and
validate identities.  CAs still issue certificates.

Local registration authorities (LRAs): Can also issue certificates.  LRAs can
physically identify individuals, unlike RAs.
**** Implementing certificates
***** X.509
The most popular certificate used.  A standard format supported by the ITU and
others.

The certificate contains identifiers of two different algorithms used in the
process.  The signature algorithm is Md2RSA and the digital signature algorithm
is sha1.  It also contains the unique serial number issued by the CA.
***** Certificate policies
Define what certificates do (e.g. email, finance, etc.) and affect how a
certificate is issued and used.  The receiving organization uses the CA's
policies to determine what certificates it will accept.  Cross certification
occurs when CAs have interoperability.
***** Certificate best practices
Certificate Practice Statement (CPS): CA uses this to issue certificates and
implement policies.
**** Understanding certificate revocation
Certificate Revocation: The process of revoking a certificate before it
expires.  Handled through a certificate revocation list (CRL) or by using OCSP.

Must be done when the private key becomes known.

Latency can be an issue due to hourly/daily CRL updates.  OCSP solves this
problem.
**** Implementing trust models
Four main trust models used with PKI:
- Hierarchical
- Bridge
- Mesh
- Hybrid
***** Hierarchical trust models
Also known as a tree.  A root CA provides all information.  Intermediate CAs
only trust the root.  A root CA also trusts other intermediate CAs at the same
level in the hierarchy.  Leaf CAs serve end entities.
***** Bridge trust models
A peer-to-peer relationship between root CAs.  Root CAs can allow cross
certification.  Useful for flexibility and interoperability between
organizations, and geographically dispersed organizations.  Weakness is
trustworthiness of all root CAs.  An illegitimate certificate can become
available to all users in a bridge.
***** Mesh trust models
Supports multiple paths between root CAs.  Provides more flexibility for
configuring root CA structures.  Same weakness as bridge.
***** Hybrid trust model
Arbitrary trust model structures, where intermediate CAs can trust each other,
across hierarchies.  Downside is these can become complicated and unintentional
trusting can occur.
**** Hardware-based encryption devices
Trusted Platform Modules (TPMs): Can be enabled in some BIOS configurations.
TPMs are chips that store cryptographic keys, passwords, or certificates.  Used
on PCs and smart phones.  Can generate values used with whole-disk encryption
(e.g. BitLocker).  BitLocker can optionally use a TPM, and is much more secure
when doing so.

Hardware Security Module (HSM): A cryptoprocessor commonly used with PKI
systems to augment security with CAs.  Traditionally are PCI modules.
**** Data encryption
BitLocker does full disk encryption of a volume with 128-bit encryption.
Prevents bypassing security by booting another OS.  BitLocker to Go provides
the same for removable media, such as flash drives.  TrueCrypt is another
alternative.

Some RDBMSes like SQL Server provide database encryption.
*** Review questions
1 B
2 B
3 A
4 C
5 D
6 A
7 C
8 B
9 C
10 A
11 A
12 C
13 B
14 C
15 A
16 A
17 D
18 A
19 A
20 D
*** additional notes
- Key transmission: The most serious threat to key security.  Use out-of-band
  methods to do so.
- Key storage: Physically stored in a secure environment.  Use locked cabinets,
  hardened servers, and physical/administrative controls.
- Suspending keys: A good practice for absent employees.  These can be
  reactivated later.
** Chapter 9: Malware, vulnerabilities, and threats
*** Understanding malware
Software exploitation: Attacks launched against applications and higher-level
services.

Exploitations introduced by using viruses or access attacks:
- Spyware: Monitors user's activity and reports it to a third party.  Usually
  exist for commercial gain.
- Adware: Displays ads and generates revenue for the creator.
- Rootkits: Programs that have the ability to hide certain things from the
  OS.  May hide tasks from Task Manager or connections from netstat.  Best
  defense is system monitoring and catching the rootkit during install.
- Trojan horses: Programs that enter a system/network under the guise of
  another program.  Could create a backdoor or replace a valid program.  Best
  defense is to not install them and back up systems pre/post-install of
  software OSes.  Also check for open ports not regularly used.
- Logic bombs: Programs or code that executes when certain preconditions are
  met.  Some notify an attacker when the system is in a particular state.
- Backdoors: Refers both to the intentionally created backdoors used by
  developers and malware that creates an entrance for an attacker, bypassing
  security.  Usually an access or modification attack, and sometimes use remote
  administration tools.  Most conventional AV software will detect these.
- Botnets: Bots running on zombies, under the control of a bot-herder.  Used
  for DoS and DDoS attacks, adware, spyware, and spam (spambots).  No
  universal defense, but some can be detected by looking at databases of known
  threats, whereas others can be identified through detecting behavior.
- Ransomware: Takes control of a system (often through a trojan) and demands a
  payment.  Can encrypt a hard drive, change passwords, etc.
*** Surviving viruses
Viruses can get on a system via:
- Contaminated media.
- Through email and social networking sites.
- As part of another program.

Viruses can be classified as:
- Polymorphic: Changes form to avoid detection.
- Stealth: Avoid detection by masking themselves from applications.
- Retroviruses: Attack or bypass installed AV software.
- Multipartite: Attack a system in multiple ways.
- Armored: Designed to make it difficult to detect or analyze.
- Companion: Attaches to legitimate programs and creates versions of programs
  with different extensions.
- Phage: Modifies or alters other programs and databases.
- Macro: Exploits scripting systems within other programs.
**** Symptoms of a virus infection
Some are obvious.  Others just cause slow down, cause files to disappear, or
take over disk space.

Symptoms to look for:
- Programs load more slowly.
- Unusual files appear or files disappear.
- Program sizes change from installed versions.  Occurs with viruses that
  attach to executables.
- Applications (browsers, word processors, etc.) begin to exhibit unusual
  behavior
- System stops/starts itself and has unexplained disk activity.
- Mysterious loss of disk access or other system resources.  Occurs when
  viruses change device settings.
- System doesn't reboot or gives unexpected error messages during startup.
**** How viruses work
Many viruses will infect every file or many of them on the system to spread to
other systems.  Many spread via email or thumb drives.
**** Types of viruses
- Armored virus: Cover themselves with protective code that stops debuggers or
  disassemblers from examining critical elements of the virus.  Delays
  identification of the virus, allowing it time to spread.
- Companion virus: Creates programs of different file extensions to existing
  ones.  May reside in the system's temp directories.  Many on Windows change
  program pointers in the registry.  When run, will perform its actions then
  launch the real program.
- Macro virus: Can infect documents and spread to other systems via email.
  The fastest growing virus type.
- Multipartite virus: Attack systems in multiple ways.  May infect the boot
  sector, infect executables, and destroy application files.  The purpose is
  to decrease likelihood of correcting all problems.
- Phage virus: Modifies/alters other programs or databases.  The only way to
  remove the virus is to reinstall the programs infected.  Easy to miss a
  single instance of it.
- Polymorphic virus: A subset of polymorphic malware, changing form to evade
  detection.  Will attempt to hide from AV.  Will encrypt parts of itself to
  avoid detection.  Performs mutation, making it hard for AV to detect common
  patterns within it.
- Retrovirus: Attacks or bypasses AV.  Can destroy the virus definition file,
  or directly attack the AV program.
- Stealth virus: Avoids detection by masking itself from applications.  May
  attach to a boot sector.  May redirect commands from system utilities around
  itself.  May report different file sizes than actual.  May move filenames
  during a scan.
**** Managing spam to avoid viruses
While also annoying, spam can direct to sites infected with viruses, worms,
etc.  SPIM: spam over IM.  SPIT: spam over telephony.
**** Antivirus software
AV scans for characteristics, or fingerprints, common in viruses, identifying
and neutralizing them prior to causing damage.  Keep definition databases up to
date.  Layer AV defense on gateways, servers, and desktops.  To go further, use
AV from multiple vendors.  Educate users to not open suspicious files.
*** Understanding various type of attacks
**** Identifying denial-of-service and distributed denial-of-servce attacks
DoS attacks prevent access to resources by users authorized to use them.
These can:
- Deny access to information, applications, systems, communications.
- Bring down a website.
- Crash an OS.
- Fill a communications channel.
- Open many TCP sessions.  Called a TCP SYN flood DoS.

Two most common types:
- Ping of death: Sending ICMP packets larger than the system can handle.
- Buffer overflow: Put more data (e.g., long input strings) into the buffer
  than it can hold.

DDoS used multiple systems (often botnets) to conduct simultaneous DoS
attacks.  Far more common and effective than DoS.

Little can defend against DoS and DDoS attacks.  OS updates can minimize their
effects.
**** Spoofing attacks
An access attack where identity masquerading occurs.  A fake login screen is
one example.  Most common are:
- IP spoofing: Makes data look as if it came from a trusted host, spoofing the
  IP of the sending host.
- ARP spoofing: Also known as ARP poisoning.  Faking a MAC address, making it
  looking like it came from a network it didn't.  Can gain access to a network,
  fool a router into sending data to it intended for another host, or launch a
  DoS attack.  The address is that of a legitimate user, bypassing allow/deny
  lists.
- DNS spoofing: Giving a DNS server information about a name server that isn't
  legitimate.  Can send users to other websites, reroute mail, or other
  misdirection.  Also called DNS poisoning.

Domain name kiting: Another DNS weakness that takes advantage of the 5 day
grace period between registration and required payment, deleting and
registering the account before the period ends.
**** Pharming attacks
A form of redirection where traffic intended for one host is sent to another.
Can be done by changing entries in a host file or DNS server.
**** Phishing, spear-phishing, and vishing
Phishing: A form of social engineering involving a legitimate-looking
information request.

Spear phishing: Tailoring a message to recipients that impersonate entities
they trust.  Uses obtainable information like email databases, friend lists,
etc.

Vishing: Combination of phishing and VOIP.  VOIP doesn't include caller ID or
tracing.
**** Xmas attack
A scan using nmap to get around firewall detection to look for open ports.
**** Man-in-the-middle attacks
Secretly place software or a rogue router between a server and user.
Intercepts data and sends the information between the server and client as if
nothing is wrong.  Can collect or alter data, or otherwise compromise the
security of a system.  A particular problem with wireless.

TCP/IP hijacking: Gaining access to a host and logically disconnecting it from
the network, then replacing it with another of the same IP.  Can give the
attacker access to the session and other information of the original system.
More difficult to engineer.
**** Replay attacks
Capturing and replaying information to a server over a network.  Login/password
information can be captured and replayed to the server.  Also occurs with
certificate systems like Kerberos.

Countering replay attacks is the main reason for certificate session
identifiers and time stamps.  Expired certificates should be rejected.
**** Smurf attacks
Spoofing the target machine's IP address and broadcasting to it's routers so
the routers think the target is sending out the broadcast.  Every machine on
the network then responds and overloads the target system.

Solved by blocking ICMP traffic through the router.
**** Password attacks
Attack accounts repeatedly using password crackers.

Types of password attacks:
- Brute-force attack: Iterating through all possible guesses.  Defended by
  minimum password length and password lockout policies.
- Dictionary attack: Iterating through common words.
- Hybrid: Combined brute-force/dictionary attacks, seeding known values into
  those attempted.  Can use rainbow tables.
- Birthday attack: With hashed keys, finding a value that produces the same
  hash.
- Rainbow table: Comparing hashed phrases or words to identify a stored
  value.  Defended with password salt.

Don't confirm account existence when a password is incorrect but an account
exists.
**** Privilege escalation
User gaining more privileges, often by unintentionally leftover backdoors.
**** Malicious insider threats
Defended by white box testing: testing systems from the premise of knowing
about the network and systems in place.  Also called full disclosure testing.
**** Transitive access
Transitive trust is enabled by default in AD.
**** Client-side attacks
Targeting vulnerabilities in client applications that interact with a
malicious server.  Rouge code runs at the same access level as the user.
**** Typo squatting and URL hijacking
Synonymous terms.  Setting up malicious servers on misspelled URLs.

Register domains around yours for deviations and other top-level domains.
**** Watering hole attack
Identifying a site visited by those being targeted, then poisoning that site
and waiting for results.  E.g., installing malware on a target's third part
email provider.
*** Identifying types of application attacks
**** Cross-site scripting and forgery
XSS: An attacker tricking a user who visits a site into having code execute
locally.

An attacker might use a website control where input is allowed to be posted and
insert malicious scripts.  The prevention for this is to filter input.

Cross-site Request Forgery (XSRF): Also called session riding and one-click
attack.  Unauthorized commands coming from a trusted user to a website.
Exploits unexpired cookies on website user account logins.

The best protection against XSS is disabling the running of scripts and
using browser profiles.
**** SQL injection
Most common exploit categories, using SQL injection:
- Escape characters not filtered correctly.
- Type handling not properly done.
- Conditional errors.
- Time delays.

Defend by filtering input.  Reject input with certain characters.
**** LDAP injection
Exploits weaknesses in LDAP implementations, where user input isn't properly
filtered and commands are executed.  Defend by filtering input.
**** XML injection
Injecting values that query XML (XPath, which is a QL for XML).  XML doesn't
have the same levels of access control and entire document contents can
returned.  Defend by filtering input.
**** Directory traversal/command injection
Directory traversal attack: If an attacker can gain access to restricted
directories of a website, they may be able to gain access to the root
directory of the system.  The common method of this is to use a command
injection attack to execute shell commands on the server.  Ability to do this
limited today.  Defend by running scanners and patch web server software.
**** Buffer overflow
Causes applications to terminate or write data beyond the end of allocated
space.  Termination may leave the system sending data with privileged access
levels.  Overwriting can cause important data to be lost.
**** Integer overflow
Overflowing the bit-length of integer variables.
**** Zero-day exploits
Exploits used on the day of discovery, front-running the typical one-to-two day
response time needed to patch.  Defend by turning off services between
discovery and patch.
**** Cookies and attachments
Cookies have the potential to contain personal information.

Evercookie: Writes data to multiple locations and are hard to remove
completely.

Best protection is to disable cookies.  Can also disable cookies from external
sites.  A compromise is to only allow session cookies.
**** Locally Shared Objects (LSOs) and Flash Cookies
Synonymous terms.  Data stored on the user's system by Adobe Flash.  Often used
for Flash games or user preferences.  Can represent a security/privacy threat.
**** Malicious add-ons
Java applets run in a sandbox.  Usually safe, but errors in the JVM may allow
breaking out.  Defend by only running applets from reputable sites.

ActiveX uses Authenticode as a certificate technology to validate components
with a server.  Uneducated users may enable ActiveX controls, creating a
security risk.  Defend by configuring browsers to prompt the user before
running ActiveX.
**** Session hijacking
Stealing the item used to validate a user's session, such as a cookie, and
using it to establish a session with a host that thinks it's still
communicating with the user.  Man-in-the-middle and sidejacking use session
hijacking.

Defend by encrypting sessions, encouraging users to log out of sites when
done, and perform secondary checks on user identity.
**** Header manipulation
Uses other methods here to change values in HTTP headers and falsify access.
When used with XSRF, can change user cookies.
**** Arbitrary code and remote code execution
Synonymous terms.  An application can be written in a way to accept arbitrary
remote commands and run them on the host, under the privileges of the
user/program.
*** Tools for finding threats
**** Interpreting assessment results
Filtering and interpreting collected data.
**** Tools to know
Active vs. passive response.
***** Understanding protocol analyzers
Protocol analyzers are synonymous with packet sniffers.
***** Working with vulnerability scanners
Checks a network for known security holes.  E.g., Nessus and Retina.

Major tasks necessary in using vulnerability scanners:
- Passively testing security controls: The scanner testing the security
  controls without doing any actual harm.  Just looks for openings and reports.
- Interpreting results: Scanners return a report of interpreted results.
- Identifying vulnerability: Map open port to service.
- Identifying lack of security controls: Find places with no controls, not
  just weak ones.
- Identifying common misconfigurations: Ensure applications and services are
  properly configured.
***** Honeypots and honeynets
***** Working with a port scanner
Part of fingerprinting a network, identifying services available on it.
Possible internally and externally.  Many routers default to let all protocols
pass through.
***** Banner grabbing
Looking at the header information of messages to find out about systems.
Banners often identify the host, OS, etc.  Can be grabbed with telnet, netcat,
or nmap.
**** Risk calculations and assessment types
Focus areas for network security and vulnerability:
- Risk: What's the actual dangers and likelihood.
- Threat: Means and source of attack, weighed against the likelihood.
- Vulnerability: Identify flaws, holes, and areas of exposure.
***** Baseline reporting
Checks to make sure that things are operating status quo.  Change detection is
used to alert administrators when modifications are made.  A
changes-from-baseline report can be run to find security breaches.  Often
combined with gap analysis to check against industry standards.
***** Code review
Part of gray box testing.  Reading code is called manual assessment.  Using
tools is called automated assessment.
***** Determine attack surface
Attack surface: Area of application available to users (both authenticated and
not).  Includes services, protocols, interfaces, and code.

Attack surface reduction: Minimizing attack surface area.
***** Architecture
Architectural approach to security: Using a control framework to focus on
underlying infrastructure.  Popular with regulatory and compliance standards.
***** Design review
Examines ports and protocols, rules, segmentation, and access control.  More
granular than architecture assessments.
*** Review questions
1 B
2 B
3 C
4 A
5 C
6 D
7 A
8 A
9 A
10 B
11 A
12 B
13 A
14 D
15 B
16 C
17 D
18 C
19 B
20 D
*** Additional notes
nmap is a vulnerability scanner.
** Chapter 10: Social engineering and other foes
*** Understanding social engineering
Social engineering: Gaining access to facilities, networks, or employees by
exploiting the trusting nature of people.  Also called wetware.
**** Types of social engineering attacks
Common attacks:
- Shoulder surfing: Watching others enter sensitive data.  Defend by surveying
  your environment before entering such information and position monitors in
  directions others can't see.
- Dumpster diving: Shred documents.
- Tailgating: Following others through locked doors.
- Impersonation: Can be done in person, over phone, by email, etc.
- Hoaxes: Includes virus hoaxes.  Check CERT to confirm before forwarding
  notice.
- Whaling: Phishing or spear phishing, but targeting big users, usually an
  owner or manager.
- Vishing: Impersonation over VOIP, where caller ID and tracing don't exist.

Counters are user education and tools to detect online phishing sites (such as
IE's SmartScreen Filter).
**** What motivates and attack?
Greed, bribes, and malicious insider threats.
**** The principles behind social engineering
Reasons for effectiveness:
- Authority: Authority figures are less likely to provoke questioning.
- Intimidation
- Consensus/social proof: Charming a target.
- Scarcity: Limited supply of something.
- Urgency: Time to act.
- Familiarity/Liking
- Trust: Reciprocation of trust.
**** Social engineering attack examples
*** Understanding physical security
Access control: A critical part of physical security.

Physical barriers: The most effective are multiple barrier systems, requiring
more than one physical barrier to be crossed.  Ideally, you should have three:
- Perimeter: External entrance to the building, protected by alarms, walls,
  fencing, surveillance, etc.  Use with an access list, identifying who can
  enter, to be verified by guard or others.
- Locked door protecting computer center: Also include ID badges, proximity
  readers, fobs, or keys.
- Entrance to computer room: Another monitored, locked door.

Escort temporary access individuals, like repair men.

Proximity reader: Any ID or card reader reading proximity cards, which use
RFID.

Physical tokens/fobs: Anything a user must have on them to access network
resources.  Often use one-time password authentication.
**** Hardware locks and security
Applying physical security modifications to prevent systems from leaving the
facility.  A cable lock prevents a laptop from being removed from a desk.

Add locks to desktop back covers to prevent removal of hard drives.  Use a safe
and locking cabinets to protect backup media, documents, and other artifacts.
Server racks should lock servers into cabinets.
**** Mantraps
Require visual identification and authentication to gain access.  Limits access
to 1-2 people at a time.  Can contain an unauthorized person for authorities.
Some include scales for weight checking.
**** Video surveillance
***** Camera vs. guard
Camera/CCTV: Always running, records, and creates evidence.  Stationary, lacks
intelligence, is possible to avoid, and needs someone to monitor or review the
tape.

Guard: Can move about, apply intelligence, and collect evidence.  Not
recording, can be avoided, and has downtime.
**** Fencing
Perimeter security analogous to network security's border routers.
**** Access list
Specify those authorized to enter a facility.  Can be verified by guard or
other authority.  Similar to ACLs for networks.
**** Proper lighting
A deterrent and useful for visual identification.
**** Signs
Authorized access only.  Violators will be prosecuted.

Also used for login banners on computer systems.
**** Guards
Effective, but expensive and fallible.
**** Barricades
Also gauntlets.  Combined with other measures or used alone.
**** Biometrics
Use unique biological traits for identification.  Hand scanners, retinal
scanners, facial recognition, and keystroke recognition.  Laptops often
include fingerprint readers.
**** Protected distribution
Protected distribution systems (PDS): A system where the network is secure
enough for classified information transmission unencrypted.  Substitute
encryption security for physical security.  Called approved circuits.  Used by
the US government.
**** Alarms
Draws attention to a suspected breach.

Security zone: An area where access is individually monitored and controlled.
Alarms identify the zone of intrusion.  Zone notification tells security where
to look for intruders.
**** Motion detection
Detects movement via infrared, microwave, or sonic.  Can use hybrid sensors.
*** Environmental controls
**** HVAC
Systems ideally located central in the building, with separate ducting from
the rest of the HVAC system.  Zone-based environment control allows the rest
of the facility's HVAC to be turned off while maintaining full-time service to
the computer room.
**** Fire supression
Extinguishing active fires, not prevention.
***** Fire extinguishers
Portable.  Type classifications:
| Type | Use               | Retardant composition     |
|------+-------------------+---------------------------|
| A    | Wood, paper       | Largely water or chemical |
| B    | Flammable liquids | Fire-retardant chemicals  |
| C    | Electrical        | Nonconductive chemicals   |
| D    | Metal             | Varies; type specific     |
| K    | Cooking oil       | Subset of B               |

Multipurpose extinguishers combine capabilities.  Common are A-B, B-C, and ABC.

Remove power from electrical fires to prevent recurrence.

Extinguishers require annual inspection.
***** Fixed systems
Combine fire detectors with fire-suppression systems.  Detectors trigger on
rapid temperature change or smoke.  Suppression uses water or fire-suppressing
gas.

Water: Can cause damage to active electrical equipment like computers.  Fixed
systems can be tied to relays to cut power before releasing water.

Gas: Halon no longer used for environmental reasons.  FM200 most common now.
Displaces oxygen from a room.  Can suffocate humans.  Require sealed
environments to work.  Expensive.
**** EMI shielding
Shielding: Preventing electronic emissions from computers being used to gather
intelligence and preventing outside EMI from disrupting computers.  A Faraday
cage does this, surrounding a room in a grounded wire mesh.

Eletromagnetic interference (EMI): Caused by motors, lights, etc.  Can cause
overload, spikes, or component failure.  Shield and ground signal lines and
separate EMI generating equipment from cabling.

Radio frequency interference (RFI): Similar to EMI but on the radio spectrum.
Motors with defective brushes can cause RFI.  Can cause wireless receivers to
become deaf, a process called desensitizing.  Only solution is to move devices
farther apart.

TEMPEST shielding protection: A system that doesn't emit significant EMI or
RFI.  Control zones and white noise can accomplish shielding.  A certified
standard.
**** Hot and cold aisles
Combine to regulate air flow in server racks.  Cold air usually comes from a
raised floor.
**** Environmental monitoring
Computer rooms should have fire and moisture detectors.  Moisture monitors
could detect a burst pipe and cut power.
**** Temperature and humidity controls
Electrostatic shock damage can occur if humidity is too low (below 50%).
Regularly service environmental systems.
*** Control types
Six control types:
- Deterrent: Delays/discourages attack, like warnings.
- Preventive: Stop event from happening, like locks.
- Detective: Uncover violations.  When prevention fails.  Sounds alarm.
- Compensating: Backup for failed controls, like extra alarms, backup
  generators, etc.
- Technical: Implemented through technology.  Can be any other type too,
  except administrative.
- Administrative: Comes down through policies, procedures, and guidelines,
  like an escalation procedure.
**** A control type analogy
*** Data policies
Focuses of a data policy:
- Wiping: How data is removed from media.
- Disposing: Discarding media.
- Retention: How long to keep data.
- Storage: Where data is kept and access security for it.
**** Destroying a flash drive
Steps:
- Open case and retrieve memory chips.
- Turn chips to powder.  Hand drills work.
- Finish it off by tossing into fire.
**** Some considerations
Add passwords and encrypt drives.
**** Optical discs
Use a disc shredder.  Optionally apply palm or belt sander to data side first.
*** Review questions
1 A
2 C
3 A
4 D
5 D
6 C
7 A
8 C
9 B
10 A
11 C
12 A
13 A
14 D
15 A
16 B
17 C D
18 A
19 B
20 C
*** Additional notes
Proximity readers work with 13.56Mhz smart cards and 125kHz proximity cards.
** Chapter 11: Security administration
*** Third-party integration
**** Transitioning
Occurs during on-boarding or off-boarding of a business partner.

On-boarding: Determine whether security policies of both organizations are
compatible, at least in areas where interaction occurs.  Determine data
ownership, data responsibility, and backups.  Also important are privacy
concerns.

Interoperability agreements are documents that define how the systems will
interoperate and what the requirements and specifications are.  Some of the
documents that need to be part of the interoperability agreement:
- Service-Level Agreement (SLA): Level of service provided, such as support
  response times.
- Blanket Purchase Order (BPO): An agreement between the government and a
  company for ongoing purchases.
- Memorandum of Understanding (MOU): Summarizes which party is responsible for
  what portion of work.
- Interconnection Security Agreement (ISA): Details technical requirements of
  connected systems.
**** Ongoing operations
Address security issues on and ongoing basis, including risk awareness
(sharing information regarding risks).
*** Understanding security awareness and training
**** Communicating with users to raise awareness
Use internal security websites, news servers, and emails.  Use a regular
notifications process to inform on security and changes.
**** Providing education and training
Tailor for:
- Organization: Rank and file employees.
- Management.
- Technical staff.

Organization: Recommend doing during new employee orientation and staff
meetings, repeating it periodically.  Have employees sign off on receiving
training.  Security awareness training here should cover:
- Importance of security.
- Responsibilities of people in the organization.
- Policies and procedures.
- Usage policies.
- Account and password-selection criteria.
- Social engineering prevention.

Management: Give additional training/exposure to issues, threats, and method
of dealing with threats.  Discuss productivity impacts.

Technical staff: Require special knowledge about methods, implementations, and
capabilities of security systems.  Will need to be vendor-specific.

Gather training metrics to validate compliance and effect on security.
**** Safety topics
Refers to safety of data and physical environment, and also to humans.  Topics
related to safety:
- Fencing.
- Lighting.
- Locks.
- CCTV.
- Escape plans.
- Drills: Ensure knowledge of escape plans.
- Escape routes: Include alternative routes.
- Testing controls: Technical, management, and operational.
**** Training topics
Topics for user education:
- Clean desk policy: Notes, papers, etc. on a desk can be a security risk.
  Sensitive information should be stored when employees are away from their
  desks.
- Compliance with laws, best practices, and standards: Keep up to date on
  regulations and laws.
- Data handling: Limit access to only those needing it.  Implement and educate
  on data safeguards.
- Policy on personally owned devices: Segregate personal and company data.  Do
  not allow syncing of smartphones to work systems.  Ban all P2P networking.
- Personally Identifiable Information (PII): Includes names, biometrics,
  and financial/health information.  NIST issues guidelines regarding PII.
  Explain phone SIM modules contain PII.
- Prevent tailgaiting: Also called piggybacking.
- Safe Internet habits: Educate on phishing, pop-ups, and downloading software.
- Smart computing habits: Never introduce stray media.  Require IT approval
  for third-party software installs.
- Social networking dangers: Educate on exercising caution when using.
- The need for all computing to be safe: Educate on weakest link rule.
  Recommend security like firewalls and AV for employee home systems.
- The value of strong passwords: Password complexity, change policy, and
  secrecy.
- Understanding data labeling and handling: Differing value of various data.
- What to do when disposing of old media: Data disposal, including for home
  systems that have work data.
- Responding to hoaxes: Scareware tries to convince a threat exists.
  Rougeware tries to extract protection payment for nonexistent threats.
  Policy when encountering possible hoaxes should be to contact IT.
*** Classifying information
Information classification: Support the organization's privacy requirements,
preventing unauthorized disclosure of sensitive information.

Classify information into three categories: public use, internal use, and
restricted use.  Internal and restricted are also called private.  Most
information is for internal use.
**** Public information
Includes information accessible to the general public or two just specific
individuals who need it.  Need to develop policies about what information is
available and for what purpose it's disseminated.  Assigned disclosure
authorization.
***** Limited distribution
Data not intended for public release.  Private, but not secret.

Beta test is an example of limited distribution, requiring participants to
sign NDAs.

Statements about privacy and confidentiality are common on limited-access
documents and indicate unauthorized disclosure is a breach of confidentiality.
***** Full distribution
Marketing material, annual stockholder reports, and other PR.  Sometimes
controlled by a corporate communications department.
**** Private information
Information intended only for internal use.  Also called "working documents" or
"work product".
***** Internal information
Includes personnel records, financial working documents, ledgers, customer
lists, etc.
***** Restricted information
Disclosure could seriously damage an organization.  Includes proprietary
processes, trade secrets, strategic information, and marketing plans.  Usually
considered need-to-know.
*** Information access controls
Access controls: Methods used to ensure users can access only what authorized
for.  Should be detailed in the organization's security policies/standards.
Key concepts:
- Implicit deny.
- Least privilege.
- Job rotation: Redundancy in skills.
**** Security concepts
The CIA triad: Confidentiality, integrity, and availability.  The opposite of
DAD: Disclosure, alteration, and destruction.
- Confidentiality: Preventing unauthorized access to data.  Encryption,
  passwords, access control, steganography.
- Integrity: Ensuring data hasn't been altered.  Hashing, message
  authentication codes, nonrepudiation with digital signatures.
- Availability: Ensuring systems are available.  Backups, redundancy, disaster
  recovery plans.
*** Complying with privacy and security regulations
**** The Health Insurance Portability and Accountability Act (HIPAA)
Standards and procedures for personal medical information.  Covers
confidentiality, privacy, and security of records.
**** The Gramm-Leach-Bliley Act
Also known as the Financial Modernization Act of 1999.  Requires financial
institutions to develop privacy notices and inform customers on privacy.
Prohibits release of customer information by banks.
**** The Computer Fraud and Abuse Act (CFAA)
Federal authorities granted power to prosecute hackers, spammers, and others
as terrorists.
**** The Family Educational Rights and Privacy Act (FERPA)
Covers release of student information by educational institutions.
**** The Computer Security Act of 1987
Requires federal agencies to protect systems containing sensitive information.
**** The Cyberspace Electronic Security Act (CESA)
Grants law enforcement the right to gain access to encryption keys and
cryptography methods.
**** The Cyber Security Enhancement Act
Allows federal agencies access to ISP and data transmission facility data.
**** The Patriot Act
Includes authority to intercept electronic communication.
**** Familiarizing yourself with international efforts
Cybercrime Treaty: Makes hacking illegal in Europe.
*** Mobile devices
Security measures for mobile devices:
- Screen lock: Set timeouts with password locks.  Include repeated failed login
  lockouts.
- Strong password.
- Device encryption: Use TPMs.
- Remote wipe/sanitation: Remotely clear data or stolen or transferred devices.
- Voice encryption: Phone call encryption.
- GPS tracking: Track location of stolen devices.
- Application control: Controlling what applications are installed on the
  device.
- Storage segmentation: Keep work data separate and possibly separately
  encrypted.
- Asset tracking: Inventory control of devices.
- Device access control: Controlling who has a mobile device.
**** BOYD issues
Employees bringing personal devices into the corporate network environment.

Disallow connecting such devices to the network and use a second Wi-Fi guest
network for this.  Have a policy to address cell phones photographing or
recording sensitive information, like having it subject to random search.
Address data ownership for situations like where company data is on personal
devices.
*** Alternative methods to mitigate security risks
Use a combination of network segmentation and security layers.  Zone based
upon security levels.

Application firewalls (WAPs?) are better protection for database and web
servers than other types, since they filter application content.

Apply updates, including for firmware.  Certain viruses target router and
switch firmware.  Use firmware version control.

Control redundancy and diversity: Implement more than one of each security
control.  Diversity means using different controls of the same type (e.g. using
a Cisco IDS on the perimeter but a SNORT IDS inside the network).  Use
wrappers around sensitive data, like having data servers on their own segment
with their own firewall, IDS, and AV.

Specialized systems:
- SCADA (supervisory control and data acquisition): Equipment used to manage
  automated factory equipment, dams, power generators, etc.  Stuxnet attacked
  SCADA systems.
- Embedded systems (printers, smart TVs, HVAC controls, game consoles): Device
  dependent, but have similar security needs due to having HDs, RAM, and OSes.
- Smartphones: Security issues differ between Android and iOS.
- Mainframes: More secure generally, but not invulnerable.
- In-vehicle computing systems: Use HDs and GPS.  Implementation dependent.
*** Review questions
1 A
2 D
3 A
4 C
5 D
6 D
7 A
8 B
9 B
10 B
11 A
12 C
13 D
14 A
15 B
16 B
17 A
18 A
19 A
20 B
** Chapter 12: Disaster recovery and incident response
*** Issues associated with business continuity
Business continuity: The processes, policies, and methods used to minimize
impact of a system or network failure.

Business continuity planning (BCP): Process of implementing business
continuity.  A management tool ensuring critical business functions when normal
ones are disrupted.

Critical business functions (CBFs): The processes or systems that must be made
operational immediately when an outage occurs.  The business cannot function
without them.
**** Types of storage mechanisms
Reasons for restores:
- Accidental deletion.
- Application errors.
- Natural disasters.
- Physical attacks.
- Server failure.
- Virus infection.
- Workstation failure.

Data storage mechanisms:
- Working copies: Also called shadow copies.  Partial or full backups kept for
  immediate recovery.  Updated frequently and are usually the most recent.
  Some filesystems include journaling.  A journaled file system (JSF) includes
  a log of transactions within a recent time range.  With crashes, the OS can
  check logs to see which transactions have been committed.
- Onsite storage: Storage location on the site of the computer center.  Often
  stored in fire-rated containers.
- Offsite storage: 
**** Crafting a disaster-recover plan
***** Understanding backup plan issues
***** Knowing the backup types
***** Developing a backup plan
***** Recovering a system
***** Backout vs. backup
***** Planning for alternate sites
**** Incident response policies
**** Understanding incident response
***** Step 1: identify the incident
***** Step 2: investigating the incident
***** Step 3: repair the damage
***** Step 4: documenting and reporting the response
***** Step 5: adjusting procedures
***** Forensics from the Security+ perspective
**** Succession planning
**** Tabletop exercise
*** Reinforcing vendor support
**** Service-level agreements
**** Code escrow agreements
*** Penetration testings
**** What should you test?
**** Vulnerability scanning
***** Credentialed vs. noncredentialed
*** Review questions
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


* Assessment test (first try)
1 A
2 D
3 
4 A x
5 
6 B?
7 D x
8 B? x
9 A x
10 B?
11 A 
12 A?
13 
14 D x
15 A
16 
17 C? x
18 D
19 A
20 
21 A
22 B
23 A
24 C
25 
26 
27 C x
28 C
29 
30 A
Score: 50%


* Assessment test (second try)
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
Score:


* All review questions (second try)
*** Chapter 1
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
*** Chapter 2
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
*** Chapter 3
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
*** Chapter 4
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
*** Chapter 5
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
*** Chapter 6
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
*** Chapter 7
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
*** Chapter 8
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
*** Chapter 9
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
*** Chapter 10
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
*** Chapter 11
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
*** Chapter 12
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
*** Score
