Time-stamp: <2014-12-01 16:57:41 (bmiller)>
#+STARTUP: content

* Security+ SY0-401
** Chapter 1: Measuring and weighing risk
*** risk assessment
A process conducted in which threats, vulnerabilities, and impacts of a loss
are assessed.  Determines which risks are real/likely.  Coordination with the
Business Impact Analysis (BIA) determines course of action.
**** computing risk assessment
Prioritize and determine which risks are acceptable.  NIST provides a guide
for conducting assessments.
**** risk calculations
Risk impact terms:
- ALE: Annual Loss Expectancy.  A monetary measure of loss, every year.
- SLE: Single Loss Expectancy.  A monetary measure of loss for one event.  This
  is divided into AV (asset value) and EF (exposure factor).  SLE = AV * EF.
- ARO: Annualized Rate of Occurance.  Chance of an event occurring within a
  year, based on historical data.

Formula: SLE * ARO = ALE
**** quantitative vs. qualitative risk assessment
Risk assessments are either qualitative (opinion-based and subjective) or
qualitative (cost-based and objective).  If a dollar cost can be assigned,
it's quantitative.
**** additional risk terminology
- Likelihood: A score representing the possibility of threat initiation.  Goes
  from 10-0, with 10 being a certainty that the adversary will initiate a
  threat event.
- Threat vector: The way in which an attacker poses a threat.
- Mean Time Between Failures (MTBF): The measure of the anticipated incidence
  of failure for a system or component.  E.g., if a system's MTBF is 1 year,
  expect to replace it once a year.
- Mean Time to Failure (MTTF): The average time to failure for a
  non-repairable system.  Same as MTBF, but for non-repairable systems.
- Mean Time to Restore (MTTR): How long it takes to repair a system once a
  failure occurs.
- Recovery Time Objective (RTO): The maximum amount of downtime considered
  acceptable.  Agreed upon during BIA creation.
- Recovery Point Objective (RPO): The point in time from which the system needs
  to be restored.  The shorter the RPO time, the more expensive.
- Service Level Agreement (SLA): Formally defines service provided.
**** acting on your risk assessment
- Risk Avoidance: Identifying a risk and deciding not to engage in actions
  associated with it.
- Risk Transference: Sharing some of the burden of the risk with another
  entity (e.g. using insurance).
- Risk Mitigation: Taking steps to reduce a risk.  E.g., Data Loss Prevention
  (DLP) systems monitor the content of systems ensure key content is not
  deleted/removed.
- Risk Deterrence: Warning the adversary about consequences, like posting
  prosecution policies or warning of intrusion detection.
- Risk Acceptance: The choice to make when the cost of implementing the other
  choices outweighs the harm of an identified risk.
**** risks associated with cloud computing
Cloud computing implementations:
- PaaS: Vendors allow apps to be created and run on their infrastructure.
  E.g., AWS and Google Code.
- SaaS: Applications are remotely run over the Web.
- IaaS: Virtualized resources, billed by resource usage.

Risk-related issues:
- Regulatory compliance
- User privileges: Enforcing least privileges, reduced control.
- Data integration/segregation: Shared resources up data
  encryption/segregation requirements.
**** risks associated with virtualization
- Breaking out of the VM: Data access issues.
- Network and security controls can intermingle: Granularity differences
  between network and VM admin tools.
- Most attacks occur through the hypervisor, giving attackers root-level
  access to all VMs.
*** developing policies, standards, and guidelines
Policies provide high-level guidance, standards provide expectations, and
guidelines provide specific advice.
**** implementing policies
- Scope Statement: Outlines what the policy intends to accomplish and which
  documents, laws, and practices it addresses.  Usually a single sentence.
- Policy Overview Statement: Provides the goal of the policy, its importance,
  and how to comply.  Usually a single paragraph.
- Policy Statement: The substance of the policy.  E.g., how to lock up the
  building at night.
- Accountability Statement: Who is responsible for ensuring the policy is
  enforced.
- Exception Statement: Guidance on how to deviate from the policy and an
  escalation contact.
**** incorporating standards
Standards are derived from policies.  Provides enough detail that an audit can
be performed.

Key aspects of standards documents:
- Scope and Purpose: Explains/describes the intention.
- Roles and Responsibilities: Who is responsible for implementing, monitoring,
  and maintaining the standard.
- Reference Documents: Explains how the standard relates to the organization's
  policies, thereby connecting them.
- Performance Criteria: Outlines how to accomplish the task, including a
  relevant baseline and tech standards.
- Maintenance and Administrative Requirements: E.g., frequency of lock
  combination changes.
**** following guidelines
Helps users comply with standards, often step-by-step processes to accomplish
tasks.

Contents of guidelines documents:
- Scope and Purpose: Overview of the guideline's intent.
- Roles and Responsibilities: Who is responsible for accomplishing tasks.
- Guideline Statements: Step-by-step instructions.
- Operational Considerations: Specify what duties are required and at what
  intervals.
**** Business policies to implement
Primary areas of concern:
- Separation of Duties Policies: Designed to reduce risk of fraud and prevent
  other losses.  May require more than one person to accomplish key
  processes.
- Privacy Policies: Define what controls are required to maintain data
  privacy.  A legal document informed by laws.
- Acceptable Use Policies (AUPs): Describe how employees can use company
  systems and resources, including consequences for misuse.  Also known as a
  Use Policy.
- Security Policies: Define what controls are required for security.
- Mandatory Vacations: Addresses dependence upon single persons and an
  opportunity to discover fraud.
- Job Rotation: Same motivation as mandatory vacations, with an emphasis on
  redundancy in skills.
- Least Privilege: Users are given only the permissions needed to perform work.
- Succession Planning: Outlines internal persons that have the ability to step
  into positions when they open up.  Identifies key roles.
**** understanding control types and false positives/negatives
Once risks are identified, controls are put in place to address them.
Controls fall into three groups:
- Management: Risk assessment; planning; system and services acquisition;
  certification, accreditation, and security assessment.
- Operational: Personnel security, physical and environmental protection,
  contingency planning, configuration management, maintenance, system and
  information integrity, media protection, incident response, awareness and
  training.
- Technical: Identification and authentication, access control, audit and
  accountability, system and communication protection.

Once controls are implemented, audits should be performed.  While doing so,
pay attention to:
- False positives: Events flagged as anomalies that aren't really incidents.
- False negatives: Lack of alert on an real event.
**** risk management best practices
Implemented with a BIA.  What is shown in industry to produce superior results
regarding business continuity.
**** undertaking business impact analysis (BIA)
BIA is the process of evaluating critical systems to define impact and
recovery plans.  Focuses on impact a loss would have.

Key components:
- Identifying Critical Functions: Defines essential functions until restoration
  of full service.  Ensures Business Continuity Planning (BCP).
- Prioritizing Critical Business Functions: Categorizes essential/non-essential
  functions.  Useful allocating resources during recovery.
- Calculating a Timeframe for Critical Systems Loss: Evaluates maximum time a
  particular function can be unavailable.  Dictates contingencies to minimize
  loss when time is exceeded.
- Estimating the Tangible and Intangible Impact on the Organization: Details
  tangible (loss production/sales) and intangible (loss customer confidence)
  impact.
**** identifying critical systems and components
Build systems that don't have a Single Point of Failure (SPOF) by adding
redundancy.  Factor weather, natural disaster, and utilities into contingency
plans.
**** high availability (HA)
Measures used to keep services operational during an outage.  The goal is to
have 99.999% availability (five nines).
**** redundancy
Systems either duplicated or fail over to other systems.  Failover is the
process reconstructing a system or switching to another when failure is
detected.  In networks, this involves failover network paths.  Includes
clustering (load balancing).
**** fault tolerance
The ability of a system to sustain operation in event of component failure.
Stock spare parts and ensure power.  For parts, having N+1 is a common
strategy, where N is the number of parts in use.  For power, use UPSes with
surge protection or a backup generator.
**** RAID
- RAID 0: Disk striping.
- RAID 1: Disk mirroring.  Can alternatively be disk duplexing, which uses one
  more controller card (writing to both disks simultaneously).
- RAID 3: Disk striping with a parity disk.  Uses RAID 0 striping, but adds
  another disk for parity info.  Common in older systems.
- RAID 5: Disk striping with parity, spread across multiple disks.  Supports
  3-32 disks.  Can survive failure of only one drive.
**** disaster recovery
Recovering system operations after a disaster.  Planning includes designing a
comprehensive backup plan of backup storage, procedures, and maintenance.
Prioritize critical systems.
**** types of backups
Include both paper and computer records.
**** disaster recovery planning
Keep backups of key data, databases, applications, and paper records.
**** tabletop exercise
A method of accessing risk where a facilitator and participants discuss
possible situations and how to respond.
*** review questions
1 C
2 A
3 D
4 A
5 B
6 D (B)
7 A
8 D
9 B (C)
10 E
11 C
12 D
13 D
14 C
15 B
16 C
17 C
18 A
19 C
20 A
*** additional notes
- Change management: A structured approach to securing a company's assets.
** Chapter 2: Monitoring and diagnosing networks
*** monitoring networks
**** network monitors
- Sniffers: Another name for network monitors.  Enables examining the
  signaling and traffic that occurs on a network.
- Promiscuous mode: A NIC looking at any packet it sees on the network, even
  if the packet is not addressed to that NIC.
**** monitoring system logs
Event logs: System logs that record various events that occur.  Includes many
types of logs, but security and access logs are most pertinent here.

For Windows, the two most important are:
- Application Log: Contains events logged by programs, including errors.
  E.g., SQL Server uses this and the log can show DB compromise attempts.
- Security Log: Shows successful/unsuccessful login attempts and resource use
  (e.g. creating, opening, deleting files and other objects).  Event types to
  log can be specified.  Should always be changed to log both successful and
  failed login attempts.

In Linux, note:
- /var/log/faillog: Logs failed user logins.
- /var/log/apport.log: Logs application crashes.  Can sometimes reveal system
  compromise attempts or the presence of virii/spyware.
*** hardening
Hardening means to lock down and secure an OS as much as practical.  Ensure
unneeded services are turned off, unneeded software is uninstalled, patches are
updated, user accounts are checked, etc.
**** working with services
Part of OS hardening involves disable unnecessary services.

Tips:
- File and Print Servers: Primarily vulnerable to DoS.  Ensure only needed
  protocols are run.
- Networks with PC-Based Systems: Disable NetBIOS on servers or provide an
  effective firewall between them and the internet.  NetBIOS ports are 135,
  137, 138, and 139.  On Unix systems, close port 111 (RPC).
- Directory Sharing: Limit to what is essential for system functions.  Hide
  root directories from browsing -- instead, designate subfolders.
**** protecting management interfaces and applications
Admin interfaces should be restricted to only those admins who need it.
Protect server utilities and even workstation utilities like regedit.  Password
protect management functionality and consoles.

On Windows, use the Performance Monitor to look for possible illicit activity,
as it can do things like show excessive processor usage.
**** software
Remove unneeded software.  On Windows, remove Windows components that commonly
come preinstalled (via Programs and Features).
**** patches
A patch is an update to a system, adding new functionality or correcting bugs.
In a network environment, patches should be applied to a single machine and
tested first, as it's possible that patches could have problems.  In such
cases, not applying it is an option until a fix can be found.

Types of patches:
- Service pack: A periodic update that corrects problems in one version of a
  product.  Gets users to the current codebase for the product.
- Updates: Code fixes provided to individual customers experiencing critical
  problems that have no feasible workarounds.
- Security updates: Address security vulnerabilities.
** Chapter 3: Understanding devices and infrastructure
*** ports
- 21 FTP
- 22 SSH
- 25 SMTP
- 53 DNS
- 80 HTTP
- 110 POP3
- 139 NetBIOS session
- 143 IMAP
- 443 HTTPS
- 3389 RDP
** Chapter 4: Access control, authentication, and authorization
** Chapter 5: Protecting wireless networks
** Chapter 6: Securing the cloud
** Chapter 7: Host, data, and application security
** Chapter 8: Cryptography
** Chapter 9: Malware, vulnerabilities, and threats
** Chapter 10: Social engineering and other foes
** Chapter 11: Security administration
** Chapter 12: Disaster recovery and incident response


* Assessment test (first try)
1 A
2 D
3 
4 A x
5 
6 B?
7 D x
8 B? x
9 A x
10 B?
11 A 
12 A?
13 
14 D x
15 A
16 
17 C? x
18 D
19 A
20 
21 A
22 B
23 A
24 C
25 
26 
27 C x
28 C
29 
30 A
Score: 50%

* Assessment test (second try)
