Time-stamp: <2014-12-04 17:07:01 (bmiller)>
#+STARTUP: content

* Security+ SY0-401
** Chapter 1: Measuring and weighing risk
*** risk assessment
A process conducted in which threats, vulnerabilities, and impacts of a loss
are assessed.  Determines which risks are real/likely.  Coordination with the
Business Impact Analysis (BIA) determines course of action.
**** computing risk assessment
Prioritize and determine which risks are acceptable.  NIST provides a guide
for conducting assessments.
***** risk calculations
Risk impact terms:
- ALE: Annual Loss Expectancy.  A monetary measure of loss, every year.
- SLE: Single Loss Expectancy.  A monetary measure of loss for one event.  This
  is divided into AV (asset value) and EF (exposure factor).  SLE = AV * EF.
- ARO: Annualized Rate of Occurance.  Chance of an event occurring within a
  year, based on historical data.

Formula: SLE * ARO = ALE
***** quantitative vs. qualitative risk assessment
Risk assessments are either qualitative (opinion-based and subjective) or
qualitative (cost-based and objective).  If a dollar cost can be assigned,
it's quantitative.
***** additional risk terminology
- Likelihood: A score representing the possibility of threat initiation.  Goes
  from 10-0, with 10 being a certainty that the adversary will initiate a
  threat event.
- Threat vector: The way in which an attacker poses a threat.
- Mean Time Between Failures (MTBF): The measure of the anticipated incidence
  of failure for a system or component.  E.g., if a system's MTBF is 1 year,
  expect to replace it once a year.
- Mean Time to Failure (MTTF): The average time to failure for a
  non-repairable system.  Same as MTBF, but for non-repairable systems.
- Mean Time to Restore (MTTR): How long it takes to repair a system once a
  failure occurs.
- Recovery Time Objective (RTO): The maximum amount of downtime considered
  acceptable.  Agreed upon during BIA creation.
- Recovery Point Objective (RPO): The point in time from which the system needs
  to be restored.  The shorter the RPO time, the more expensive.
- Service Level Agreement (SLA): Formally defines service provided.
**** acting on your risk assessment
- Risk Avoidance: Identifying a risk and deciding not to engage in actions
  associated with it.
- Risk Transference: Sharing some of the burden of the risk with another
  entity (e.g. using insurance).
- Risk Mitigation: Taking steps to reduce a risk.  E.g., Data Loss Prevention
  (DLP) systems monitor the content of systems ensure key content is not
  deleted/removed.
- Risk Deterrence: Warning the adversary about consequences, like posting
  prosecution policies or warning of intrusion detection.
- Risk Acceptance: The choice to make when the cost of implementing the other
  choices outweighs the harm of an identified risk.
**** risks associated with cloud computing
Cloud computing implementations:
- PaaS: Vendors allow apps to be created and run on their infrastructure.
  E.g., AWS and Google Code.
- SaaS: Applications are remotely run over the Web.
- IaaS: Virtualized resources, billed by resource usage.

Risk-related issues:
- Regulatory compliance
- User privileges: Enforcing least privileges, reduced control.
- Data integration/segregation: Shared resources up data
  encryption/segregation requirements.
**** risks associated with virtualization
- Breaking out of the VM: Data access issues.
- Network and security controls can intermingle: Granularity differences
  between network and VM admin tools.
- Most attacks occur through the hypervisor, giving attackers root-level
  access to all VMs.
*** developing policies, standards, and guidelines
Policies provide high-level guidance, standards provide expectations, and
guidelines provide specific advice.
**** implementing policies
- Scope Statement: Outlines what the policy intends to accomplish and which
  documents, laws, and practices it addresses.  Usually a single sentence.
- Policy Overview Statement: Provides the goal of the policy, its importance,
  and how to comply.  Usually a single paragraph.
- Policy Statement: The substance of the policy.  E.g., how to lock up the
  building at night.
- Accountability Statement: Who is responsible for ensuring the policy is
  enforced.
- Exception Statement: Guidance on how to deviate from the policy and an
  escalation contact.
**** incorporating standards
Standards are derived from policies.  Provides enough detail that an audit can
be performed.

Key aspects of standards documents:
- Scope and Purpose: Explains/describes the intention.
- Roles and Responsibilities: Who is responsible for implementing, monitoring,
  and maintaining the standard.
- Reference Documents: Explains how the standard relates to the organization's
  policies, thereby connecting them.
- Performance Criteria: Outlines how to accomplish the task, including a
  relevant baseline and tech standards.
- Maintenance and Administrative Requirements: E.g., frequency of lock
  combination changes.
**** following guidelines
Helps users comply with standards, often step-by-step processes to accomplish
tasks.

Contents of guidelines documents:
- Scope and Purpose: Overview of the guideline's intent.
- Roles and Responsibilities: Who is responsible for accomplishing tasks.
- Guideline Statements: Step-by-step instructions.
- Operational Considerations: Specify what duties are required and at what
  intervals.
**** business policies to implement
Primary areas of concern:
- Separation of Duties Policies: Designed to reduce risk of fraud and prevent
  other losses.  May require more than one person to accomplish key
  processes.
- Privacy Policies: Define what controls are required to maintain data
  privacy.  A legal document informed by laws.
- Acceptable Use Policies (AUPs): Describe how employees can use company
  systems and resources, including consequences for misuse.  Also known as a
  Use Policy.
- Security Policies: Define what controls are required for security.
- Mandatory Vacations: Addresses dependence upon single persons and an
  opportunity to discover fraud.
- Job Rotation: Same motivation as mandatory vacations, with an emphasis on
  redundancy in skills.
- Least Privilege: Users are given only the permissions needed to perform work.
- Succession Planning: Outlines internal persons that have the ability to step
  into positions when they open up.  Identifies key roles.
**** understanding control types and false positives/negatives
Once risks are identified, controls are put in place to address them.
Controls fall into three groups:
- Management: Risk assessment; planning; system and services acquisition;
  certification, accreditation, and security assessment.
- Operational: Personnel security, physical and environmental protection,
  contingency planning, configuration management, maintenance, system and
  information integrity, media protection, incident response, awareness and
  training.
- Technical: Identification and authentication, access control, audit and
  accountability, system and communication protection.

Once controls are implemented, audits should be performed.  While doing so,
pay attention to:
- False positives: Events flagged as anomalies that aren't really incidents.
- False negatives: Lack of alert on an real event.
**** risk management best practices
Implemented with a BIA.  What is shown in industry to produce superior results
regarding business continuity.
***** undertaking business impact analysis (BIA)
BIA is the process of evaluating critical systems to define impact and
recovery plans.  Focuses on impact a loss would have.

Key components:
- Identifying Critical Functions: Defines essential functions until restoration
  of full service.  Ensures Business Continuity Planning (BCP).
- Prioritizing Critical Business Functions: Categorizes essential/non-essential
  functions.  Useful allocating resources during recovery.
- Calculating a Timeframe for Critical Systems Loss: Evaluates maximum time a
  particular function can be unavailable.  Dictates contingencies to minimize
  loss when time is exceeded.
- Estimating the Tangible and Intangible Impact on the Organization: Details
  tangible (loss production/sales) and intangible (loss customer confidence)
  impact.
***** identifying critical systems and components
Build systems that don't have a Single Point of Failure (SPOF) by adding
redundancy.  Factor weather, natural disaster, and utilities into contingency
plans.
***** high availability (HA)
Measures used to keep services operational during an outage.  The goal is to
have 99.999% availability (five nines).
***** redundancy
Systems either duplicated or fail over to other systems.  Failover is the
process reconstructing a system or switching to another when failure is
detected.  In networks, this involves failover network paths.  Includes
clustering (load balancing).
***** fault tolerance
The ability of a system to sustain operation in event of component failure.
Stock spare parts and ensure power.  For parts, having N+1 is a common
strategy, where N is the number of parts in use.  For power, use UPSes with
surge protection or a backup generator.
***** RAID
- RAID 0: Disk striping.
- RAID 1: Disk mirroring.  Can alternatively be disk duplexing, which uses one
  more controller card (writing to both disks simultaneously).
- RAID 3: Disk striping with a parity disk.  Uses RAID 0 striping, but adds
  another disk for parity info.  Common in older systems.
- RAID 5: Disk striping with parity, spread across multiple disks.  Supports
  3-32 disks.  Can survive failure of only one drive.
**** disaster recovery
Recovering system operations after a disaster.  Planning includes designing a
comprehensive backup plan of backup storage, procedures, and maintenance.
Prioritize critical systems.
***** types of backups
Include both paper and computer records.
***** disaster recovery planning
Keep backups of key data, databases, applications, and paper records.
**** tabletop exercise
A method of accessing risk where a facilitator and participants discuss
possible situations and how to respond.
*** review questions
1 C
2 A
3 D
4 A
5 B
6 D (B)
7 A
8 D
9 B (C)
10 E
11 C
12 D
13 D
14 C
15 B
16 C
17 C
18 A
19 C
20 A
*** additional notes
- Change management: A structured approach to securing a company's assets.
** Chapter 2: Monitoring and diagnosing networks
*** monitoring networks
**** network monitors
- Sniffers: Another name for network monitors.  Enables examining the
  signaling and traffic that occurs on a network.
- Promiscuous mode: A NIC looking at any packet it sees on the network, even
  if the packet is not addressed to that NIC.
***** monitoring system logs
Event logs: System logs that record various events that occur.  Includes many
types of logs, but security and access logs are most pertinent here.

For Windows, the two most important event logs are:
- Application Log: Contains events logged by programs, including errors.
  E.g., SQL Server uses this and the log can show DB compromise attempts.
- Security Log: Shows successful/unsuccessful login attempts and resource use
  (e.g. creating, opening, deleting files and other objects).  Event types to
  log can be specified.  Should always be changed to log both successful and
  failed login attempts.

In Linux, note:
- /var/log/faillog: Logs failed user logins.
- /var/log/apport.log: Logs application crashes.  Can sometimes reveal system
  compromise attempts or the presence of virii/spyware.
*** hardening
Hardening means to lock down and secure an OS as much as practical.  Ensure
unneeded services are turned off, unneeded software is uninstalled, patches are
updated, user accounts are checked, etc.
**** working with services
Part of OS hardening involves disable unnecessary services.

Tips:
- File and Print Servers: Primarily vulnerable to DoS.  Ensure only needed
  protocols are run.
- Networks with PC-Based Systems: Disable NetBIOS on servers or provide an
  effective firewall between them and the internet.  NetBIOS ports are 135,
  137, 138, and 139.  On Unix systems, close port 111 (RPC).
- Directory Sharing: Limit to what is essential for system functions.  Hide
  root directories from browsing -- instead, designate subfolders.
***** protecting management interfaces and applications
Admin interfaces should be restricted to only those admins who need it.
Protect server utilities and even workstation utilities like regedit.  Password
protect management functionality and consoles.

On Windows, use the Performance Monitor to look for possible illicit activity,
as it can do things like show excessive processor usage.
***** software
Remove unneeded software.  On Windows, remove Windows components that commonly
come preinstalled (via Programs and Features).
**** patches
A patch is an update to a system, adding new functionality or correcting bugs.
In a network environment, patches should be applied to a single machine and
tested first, as it's possible that patches could have problems.  In such
cases, not applying it is an option until a fix can be found.

Types of patches:
- Service pack: A periodic update that corrects problems in one version of a
  product.  Gets users to the current codebase for the product.
- Updates: Code fixes provided to individual customers experiencing critical
  problems that have no feasible workarounds.
- Security updates: Address security vulnerabilities.  Should be considered
  mandatory.  Should be deployed within 30 days of release.
**** user account control
Only active accounts should be operational and properly managed.  Along with
domain accounts, pay attention local accounts.  A common approach is to
configure a single machine, image it, then copy to other workstations.  This
can result in issues propagating throughout a network.

Tips:
- Disable unneeded accounts.  These can provide attack vectors.
- Accounts must have passwords that meet standards.  These should apply to
  domain and local accounts.
- Apply least privileges.

Disable these accounts:
- Employees who have left the company: Should be disabled the minute an
  employee is terminated, regardless of termination type.  Disable instead of
  delete accounts.
- Temporary employees: Also disable immediately.
- Default guest accounts: Commonly known to exist.
**** filesystems
Windows:
- MS FAT: Designed for small drives.  FAT-16 preceded FAT-32.  Only allows
  share-level and user-level access privileges.  If a user has write or change
  access to a directory, they have access to any file in the directory.
  Highly insecure.
- MS NTFS (New Technology FS): Introduced in Windows NT.  Addresses growing
  disk sizes, security concerns, and file stability.  Unlike FAT, includes
  transaction-tracking, which allows backing out any disk operation in
  progress when the OS crashes or loses power.  Files, directories, and
  volumes each have their own security.  Tracks security in ACLs.

Windows systems have hidden admin shares with names ending in dollar signs
(e.g., admin$) for remote administration.

Not covered: ext3, ext4, XFS on Linux; HFS, HFS+ on OSX.
*** securing the network
- MAC limiting and filtering: Limit network access to known MAC addresses.
  Most routers have this option.  Find MAC address using ipconfig /all or
  ifconfig/ip command.  Not foolproof as MAC addresses can be changed.
- 802.1X: Add port authentication to MAC filtering secures on a switch port
  level, vastly increasing security.  802.1X defines port-based security for
  wireless network access control.  802.1X offers authentication and defines
  the Extensible Authentication Protocol (EAP) over IEEE 802.  This is EAP
  over LAN (EAPOL).  Authentication relies on authentication servers instead
  of access points and switches doing it themselves.
- Disable unused ports: Disable the service and block the port with a firewall.
- Rogue machine detection: Scan for these.
*** security posture
Document a baseline configuration, representing a known secure state.
Reporting will be relative to this state.  The baseline also addresses specific
compliance issues and regulatory standards.  Include network utilization stats,
useful in identifying DoS attacks.
**** continuous security monitoring
Ongoing monitoring involving network traffic levels, routine evaluations for
regulatory compliance, and checks of network security device configurations.
**** security audits
Scheduled, in-depth checks of security.  Includes:
- Review of security logs.
- Review of policies and compliance with policies.
- A check of security device configuration.
- Review of incident response reports.

Scope and frequency are determined by the organization, subject to
needs/budget.
**** setting a remediation policy
Monitoring may uncover gaps between the baseline and current network state.  A
remediation plan must be implemented.  A possible classification of gaps:
- Minor: Does not pose an immediate threat.
- Serious: Could pose an  immediate threat, but one unlikely.
- Critical: Poses an immediate threat that must be addressed.
*** reporting security issues
**** alarms
Indications of an ongoing current problem requiring immediate response.  Alarm
rates may indicate trends.  After solving the problem, look for indicators that
the condition is not isolated.  A notification system should notify appropriate
staff.  That staff needs a procedure to report incident specifics and how it
was addressed.
**** alerts
Issues requiring attention but not likely to bring down the system.  Alerts
can refer to Event Viewer events, or AV industry and OS alerts.
**** trends
Trends in threats, like if a type of attack is currently common.  Also can
refer to organizational security profile trends.  E.g., audits finding
increased policy compliance or increased violation of software installation
policies.  Allow the taking of proactive security measures.
*** differentiating between detection controls and prevention controls
Some controls exist to detect potential threats, others to prevent/minimize
them.  An intrusion detection system (IDS) detects, an intrusion prevention
system (IPS) prevents.  H-IDS is host based, N-IDS is network based.

Honeypot: A tool that is part detection and prevention.  Honeypots allow
themselves to be attacked to gain information of methods used in the attack.
Draws attackers away from high-value systems and provides attack strategy
intelligence.  If not configured properly, can be used to launch further
attacks.  Concepts to consider for honeypots/honeynets:
- Enticement: Luring someone into a plan/trap via invitation.
- Entrapment: Encouraging/inducing potential criminal activity when a desire
  is expressed not to go ahead.  Not legally acceptable.

Tar pit: Exists only to slow down attackers and does not collect data.
*** review questions
1 C
2 B
3 C
4 A
5 A
6 A
7 B
8 B
9 A
10 B
11 C
12 D
13 C
14 A
15 B
16 D
17 C
18 A
19 A
20 B
*** additional notes
Administrator: IDS person responsible for setting security posture.
** Chapter 3: Understanding devices and infrastructure
Intrastructure, network ports, and common protocols. A network is composed of
media and devices.
*** mastering TCP/IP
Has numerous holes which are easy to plug once aware of their existence.
**** OSI relevance
OSI model is 7-layer.  TCP/IP precedes OSI and uses 4 layers and is used here.
**** working with the TCP/IP suite
Layers:
- Application layer: E.g., HTTP, SMTP.
- Host-to-Host, or Transport layer: TCP or UDP (user datagram protocol).
- Internet layer: IP.
- Network Access, Network Interface, or Link layer: Network topology
  (essential for conveying information on a network).  Includes "media".

TCP/IP uses existing physical connections between systems, ignoring network
topology (which network controllers handle).

Concepts:
- Host: Any device connected to the network that runs the TCP/IP stack
  (protocol suite).
- Encapsulation: The process used to pass messages between layers.
***** the application layer
Highest layer.  Allows applications to access services or protocols to exchange
data.  Common protocols:
- HTTP
- HTTP Secure (HTTPS): Combines HTTP with SSL/TLS to provide encrypted
  communication.
  - SSL: Establishes a secure connection between two TCP-based machines.  Uses
    the handshake method of session establishment.  Maintains a session using
    symmetric encryption.
  - TLS: A security protocol that expands upon SSL.  May replace SSL and is
    already referred to as SSL 3.1, though doesn't interoperate with SSL.
- FTP: Allows connections to FTP servers for file uploads/downloadds.  Uses
  ports 20 and 21.  Inherently insecure.  FTP over SSL (FTPS) adds support for
  SSL cryptography.  There's also SSH FTP (SFTP), also known as Secure FTP.
  An alternative to FTP is SCP, using port 22.  This combines the remote copy
  program (RCP) with SSH.  Finally, there's Trivial FTP (TFTP), which allows
  file transfer without any user interaction.  TFTP should be avoided anywhere
  other options exist.
- SMTP: Email delivery.  Port 25.
- Telnet
- DNS: Allows resolving of hostnames to IPs.  Port 53.
- RDP: Allows Windows-based terminal servers.  Port 3389.
- SNMP: Simple Network Management Protocol.  Allows communication between
  network devices and a management console.  Used by routers, bridges, and
  intelligent hubs.
- POP3: Post Office Protocol, version 3.  Receiving email.  Port 110.  Often
  now replaced by IMAP on port 143.  POP was created to move email to clients
  and not keep it on the server, whereas IMAP stores email on the server for
  access.  Now, POP can now be configured to store on the server and IMAP to
  store only locally.
***** the host-to-host or transport layer
Session and datagram communications.
- TCP: Provides reliable, one-to-one, connection-oriented sessions.
  Establishes sessions and ensures packet reception.  Ensures packets are
  decoded and sequenced properly.  The connection persists during the only
  session.
- UDP: Provides unreliable, connectionless communication between hosts.  Faster
  than TCP.  No session synchronization.  Doesn't guarantee error-free
  communication.  Mainly used to send small packets of info.  The application
  is responsible for acknowledging correct reception of data.
***** the internet layer
Responsible for routing, IP addressing, and packaging.  Does most of the work
in establishing info exchange between hosts.  Four standard layer protocols:
- IP: Routable protocol responsible for IP addressing.  Fragments and
  reassembles message packets.  Only routes information, doesn't verify for
  accuracy (which is the domain of TCP).  Determines if a destination is known
  and, if so, routes info to it.  If destination is unknown, IP sends the
  packet to the router.
- Address Resolution Protocol (ARP): Resolves IP addresses into Network
  Interface layer addresses, including hardware addresses.  Resolves IPs to MAC
  addresses.
- Internet Control Message Protocol (ICMP): Provides maintenance and reporting
  functions.  Used by ping.  ICMP responds to ping requests or locally reports
  if the destination is unreachable.  Routers and other network devices use
  ICMP to report path info.
***** the network access layer
Responsible for placing and removing packets on the physical network via
communicating with the host's network adapters. When network topology or
technology is changed, TCP/IP only needs to know how to communicate with the
new network controller.  Can also communicate with multiple network topologies.
**** IPv4 and IPv6
IPv4: 32-bit addresses, IPv6: 128-bit addresses.  IPv6 includes mandatory
IPSec security.  Most systems support both.
**** understanding encapsulation
Encapsulation allows a transport protocol to be sent across the network and
used by the equivalent protocol/service at the destination.  Allows higher
level protocols not to care what happens at lower levels.
**** working with protocols and services
Ports, handshakes, and application interfaces.

Note: NetBIOS was originally an alternative to TCP/IP, but has since been
adapted to run on top of it.  It's widely used for name resolution and
registration in Windows-based environments.
***** well-known ports
Ports identify how a communication process occurs.  Ports are special addresses
that allow communication between hosts.  The Internet Assigned Numbers
Authority (IANA) defines a list of well-known ports.

Port numbers are additional info added to TCP or UDP message headers.

TCP ports:
- 20 FTP (data channel)
- 21* FTP (control channel)
- 22* SSH and SCP
- 23 Telnet
- 25* SMTP
- 49 TACACS authentication service
- 80* HTTP
- 110* POP3
- 115 SFTP
- 119 NNTP
- 137 NetBIOS name service
- 138 NetBIOS datagram service
- 139* NetBIOS session
- 143* IMAP
- 389 LDAP
- 443* HTTPS
- 989 FTPS (data channel)
- 990 FTPS (control channel)
- 3389 MS WBT Server (RDP)

UDP ports:
- 22* SSH and SCP
- 49 TACACS authentication service
- 53* DNS
- 69 TFTP
- 80* HTTP
- 137 NetBIOS name service
- 138 NetBIOS datagram service
- 139* NetBIOS session
- 143* IMAP
- 161 SNMP
- 389 LDAP
- 989 FTPS (data channel)
- 990 FTPS (control channel)
- 3389 MS WBT Server (RDP)
***** viewing the active TCP and UDP ports
- Windows: netstat lists local port -> foreign address.  netstat -a provides
  full listings.
- services file: A reference for common services/ports.
***** TCP three-way handshake
TCP is a connection-oriented protocol which establishes a session using a
three-way handshake:
- SYN: The client originates the connection, sending a TCP segment/message to
  the server.  This segment includes an initial sequence number (ISN) for the
  connection and a window size.
- SYN/ACK: The server responds with a TCP segment that contains its ISN and a
  value for its buffer/window size.
- ACK: The client sends back and acknowledgement of the server's sequence
  number.

A four-step process is used to close the connection.  The sequence numbers are
used so the server can handle simultaneous requests on the same port.  All
communication in a session uses the same sequence number.
***** application programming interface
Here refers to the APIs used by programmers to create interfaces to TCP/IP.

MS uses the Windows Socket (Winsock) API to interface TCP/IP.
***** other protocols to know
- iSCSI (Internet Small Computer Systems Interface): Uses port 860 and 3260.
  Allows data storage and transfers across the network.  Enables the creation
  of storage area networks (SANs).
- Fibre Channel: Same as iSCSI, but designed for only fibre-based networks.
  Later changed to use SCSI to create SANs.  A common protocol used is FCoE
  (Fibre Channel over Ethernet), which is not routable at the IP layer, and is
  only useful in small networks.
*** designing a secure network
Consider these when designing the security topology of a network:
- Demilitarized zones (DMZs).
- Subnetting.
- VLANs.
- Remote access.
- NAT.
- Telephony.
- NACs.
**** demilitarized zones
An area to place public servers accessible to people otherwise not trusted.
Doesn't allow access to other parts of the network.  Can be built/demarcated
using firewalls that can transmit in three directions:
- To the internal network.
- To the external internet.
- To the public information (DMZ).

If a web server was on a DMZ, the firewall would direct HTTP traffic there,
whereas email would go to the internal network.

Bastion hosts: Hosts, routers, and firewalls that exist outside the DMZ and
open to the public.
**** subnetting
Subnetting: Using a subnet mask to divide a network into smaller components.
These can be divided physically, logically, topologically, etc.

Subnetting uses bits from the host address to create the additional networks.
This can:
- Use IP addresses more effectively.
- Make the network more secure and manageable.

Subnets increase security by confining traffic to the network it needs to be
on, reducing network traffic and creating more broadcast domains (reducing
network-wide broadcast traffic).
**** virtual local area networks (VLANs)
A VLAN allows creation of groups of users and systems, segmenting them on the
network.  Allows hiding of other segments and controlling access.  VLANs can
be set up to control the path data takes.  A good way to contain network
traffic to a certain area.

Can also be thought of as a network of hosts that act as if a physical wire
connects them, even though it doesn't exist.

VLANs reduce the number of broadcast domains by reducing their scope, improving
performance and manageability, and decreasing dependence on topology.  Most
importantly, it allows users with similar data sensitivity to be segmented
together.

Tunneling protocols: Adds the ability to create tunnels between networks that
can be more secure, support additional protocols, and provide virtual paths.
Can use encapsulation in other packets to be sent across a public network.

Types of tunneling:
- Point-to-Point Tunneling Protocol (PPTP): Supports encapsulation of PPP
  (point-to-point protocol) packets in a single point-to-point environment.  A
  low-end protocol.  Negotiation between hosts done is done in the clear, after
  which the channel is encrypted.  This is its major weakness.  A
  packet-capture device, like a sniffer, can capture the negotiation process
  and determine connection type and how the tunnel works.  MS created and uses
  PPTP.  Uses port 1723 on TCP.
- Layer 2 Tunneling Protocol (L2TP): Combined MS (PPTP) and Cisco (L2F)
  tunneling protocols.  Primarily point-to-point.  Supports multiple network
  protocols and can be used outside of TCP/IP.  Works over IPX, SNA, and IP,
  and can therefore act as a bridge between systems.  Its main problem is lack
  of data encryption, but this can be provided by IPSec.  Uses port 1701 on
  UDP.
- Secure Shell (SSH): Uses encryption to establish a connection.  Alternative
  to Telnet, FTP, and other clear-text programs.  Uses port 22 on TCP.
- Internet Protocol Security (IPSec): Not a tunneling protocol, but used in
  conjunction with them.  Mainly for LAN-to-LAN connections, but also used with
  dial-up.  Provides secure authentication and encryption of data and headers,
  making it highly secure.  Can work in:
  - Tunneling mode: Data or payload and headers are encrypted.
  - Transport mode: Only payload is encrypted.
**** remote access
Tunnels create virtual connections between two systems/networks.  Data is
encapsulated in an mutually agreed protocol.  Data passed through tunnels
appears on the other side as part of the network.

Remote Access Servers (RAS): Any server service that offers the ability to
connect remote systems.  On Windows this is Routing and Remote Access (RRAS).
Connections are accomplished via dial-up/plain-old telephone services (POTS),
VPNs, ISDN, DSL, and cable modems.  RAS connections can be secure or not.
Virtual Network Computing (VNC) provides things like remote control of
computers, but has leaves a discoverable opening.  Should be configured as a
"manual start" service.
**** network address translation (NAT)
NAT originally extended the number of usable IP addresses, but now allows
organizations to present a single IP address to the Internet for all
connections.  The NAT server provides IPs to the hosts in the network and
tracks inbound/outbound traffic.

NAT presents a limited number of connections to the network through a router
or NAT server.  Intruders will only know a single address.  The rest of the
network is hidden from the outside and acts as a firewall.  Most routers
support NAT.

Non-routable, private address ranges assigned by most NATs for internal use:
- 10.0.0.0 - 10.255.255.255.
- 172.16.0.0 - 172.31.255.255.
- 192.168.0.0 - 192.168.255.255.

Note: Port Address Translation (PAT) is also possible.  NAT can use multiple
public IP addresses, whereas PAT can only use one.  PAT is usually only used on
small, private networks.  MS's ICS is a PAT implementation.  Also, Destination
NAT (DNAT) can be used to redirect traffic for a virtual host to a real one.
**** telephony
Telephony is the merger of IT and telephone systems.  Breaches here are just
as serious as any other.

Voice over IP (VoIP) can be sniffed and is susceptible to DoS attacks since it
uses UDP.  If a data network goes down, telephony can be lost.
**** network access control (NAC)
Operational security includes NAC, authentication, and security topologies.

NAC is a set of standards defined by the network for clients attempting access.
NAC typically requires clients be virus-free and adhere to certain policies.
*** understanding the various network infrastructure devices
Components encountered in a network.

Note: For network devices requiring default accounts to change settings, be
sure to change passwords.
**** firewalls
Firewalls isolate one network from another.

The first line of network defense.  Can be standalone systems/included in
routers or servers or hardware-only/software-only.  Many firewalls are add-in
software for servers/workstations.

Appliances: Some firewalls are appliances.  Intended to be the primary device
separating two networks.  These are freestanding, self-contained devices,
requiring less maintenance.

Firewall functions include one or more of:
- Packet filter.
- Proxy firewall.
- Stateful packet inspection firewall.
***** packet filter firewalls
Passes or blocks traffic to specific addresses based on the type of
application.  Doesn't analyze the data, only uses addressing info.  E.g., allow
port 80, block port 23.  Included in most routers.  Some allow specifying which
IPs can request which ports.
***** proxy firewalls
An intermediary between outside/inside the network.  Examines data and makes
rule-based decisions about whether to forward/refuse requests.  Intercepts all
packets and reprocesses them for internal use, including the hiding of IPs.

Provides better security than packet filtering due to increased intelligence.
All internal requests are routed through the proxy, isolating users from the
external network.  Can also provide caching to increase efficiency.

Proxy firewalls typically use two NICs, in which case it's called a dual-homed
firewall.  One NIC is connected internally, the other externally.

Note: IP forwarding bypasses firewalls and uses the firewall as a router.
Probably don't want that on proxies.

Proxies can function at either:
- Application-level: Reads commands of protocols.  E.g., knowing about GET and
  PUT requests and having rules in regards to them.  An application-level proxy
  is needed for each protocol supported.  Many provide full auditing,
  accounting, etc.
- Circuit-level: Doesn't deal with the contents of packets processed.
***** stateful packet inspection firewalls
Stateless firewalls make decisions based on the data that comes in (the current
packet), and not complex decisions.  Stateful packet inspection (SPI) filtering
keeps records for every communication channel and what the next should be.

Stateful inspection occurs at all levels of the network and provided added
security, especially for UDP and ICMP.  DoS attacks can overload the state
table and cause firewalls to shut down/reboot.
**** routers
Primary device for connectivity between two or more networks.  Provides a path
between networks and joins networks.  Most routers can act as packet-filtering
firewalls.

Border routers: In conjunction with Channel Service Unit/Data Service Unit
(CSU/DSU), routers can translate from LAN framing to WAN framing (e.g. a router
connecting 100bT and T1 networks).  Needed due to LANs/WANs having different
protocols.

Zones: Router-divided subnetworks.

Routers maintain tables of destinations and local connections.  Contains info
about systems connected and where to forward requests for unknown destinations.
These tables grow as connections are made.

Protocols routers use for communication routing and other info:
- Routing Information Protocol (RIP).
- Border Gateway Protocol (BGP).
- Open Shortest Path First (OSPF).

Best practice is for a router to augment the defense of a firewall.

Routers can be configured statically (manually) or dynamically (where they
learn of other routers and use their info to build routing tables).
**** switches
Multiport devices that improve network efficiency.  Switches contain small
amounts of info, usually only a table of MAC addresses.  Using virtual
circuits, they improve network efficiency.  Virtual circuits are more difficult
to examine with network monitors.  Combines some of the best features of
routers and hubs.

Only use switches internally because they only use MAC addresses and not IPs.
Routing can only occurs on IPs.
**** load balancers
Load balancing is shifting a load between devices.  Can apply to servers, HDs,
CPUs, etc.  This provides:
- Reduced response time.
- Maximizes throughput.
- Allows better resource allocation.

Can be software or hardware.
**** proxies
A device that acts on behalf of another.  All internal user interaction with
the internet should be controlled through a proxy server.  Proxies should
auto-block known bad sites.  Caching should be enabled.
**** web security gateway
A proxy server (proxies and caches) with web protection software built-in.
Can include a virus scanner and traffic monitors.  Can detect/prohibit certain
content, P2P connections, IM, tunneling, HTTP/HTML exploits, ActiveX, etc.
**** VPNs and VPN concentrators
VPN: A private network connection that occurs through a public network,
providing security over insecure environments.  Can connect LANs across the
internet.  Requires special hardware/software.  VPNs usually use L2TP, IPSec,
PPTP.  Great for extra/intranets for remote offices.

Main concern is encryption.  PPTP: weak encryption, IPSec: higher security.

VPN concentrator: A hardware device used to create remote access VPNs.  It
creates encrypted tunnel sessions between hosts, most using two-factor
authentication.  Cisco concentrators include Scalable Encryption Processing
(SEP) for hardware encryption.
**** intrusion detection systems (IDS)
Software that runs either on workstations or network devices to track network
activity.  Can evaluate system logs, monitor network activity, and disconnect
sessions in violation of security.  Some IDSs come with firewalls.  Recommend
combining with a firewall, as if firewall defenses are bypassed, the IDS
introduces reactive countermeasures.
**** understanding intrusion detection systems
Intrusion detection (ID) is the process of monitoring events in a system or
network to detect an occurring intrusion.  An intrusion is any activity that
attempts to undermine or compromise the confidentiality, integrity, or
availability of resources.

Terms:
- Activity: An element of a data source of interest to the operator.
- Administrator: Person responsible for setting the security policy, deploys
  and configures the IDS, determines appropriate responses to attacks, and
  determines alarm levels, historical logging, and session-monitoring
  capabilities.
- Alert: A message from the analyzer indicating an event of interest, like
  with exceeded traffic thresholds.
- Analyzer: Component or process that analyzes data collected by the sensor.
- Data source: Raw info that the IDS uses, like audit files, system logs,
  network traffic, etc.
- Event: An occurrence in a data source that indicates suspicious activity.
  Events might trigger alerts.
- Manager: Component or process that operator uses to manage the IDS, like an
  IDS console.  Used for config changes.
- Notification: Process or method by which the manager makes the operator
  aware of the alert.
- Operator: Person responsible for the IDS.
- Sensor: IDS component that collects data from a data source and passes it to
  the analyzer.

IDSs use four main approaches:
- Behavior-Based-Detection IDS: Looks for deviations in behavior such as
  unusually-high traffic, policy violations, etc.
- Signature-Based-Detection IDS: Also called a misuse-detection IDS (MD-IDS).
  Primarily focused on detecting based on attack signatures (established
  methods of attack) and audit trails.  Uses a database of misuse and attack
  signatures.  E.g., if the MD-IDS knows what a TCP flood looks like, it can
  respond or report appropriately.
- Anomaly-Detection IDS (AD-IDS): Looks for anomalies, usually using a training
  program to learn normal operation and then spot deviations from that, or by
  being manually assigned baseline values.
- Heuristic IDS: Uses algorithms to analyze network traffic.  Require more
  fine tuning to prevent false positives.

In order for reporting to be effective, a baseline of typical network traffic
should be developed.

AD-IDSs use AI and expert systems.

IDSs detect and report unusual occurrences, but unlike firewalls, don't block.
**** IDS vs. IPS
An IPS is an IDS that reacts to detected intrusion, usually by blocking
communication from an offending IP.  The main problem here is false positives.
**** working with a Network-based IDS (NIDS)
NIDS attaches to some point in a network, and reports on/monitors network
traffic.  Can be in front or behind a firewall.  A dual-security approach is
to place NIDSs in both locations.

In front of a firewall, the NIDS can monitor traffic going to the network and
give data on attacks the firewall is blocking.

NIDS can attach to a switch, hub, or tap.  Some switches and hubs have
monitoring ports which are effectively taps.  The advantage of a tap is the
IDS is the only device using it.

Port spanning/port mirroring: Copies all traffic from all ports to a single
port and disallows bidirectional traffic on that port.

Two types of responses: passive and active.
***** implementing a passive response
Cannot react to an incident.

Passive strategies:
- Logging: Recording events and their circumstances.  Info then used to devise
  a counter to threats.
- Notification: Notify event-related info the appropriate personnel.  For
  manned IDSs, messages can appear on the manager's console.
- Shunning: Ignoring an attack.  Useful for attacks that are inapplicable
  (e.g. IIS attacks on Apache).
***** implementing a active response
Involve taking action based on an attack/threat.  The goal is taking the
quickest possible reaction to reduce impact.  More costly than passive.

Active reactions:
- Terminating processes or sessions: E.g., in a TCP flood attack, the IDS can
  cause TCP to force resets (RST) to all current sessions.
- Network configuration changes: E.g., if an IP is an attack source, the IDS
  can instruct the border router or firewall to reject traffic from it.  If a
  socket or port is attacked, it can tell the firewall to block it for a
  length of time.
- Deception: Fools an attacker into thinking an attack is succeeding, while
  monitoring and possibly redirecting to a honeypot.
**** working with a Host-based IDS (HIDS)
Software run on a host, usually a service or background process.  Examines
logs, events, and applications, but usually skips network traffic.  Popular on
servers already using encrypted channels.  Typically are passive.

Problems:
- If a system's compromised, logs are unreliable.
- Must be deployed to each system, adding administrative load.

Benefits:
- Can keep checksums on files to detect alteration.
- Can read memory.
**** working with NIPSs
Network intrustion prevention systems focus on prevention.  Also detects,
therefor is a subset of NIDS.  Focuses on signature matches and takes action.

Can also be called intrusion detection and prevention systems (IDPS).
**** logs to check in Linux
- /var/log/faillog: Failed authentication attempts.
- /var/log/lastlog: List of uses and when they logged in.
- /var/log/messages: Use grep to find login-related info.
- /var/log/wtmp: Used by last command.
**** protocol analyzers
Protocol analyzers = packet sniffers.  Monitor data transmitted across a
network.  Software called an analyzer or sniffer.  Snort is an example of an
analyzer.
**** spam filters
Catches unwanted email and filters it before delivery.  Uses rules, such as
sender IP lists, subject word scanning, etc.  Can also be used for outgoing
mail to catch infected internal computers.
**** UTM security appliances
Unified Threat Management (UTM), or Next Generation Firewall (NGFW), is an
all-in-one appliance.  Combines firewalls with things like intrusion
prevention, antivirus, filtering, etc.

Advantages include reduced learning curve, single vendor, and reduced
complexity.  Disadvantages include single point of failure and single vendor
dependence.
***** URL filters
Block websites based on URL.  IE8's SmartScreen Filter is a URL filter, which
blocks phishing and malware sites.
***** content inspection
Looks at data coming in.  IE includes Content Advisor.
***** malware inspection
Malware detection is useful, but stop it prior to being on systems is better.
***** web application firewall (WAF) vs. network firewall
A WAF is a real-time appliance that applies a set of customizable rules to
block traffic to and from webservers and to try to block attacks.  Protects
against XSS, injection attacks, and forged HTTP requests.

Reacts to both known and suspected problems, making them superior to IPSs.
***** application-aware devices
Has the ability to respond to traffic based on what's there.  These devices
combine SNMP and QoS to prioritize traffic.  Can be added to firewalls, IPSs,
IDSs, and proxies.
*** review questions
1 C
2 A
3 D
4 B
5 B
6 A
7 A
8 D
9 C
10 A
11 B
12 A
13 D
14 C
15 A
16 B,C
17 C
18 A
19 D
20 A
*** additional notes
Socket: A combination of an IP and port.
** Chapter 4: Access control, authentication, and authorization
Controlling access to a system, what resources are accessible, and ensuring
users are who they claim to be.
*** understanding access control basics
Access control: Allowing authorized users to the system and keeping others out.
**** identification vs. authentication
- Identification: Finding out who someone is.  Claiming an identity
- Authentication: A mechanism for verifying that identification.  Proving the
  identity.

Authentication (single or multifactor) systems are based on one or more of:
- Something you know: A password or PIN.
- Something you have: A smart card, token, or ID device.
- Something you are: Fingerprints or retinal scans (biometrics).
- Something you do: An action taken to complete authentication.
- Somewhere you are: Geolocation.  Often not used due to mobile computing.

Systems use similar methods for authentication between each other.

Out-of-band authentication: Getting public record info (such as credit
reports) and querying about info within.
**** authentication (single factor) and authorization
Single-factor authentication (SFA): The most basic form.  Includes user/pass
combination.

Mutual authentication: When two or more parties authenticate each other.
Servers and clients can use this to establish a secure connection and employ
encryption.  Ensures the client isn't connecting to a rogue server.  Used when
data is critical, like finance.
**** multifactor authentication
When two or more authentication methods are used, e.g. user/pass + smart card.
The factors can not be from the same category.  Password+PIN is still SFA.
**** layered security and defense in depth
Synonymous terms, both meaning not relying on a single entity for protection.
**** network access control
Operational security is part of a triad also including physical and management
security.  Operational security includes network access control (NAC),
authentication, and security topologies -- everything not included in design
or physical security.
**** tokens
Security tokens are pieces of data that contain the rights and access
privileges of the token bearer as part of the token.  Similar to certs in that
they are used to identify and authenticate a user.  Some OSes create temp
tokens for every action or for user sessions.
**** federations
A federation is a collection of related (e.g., for an industry association)
computer networks that agree on standards of operation, such as for security.
An example is an IM federation of providers that agree on communication
standards.

Federated identity: Linking a user's identity with their privileges in a manner
usable across business boundaries (e.g. MS Passport, Google Checkout).

Single sign-on: Having one password for all resources on a network.
**** potential authentication and access problems
Transitive access and client-side attacks.
***** transitive access
Involves transition.  A trusts B, B trusts C, then A may trust C.  Problems
here were solved with transitive trusts, which type relationships between
domains.

In AD, the default is two-way transitive trust.  Potentially troublesome due
to someone acquiring undesired access by joining a domain.
**** authentication issues to consider
Consider tech-savviness of people affected by policies, though its better to
educate users than lower security.

Use identity proofing when issues arise between identification and
authentication, e.g. asking for mother's maiden name in event of lost
password.  The problem with these is that they are easily guessed/learned.
Difficult questions or biometrics are better.  Proofing shouldn't grant
immediate access, rather it should send access info to their email account.
**** authentication protocols
- PAP (Password Authentication Protocol): Older system, not used.  Sends
  user/pass in plain text.
- SPAP (Shiva Password Authentication Protocol): Replaced PAP.  Encrypts
  user/pass.
- CHAP (Challenge Handshake Authentication Protocol): Stops man-in-the-middle
  attacks.  During initial auth, the client is asked to generate a random
  number/hash and send it.  The client is then periodically challenged to
  provide the number again.
- TOTP (Time-Based One-Time Password): An algorithm using a time-based factor
  to create unique passwords.
- HOTP (HMAC-Based One-Time Password): An algorithm using a Hash Message
  Authentication Code (HMAC) algorithm.
**** account policy enforcement
Account Policy: Determines security parameters regarding who can/cannot access
the system.

The following subsections are account policy enforcement best practices.
***** password length and complexity
Obtain balance between ease of remembering and cracking difficulty.  Minimums:
8 chars considered length, 1 non-alpha char.

Windows can be set to not require passwords by setting min length 0.  Win
8/7/Vista's Local Security Policy sets password complexity.  Physical access
to Windows machines can allow password retrieval.
***** password expiration
The longer a password is used, the more likely it is to be broken.  90 days is
the standard, MS recommends 42.

Password history: Prevents users from using previous passwords, with
configurable history lengths.  History of 24 passwords is recommended.

Set minimum number of days that can exist between password changes to 2.
***** password recovery
Only a hash is stored usually.  Admins should change it to something else then
have users log in and change it.
***** password disablement and lockout
Accounts should be disabled for employees on temporary leave and permanently
for terminated employees.  For employees coming back as contractors, suspend
accounts so the relative identifiers (RIDs) are reused.

Locking an account usually occurs after repeated failed login attempts,
preventing password guessing:
- Account lockout duration: Accounts can become unlocked after a period of
  time.  Setting to 0 requires an admin to unlock.
- Account lockout threshold: Number of failed login attempts.
- Reset account lockout counter after: Duration between failed login attempts
  that count as a sequence of failures.
**** users with multiple accounts/roles
Educate users with elevated privilege accounts to only use them when
necessary.  Establish policies to this effect.
**** generic account prohibition
A generic account is any account shared by multiple users, including guest
accounts.  Problems include shared passwords and auditing issues.  These
should not be used.
**** group-based and user-assigned privileges
Group privileges include groups and roles.
*** understanding remote access connectivity
Remote authentication is any auth done for a remote user.
**** using the Point-to-Point Protocol
PPP supports multiple protocols and works with POTS, ISDN, T1, etc.  Doesn't
provide data security (no encryption), but does use CHAP auth.

PPP encapsulates traffic in Network Control Protocol (NCP) and authenticates
with Link Control Protocol (LCP).

PPP's insecurity makes it unsuitable for WAN connections.  For direct
connections, risk of phone line taps is small.  PPP connections through a
network should use an encrypted tunnel system.
**** working with tunneling protocols
Tunneling protocols create tunnels between networks that can be more secure,
support added protocols, and provide virtual paths.  Sensitive data is
encapsulated in other packets and sent across a public network.
- PPTP: Supports encapsulation in a point-to-point environment.  Encapsulates
  and encrypts packets.  The channel is encrypted after negotiation occurs,
  though a sniffer can still capture the negotiation process to determine
  connection type and tunnel info.
- Layer 2 Forwarding (L2F): A Cisco-created method of creating tunnels, mainly
  for dial-up.  Similar to PPP and shouldn't be used on WANs.  Provides
  authentication, but no encryption.
- Layer 2 Tunneling Protocol (L2TP): A hybrid of L2F and PPTP.  Primarily a
  point-to-point protocol.  Doesn't provide data security/encryption, but
  IPSec can be used for this.
- Secure Shell (SSH): Uses encryption to establish a secure connection between
  two systems.
- Internet Protocol Security (IPSec): Used in conjunction with tunneling
  protocols.  Primarily for LAN-to-LAN connections, but also remote
  connections.  Provides secure authentication and encryption of data and
  headers.
**** working with RADIUS
Remote Authentication Dial-in User Service (RADIUS), an IETF standard protocol,
allows authentication of remote and other network connections.  Implemented by
most major OSes.  Can be managed centrally.  Servers that allow access to a
network verify with a RADIUS server to perform authentication.

Use RADIUS when you want a single service to authenticate remote users.
Auditing and accounting can occur on the RADIUS server.

The main downside to RADIUS is that remote connectivity can go down if the
single servers malfunctions.  Some RADIUS systems allow multiple servers to
counter this.
**** TACACS/TACACS+/XTACACS
Terminal Access Controller Access-Control System (TACACS) is a
client/server-oriented protocol, similar to RADIUS.  Extended TACAS
(XTACACS) added logging/auditing.  TACACS+ is the current version, and allows
multiple credential methods, like Kerberos.

Both TACACS and RADIUS are centralized remote authentication services.
**** VLAN management
VLANs allow groups of users/systems, segmented on a network.  Hides segments
of networks, controls access, and controls data paths.

For security, VLANs allow grouping of users with similar data sensitivity
levels.
**** SAML
Security Assertion Markup Language (SAML) is an XML variant used for
authentication and authorization data.  Service providers uses SAML to prove
remote user identity.
*** understanding authentication services
Authentication services: The implementation of the authentication
technology. Only need to know about LDAP, Kerberos, and SSO for exam.  LDAP
and Kerberos are protocols, SSO is a property of access control.
**** LDAP
Lightweight Directory Access Protocol (LDAP): A standardized directory access
protocol that allows queries to be made of directories (paired-down X.500-based
directories).  LDAP is used by Active Directory.  Uses port 389.

Secure LDAP (LDAPS): Encrypts all LDAP communication with SSL/TLS over
port 636.
**** Kerberos
An authentication protocol/method, allowing SSO.  Kerberos authentication uses
a key distribution center (KDC), which authenticates the principal (user,
program, or system) and provides it a ticket.  The ticket can then be used to
authenticate against other principals.  The only Kerberos weakness is the KDC
is a single point of failure.

Workflow:
- User authenticates to KDC and is given a ticket granting ticket (TGT), which
  lists privileges of the user.
- User requests a resource on the network from the KDC, presenting the TGT.
  The TGT sends the user a service ticket.
- The user's computer sends the service ticket to the server with the service.
  The server communicates with the TGT to validate the service ticket.
**** single sign-on initiatives
SSO gives users access to all needed applications/systems needed with one
login.
- Kerberos: A single token allows any Kerberos-enabled application to accept a
  user as valid.  Requires each application to be able to do so.
- AD: The AD server retains all access rights for network users/groups.  Upon
  user login, AD issues a GUID to the user.  AD-supporting applications use
  the GUID to provide access control.

On decentralized networks, SSO passwords are stored on each server,
representing a security risk.  Enforcing password changes helps some.

SSO has some of its own security issues, but is the simplest way to deal with
users with multiple roles/accounts.
*** understanding access control
Four primary methods of access control:
- Mandatory Access Control (MAC): All access predefined.
- Discretionary Access Control (DAC): Incorporates some flexibility.
- Role-Based Access Control (RBAC): Allows the user's role to dictate access
  capabilities.
- Rule-Based Access Control (RBAC): Limits the user to settings in
  preconfigured policies.

For high security, the standard is MAC or role-based.  For normal business and
educational environments, DAC is standard.
**** Mandatory Access Control (MAC)
Relatively inflexible, but most secure.  Users can't share info unless rights
to do so are established by administrators.  Requires much up-front thinking
about relationships.  Makes security breaches easier to investigate and
correct and information control easier.  Downside: Inflexible and requires
change over time.  If confidentiality is paramount, use MAC.
**** Discretionary Access Control (DAC)
More flexible, allowing the share of information dynamically between users.
Increases risk of unauthorized information disclosure and makes it harder to
ensure only appropriate access is issued.  Unix file permissions are an
example of DAC, with it's "other" group permissions.
**** Role-Based Access Control (RBAC)
Implement access by job function or responsibility.  Between the flexibility
of DAC and MAC.  Windows uses this.
**** Rule-Based Access Control (RBAC)
Uses preconfigured security policies, like deny lists and allow lists.  Can be
used in conjunction with role-based models to add flexibility.  Can implement
this with ACLs.
*** implementing access controlling best practices
**** least privilege
Users/systems are given the minimum privileges necessary to accomplish their
job.  Reduces the risk of privilege escalation.
**** separation of duties
Differentiation between users and groups at varying levels, e.g., root/SA,
administrative accounts, normal users, restricted accounts.

Do the following at minimum:
- Separate the SA from regular accounts and never log in as SA for routine
  functions.
- Limit SA account to minimum group.
- Separate audit/logging from SA.
**** time of day restrictions
Configuring when an account can have access.  Prevents attacks during the
majority of the time accounts aren't in use.
**** user access review
Access review is a process to determine whether a user's access level is still
appropriate.  Accounts for change in roles over time.

Continuous monitoring: Ongoing auditing of resources accessed by a user.
**** smart cards
Contain memory storing permissions and access information.  Difficult to
counterfeit but easy to steal.  Passwords/PINs are required to activate most
smart cards.
***** Common Access Card (CAC)
Used for accessing DoD computers, signing email, and implementing PKI.
***** Personal Identification Verification (PIV) card
The same as CAC, but for federal employees and contractors.
**** access control lists
Grants/denies devices access to network capabilities.
***** implicit deny
If the proviso in question has not be explicitly granted, then access is
denied.  Can be based upon IP, destination, packet type, etc.
***** firewall rules
Dictates what traffic can pass between the firewall and internal network.
Criteria:
- Block the connection.
- Allow the connection.
- Allow the connection if it's secured.

Can be applied inbound/outbound and to any network type, and should be audited
regularly.
**** port security
Allows an administrator to configure switch ports so that only certain MAC
addresses can use the port.  A feature of smart switches, which also include
Dynamic ARP Inspection (DAI) to protect ports from ARP spoofing.

Areas to be familiar with:
- MAC limiting and filtering: Limit access to known MAC addresses.  Some
  routers also have this feature.  Not foolproof.
- 802.1X: Adding port authentication to MAC filtering increases security.
- Unused ports: Disable these.
**** working with 802.1X
Defines port-based security for wireless network access control.  Adds
authentication via Extensible Authentication Protocol (EAP) over IEEE 802,
called EAP over LAN (EAPOL).  Allow APs and switches to not do authentication,
but rely on an authentication server.
**** flood guards and loop protection
Flood guard: A protection feature built into some firewalls to vary the
tolerance for unanswered login attacks.  Lessens the likelihood/success of DoS
attacks.

Loop protection: Prevents broadcast loops.  Can disable broadcast forwarding
to protect against duplicate ARP requests (those having the same target
protocol address).  The Spanning Tree Protocol (STP) ensures loop-free bridged
ethernet LANs.  STP ensures only one active path exists between two stations.
**** preventing network bridging
Network bridging: When a devices has multiple NICs where a user on one network
can jump to the other.  A problem with modern laptops with multiple adapters.
Preventable by shutting off a jack when bridging is detected.  Create profiles
where only one interface is allowed.  Disable unused connections and ICS.
**** log analylsis
Collect and analyze logs.  Store them for future baseline comparisons.
**** Trusted OS (TOS)
Any OS meeting government requirements for security.  Common Criteria (CC) are
the most common set of standards for security.  CC outlines Evaluation
Assurance Levels (EALs):
- EAL 1: Correct operation, but threats viewed as not serious.
- EAL 2: 1 + requires product developers to use good design practices.
- EAL 3: Moderate levels of security.
- EAL 4: Positive security engineering.  The common benchmark for commercial
  systems.
- EAL 5: Security engineering implemented from an early design phase.
- EAL 6: Specialized security engineering.  Secure from penetration attackers.
- EAL 7: Extremely high levels of security.  Requires extensive independent
  testing and measurement of every component.
**** secure router configuration
Musts:
- Change the default password.
- Walk through the advanced settings: Block ping requests, perform MAC
  filtering, etc.
- Keep the firmware upgraded: Router manufacturers issues patches for
  discovered problems.

Back up router configuration before changing anything.
*** review questions
1 B
2 B
3 A
4 A
5 A
6 A
7 A
8 C
9 B
10 A
11 A
12 A
13 A
14 C
15 B
16 D
17 A
18 B
19 C
20 D
*** additional notes
Tokens can be used to validate users per-session.
** Chapter 5: Protecting wireless networks
*** working with wireless systems
802.11 standards.
**** IEEE 802.11x wireless protocols
The 802.11x family of protocols provide wireless communication using radio
frequency transmissions in the 2.4GHz and 5GHz spectrum.  Except for 802.11a,
these are compatible with each other.
- 802.11: 1 or 2Mbps, 2.4GHz.
- 802.11a: Up to 54Mbps, 5GHz.
- 802.11b: Up to 11Mbps (fallback to 5.5 and 1Mbps), 2.4 GHz.  Also called
  Wi-Fi or 802.11 high rate.
- 802.11g: Up to 54Mbps, 2.4 GHz.  Higher speeds but shares space other 2.4GHz
  devices, as is the case with 802.11b.
- 802.11i: Provides security enhancements with focus on authentication.  Often
  referenced as WPA2.
- 802.11n: Up to 600Mbps (though usually much slower).  Either 2.4GHz or
  5GHz.  Most popular now due to high speeds and less interference.  Multiple
  antennas can increase speed.
**** WEP/WAP/WPA/WPA2
Wired Equivalent Privacy (WEP) was a basic wireless security with Wireless
Application Protocol (WAP) providing network communications.  Has since been
replaced with WPA/WPA2.
***** Wired Equivalent Privacy (WEP)
A wireless protocol designed to provide privacy equivalent to a wired network
(though it doesn't, WPA2 does).  Vulnerable due to weakness in encryption
algorithm used (RC4).

IV attack: The initialization vector (IV) is 24-bit, meaning IVs are reused
with the same key. Examining the repeated result allows cracking the WEP secret
key.

Temporal Key Integrity Protocol (TKIP): Strengthens WEP encryption.  Places a
128-bit wrapper around the WEP encryption with a key based upon things like
the destination MAC address and packet serial number.  However, even TKIP has
been broken.
***** Wireless Application Protocol (WAP)
A data transmission standard widely adopted by manufacturers.  WAP functions
are equivalent to TCP/IP functions as the intent is the same, but for wireless.
WAP uses a subset of HTML called Wireless Markup Language (WML) for displays.
Scripting capabilities are provided by WMLScript.  WML and WMLScript allow
malicious code/viruses to be transmitted.

WAP systems communicate via a WAP gateway.  The gateway interfaces between WAP
and HTTP and TCP/IP.  If the WAP->internet communication isn't encrypted,
packets can be sniffed.  The security concern converting between WAP and
SSL/TLS, exposing plain text, is called "gap in the WAP".  Fixed in WAP 2.0.

WAP can use WEP, WPA with TKIP, and WPA2.  WTLS is the security layer of WAP.
***** Wi-Fi Protected Access (WPA) and WPA2
Introduced in 802.11i, addressing security issues in WEP.  WPA implements some
of 802.11i to communicate with older wireless devices.  WPA uses RC4+TKIP.
WPA2 implements the full 802.11i and isn't compatible with older devices.

CCMP: WPA2 requires Counter Mode with Cipher Block Chaining Message
Authentication Code Protocol (CCMP).  CCMP users 128-bit AES encryption with a
48-bit IV.  The larger IV makes cracking difficult and minimizes replay
attacks.

Replay attack: Capturing portions of a session to play back later to convince
the host that it's still talking to the original connection.
**** Wireless Transport Layer Security (WTLS)
The security layer for WAP.  Provides authentication, encryption, and data
integrity on wireless.  Uses lower bandwidth/processing than TLS.  Moderately
secure.  WTLS is used to support devices that don't have much processing power.
*** understanding wireless devices
Use RF signalling or cellular.

Levels of security existing in WAP:
- Anonymous authentication: Allows anyone to connect to the wireless portal.
- Server authentication: Requires authentication against the server.
- Two-way (client and server) authentication: Requires both ends to
  authenticate.

Some wireless devices can use certificates to verify authentication.

Technologies providing services between devices:
- Wireless Session Protocol (WSP): Manages the session information and
  connection between devices.
- Wireless Transaction Protocol (WTP): Provides TCP/UDP analogs to WAP.
- Wireless Transport Layer Security (WTLS): Security layer for WAP.
- Wireless Datagram Protocol (WDP): Provides common interface between devices.
**** wireless access points
A low-power transmitter/receiver (transceiver), placed strategically for
wireless access, using 802.11x protocols.  Uses a portion of the RF (radio
frequency) spectrum called microwave.
***** antenna placement
Generally, the greater the distance, the more the signal will attenuate.
Materials can reflect or absorb the signal.  Some include power level controls
to reduce amount of output.  A site survey with a strength meter can be done
while laying out a network.
***** antenna types
- Omnidirectional antenna: Provide 360 patterns evenly.
- Directional antenna: Can cover a greater distance, but in a particular
  direction.
- Gain value: Rating metric for antenna.  Expressed in dBi.  Every 3 dB doubles
  the power output.
***** MAC filtering
Most APs include MAC filtering, but default it to off.  Synonymous with
"network lock".  Vulnerable to MAC spoofing.
***** captive portals
Common on public hotspots.  Requires users to agree to conditions before using
the network/Internet.
***** working with VPNs
VPNs can enhance security over wireless.
**** Extensible Authentication Protocol (EAP)
Provides a framework for authentication often used in wireless networks.
Among the types used with WPA/WPA2 are LEAP and PEAP.

Wi-Fi Protected Setup (WPS): A series of EAP messages allowing new hosts to
join the network and use WPA/WPA2.  Common in homes and small offices.
Requires users to do something to complete the enrollment process, like enter a
PIN, push a router button, or close distance for NFC.  WPS attacks are common
though, e.g., using brute force PIN attacks.  Recommend disable WPS.

Near-field communication (NFC): Requires the user to bring the client close to
the AP for verification (through RFID or Wi-Fi), validating it is present.
***** Lightweight Extensible Authentication Protocol (LEAP)
An extension to EAP by Cisco, being phased out.  Lacks Windows support.
Requires mutual authentication.  Susceptible to dictionary attacks.  Not
recommended.
***** Protected Extensible Authentication Protocol (PEAP)
The current standard EAP.  Secure through establishing an encrypted channel
between server/client.
*** wireless vulnerabilities to know
Vulnerable to all the wired attacks, plus additional wireless ones.  Easy to
intercept.  Network names are regularly broadcast via SSID broadcast.

Cloaking: SSID broadcasts can be disabled.  Requires prior knowledge of the
APs existence.  A very weak form of security.

Site surveys: While used for antenna placement, can also be done by attackers
to find systems, protocols, etc.

Jamming: Intentional interference of the signal.

War driving: Driving around with a laptop looking for APs with a NIC set to
promiscuous mode.

War chalking: Once a network weakness is discovered, writing information about
that in chalk outside the premises.

Rogue access points: Any unauthorized AP added to the network.  May not
implement proper security.

Evil twin attack: A rogue wireless AP poses as a legitimate wireless service
provider to intercept information users transmit.

Never assume wireless communication is secure.  Always use data security.  Set
APs to not broadcast. Use WPA2 and higher encryption levels.

Bluetooth is often used to create personal area networks (PANs or WPANs).
Change the default PIN on Bluetooth devices.  Set Bluetooth devices
non-discoverable.  Vulnerablities:
- Bluejacking: Sending unsolicited messages (like spam) over Bluetooth
  connections.
- Bluesnarfing: Gaining unauthorized access through a Bluetooth connection.
*** review questions
1 C
2 A
3 C
4 D
5 B
6 C
7 A
8 A
9 C
10 A
11 B
12 B
13 C
14 A
15 A
16 C
17 D
18 B
19 A
20 D
** Chapter 6: Securing the cloud
*** working with cloud computing
Service models: SaaS, PaaS, IaaS.  Delivery models: private, public, community,
hybrid.

Cloud bursting: When your servers become too busy, you offload traffic to a
cloud provider.  A form of load balancing/prioritizing, employing Quality of
Service (QoS) protocols.
**** Software as a Service (SaaS)
Provides applications running on clouds.  Used via thin client interfaces, like
the web or a program.  The consumer doesn't control the underlying
infrastructure.

Consumer: User.
Provider: Application, middleware, OS, hardware, network, facility.
**** Platform as a Service (PaaS)
Consumer can deploy consumer-created/acquired applications on the cloud, using
languages, libs, services, and tools provided by provider.

Consumer: User, application.
Provider: Middleware, OS, hardware, network, facility.
**** Infrastructure as a Service (IaaS)
Consumer able to deploy and run arbitrary software, OSes, and applications.

Consumer: User, application, middleware, OS.
Provider: Hardware, network, facility.
**** private cloud
Cloud is for exclusive use by an organization.  Organization acts as both
provider and consumer.  Doesn't need to be online.
**** public cloud
Cloud open for use by general public.  Cloud providers own public clouds.
**** community cloud
Cloud for use by specific community or organizations with shared concerns.  May
be owned/operated by some of the organizations or external.
**** hybrid cloud
Composition of two or more of public, private, community.
*** working with virtualization
Hypervisor: The software/hardware combination making virtualization possible.
Two methods of implementation exist:
- Type I hypervisor (bare metal): Independent of the OS and boots before the
  OS.
- Type II hypervisor (hosted): Dependent upon the OS and cannot boot until the
  OS is running.
**** snapshots
Allow taking of an image of the system at a point in time.  The VM can then be
reverted to a saved state.  Snapshots contain copies of the VM settings
(hardware configuration), information on all virtual disks, and memory state of
the VM.  Can be used for cloning.
**** patch compatibility
**** host availability/elasticity
**** security control testing
**** sandboxing
*** security and the cloud
**** cloud storage
*** review questions
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
** Chapter 7: Host, data, and application security
*** application hardening
**** database and technologies
**** NoSQL
**** big data
**** SAN
**** fuzzing
**** secure cloud
**** OWASP
**** CERT secure coding standards
**** application configuration baselining
**** operating system patch management
**** application patch management
*** host security
**** permissions
**** access control lists
**** antimalware
**** host software baselining
**** hardening web services
**** hardening email servers
**** hardening FTP servers
**** hardening DNS servers
**** hardening DHCP servers
*** protecting data through fault tolerance
**** backups
**** RAID
**** clustering and load balancing
*** application security
*** best practices for security
**** data loss prevention
**** hardware based encryption
*** review questions
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
** Chapter 8: Cryptography
*** an overview of cryptography
**** historical cryptography
**** substitution ciphers
**** multi-alphabet substitution
**** transposition ciphers
**** the Enigma Machine
**** steganography
**** transport encryption
*** modern cryptography
**** working with symmetric algorithms
**** key exchange
**** working with asymmetric algorithms
**** what cryptography should you use?
**** hashing algorithms
**** rainbow tables and salt
**** key stretching
**** understanding quantum cryptography
**** cryptanalysis methods
**** wi-fi encryption
*** using cryptographic services
**** confidentiality and strength
**** integrity
**** digital signatures
**** authentication
**** nonrepudiation
**** key features
*** understanding cryptography standards and protocols
**** the origins of encryption standards
**** the role of government agencies
- National Security Agency
- National Security Agency/Central Security Service
- National Institute of Standards and Technology
**** industry associations and the development process
- American Bankers Association
- Internet Engineering Task Force
- Internet Society
- World Wide Web Consortium
- International Telecommunications Union
- Institute of Electrical and Electronics Engineers
**** public-key infrastructure X.509/public-key cryptography standards
**** X.509
**** SSL and TLS
**** certificate management protocols
**** secure multipurpose internet mail extensions
**** secure eletronic transaction
**** Secure Shell
**** Pretty Good Privacy
**** HTTP Secure
**** Secure HTTP
**** IP Security
**** tunneling protocols
**** Federal Information Processing Standards (FIPS)
*** using public-key infrastructure
**** using a certificate authority
**** working with registration authorities and local registration authorities
***** implementing certificates
***** X.509
***** certificate policies
***** certificate best practices
**** understanding certificate revocation
**** implementing trust models
***** hierarchical trust models
***** bridge trust models
***** mesh trust models
***** hybrid trust model
**** hardware-based encryption devices
**** data encryption
*** review questions
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
** Chapter 9: Malware, vulnerabilities, and threats
*** understanding malware
*** surviving viruses
**** symptoms of a virus infection
**** how viruses work
**** types of viruses
**** managing spam to avoid viruses
**** antivirus software
*** understanding various type of attacks
**** identifying denial-of-service and distributed denial-of-servce attacks
**** spoofing attacks
**** pharming attacks
**** phishing, spear-phishing, and vishing
**** xmas attack
**** man-in-the-middle attacks
**** replay attacks
**** smurf attacks
**** password attacks
**** privilege escalation
**** malicious insider threats
**** transitive access
**** client-side attacks
**** typo squatting and URL hijacking
**** watering hole attack
*** identifying types of application attacks
**** cross-site scripting and forgery
**** SQL injection
**** LDAP injection
**** XML injection
**** directory traversal/command injection
**** buffer overflow
**** integer overflow
**** zero-day exploits
**** cookies and attachments
**** locally shared objects and flash cookies
**** malicious add-ons
**** session hijacking
**** header manipulation
**** arbitrary code and remote code execution
*** tools for finding threats
**** interpreting assessment results
**** tools to know
**** understanding protocol analyzers
**** working with vulnerability scanners
**** honeypots and honeynets
**** working with a port scanner
**** banner grabbing
**** risk calculations and assessment types
**** baseline reporting
**** code review
**** determine attack surface
**** architecture
**** design review
*** review questions
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
** Chapter 10: Social engineering and other foes
*** understanding social engineering
**** types of social engineering attacks
**** what motivates and attack?
**** the principles behind social engineering
**** social engineering attack examples
*** understanding physical security
**** hardware locks and security
**** mantraps
**** video surveillance
**** camera vs. guard
**** fencing
**** access list
**** proper lighting
**** signs
**** guards
**** barricades
**** biometrics
**** protected distribution
**** alarms
**** motion detection
*** environmental controls
**** HVAC
**** fire supression
**** fire extinguishers
**** fixed systems
**** EMI shielding
**** hot and cold aisles
**** environmental monitoring
**** temperature and humidity controls
*** control types
**** a control type analogy
*** data policies
**** destorying a flash drive
**** some considerations
**** optical discs
*** review questions
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
** Chapter 11: Security administration
*** third-party integration
**** transistioning
**** ongoing operations
*** understanding security awareness and training
**** communicating with users to raise awareness
**** providing education and training
**** safety topics
**** training topics
*** classifying information
**** public information
***** limited distribution
***** full distribution
**** private information
***** internal information
***** restricted information
*** information access controls
**** security concepts
*** complying with privacy and security regulations
**** the Health Insurance Portability and Accountability Act
**** the Gramm-Leach-Bliley Act
**** the Computer Fraud and Abuse Act
**** the Family Educational Rights and Privacy Act
**** the Computer Security Act of 1987
**** the Cyberspace Electronic Security Act
**** the Cyber Security Enhancement Act
**** the Patriot Act
**** familiarizing yourself with international efforts
*** mobile devices
**** BOYD issues
*** alternative methods to mitigate security risks
*** review questions
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
** Chapter 12: Disaster recovery and incident response
*** issues associated with business continuity
**** types of storage mechanisms
**** crafting a disaster-recover plan
***** understanding backup plan issues
***** knowing the backup types
***** developing a backup plan
***** recovering a system
***** backout vs. backup
***** planning for alternate sites
**** incident response policies
**** understanding incident response
***** step 1: identify the incident
***** step 2: investigating the incident
***** step 3: repair the damage
***** step 4: documenting and reporting the response
***** step 5: adjusting procedures
***** forensics from the Security+ perspective
**** succession planning
**** tabletop exercise
*** reinforcing vendor support
**** service-level agreements
**** code escrow agreements
*** penetration testings
**** what should you test?
**** vulnerability scanning
***** credentialed vs. noncredentialed
*** review questions
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


* Assessment test (first try)
1 A
2 D
3 
4 A x
5 
6 B?
7 D x
8 B? x
9 A x
10 B?
11 A 
12 A?
13 
14 D x
15 A
16 
17 C? x
18 D
19 A
20 
21 A
22 B
23 A
24 C
25 
26 
27 C x
28 C
29 
30 A
Score: 50%


* Assessment test (second try)
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
Score:


* All review questions (second try)
*** chapter 1
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
*** chapter 2
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
*** chapter 3
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
*** chapter 4
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
*** chapter 5
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
*** chapter 6
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
*** chapter 7
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
*** chapter 8
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
*** chapter 9
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
*** chapter 10
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
*** chapter 11
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
*** chapter 12
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
*** score
